/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.vanta.vanta_auditor_api.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.vanta.vanta_auditor_api.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.Optional;

/**
 * AcceptPoliciesTaskSummaryDisabled
 * 
 * <p>If the task is disabled, the reason and date when it was disabled.
 */
public class AcceptPoliciesTaskSummaryDisabled {

    @JsonProperty("date")
    private OffsetDateTime date;


    @JsonInclude(Include.ALWAYS)
    @JsonProperty("reason")
    private Optional<String> reason;

    @JsonCreator
    public AcceptPoliciesTaskSummaryDisabled(
            @JsonProperty("date") OffsetDateTime date,
            @JsonProperty("reason") Optional<String> reason) {
        Utils.checkNotNull(date, "date");
        Utils.checkNotNull(reason, "reason");
        this.date = date;
        this.reason = reason;
    }
    
    public AcceptPoliciesTaskSummaryDisabled(
            OffsetDateTime date) {
        this(date, Optional.empty());
    }

    @JsonIgnore
    public OffsetDateTime date() {
        return date;
    }

    @JsonIgnore
    public Optional<String> reason() {
        return reason;
    }

    public static Builder builder() {
        return new Builder();
    }


    public AcceptPoliciesTaskSummaryDisabled withDate(OffsetDateTime date) {
        Utils.checkNotNull(date, "date");
        this.date = date;
        return this;
    }

    public AcceptPoliciesTaskSummaryDisabled withReason(String reason) {
        Utils.checkNotNull(reason, "reason");
        this.reason = Optional.ofNullable(reason);
        return this;
    }


    public AcceptPoliciesTaskSummaryDisabled withReason(Optional<String> reason) {
        Utils.checkNotNull(reason, "reason");
        this.reason = reason;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AcceptPoliciesTaskSummaryDisabled other = (AcceptPoliciesTaskSummaryDisabled) o;
        return 
            Utils.enhancedDeepEquals(this.date, other.date) &&
            Utils.enhancedDeepEquals(this.reason, other.reason);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            date, reason);
    }
    
    @Override
    public String toString() {
        return Utils.toString(AcceptPoliciesTaskSummaryDisabled.class,
                "date", date,
                "reason", reason);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private OffsetDateTime date;

        private Optional<String> reason = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        public Builder date(OffsetDateTime date) {
            Utils.checkNotNull(date, "date");
            this.date = date;
            return this;
        }


        public Builder reason(String reason) {
            Utils.checkNotNull(reason, "reason");
            this.reason = Optional.ofNullable(reason);
            return this;
        }

        public Builder reason(Optional<String> reason) {
            Utils.checkNotNull(reason, "reason");
            this.reason = reason;
            return this;
        }

        public AcceptPoliciesTaskSummaryDisabled build() {

            return new AcceptPoliciesTaskSummaryDisabled(
                date, reason);
        }

    }
}
