/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.vanta.vanta_auditor_api.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.vanta.vanta_auditor_api.utils.Utils;
import java.lang.Override;
import java.lang.String;

/**
 * AcceptInformationRequestEvidenceInput
 * 
 * <p>Input for accepting evidence on an information request, indicating that
 * the submitted evidence meets requirements. This changes the request's
 * approvalStatus to an approved state and creates an activity log entry.
 */
public class AcceptInformationRequestEvidenceInput {
    /**
     * Email of the auditor accepting the evidence.
     * Must match an existing Vanta user who belongs to the audit firm making the API request.
     */
    @JsonProperty("auditorEmail")
    private String auditorEmail;

    @JsonCreator
    public AcceptInformationRequestEvidenceInput(
            @JsonProperty("auditorEmail") String auditorEmail) {
        Utils.checkNotNull(auditorEmail, "auditorEmail");
        this.auditorEmail = auditorEmail;
    }

    /**
     * Email of the auditor accepting the evidence.
     * Must match an existing Vanta user who belongs to the audit firm making the API request.
     */
    @JsonIgnore
    public String auditorEmail() {
        return auditorEmail;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Email of the auditor accepting the evidence.
     * Must match an existing Vanta user who belongs to the audit firm making the API request.
     */
    public AcceptInformationRequestEvidenceInput withAuditorEmail(String auditorEmail) {
        Utils.checkNotNull(auditorEmail, "auditorEmail");
        this.auditorEmail = auditorEmail;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AcceptInformationRequestEvidenceInput other = (AcceptInformationRequestEvidenceInput) o;
        return 
            Utils.enhancedDeepEquals(this.auditorEmail, other.auditorEmail);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            auditorEmail);
    }
    
    @Override
    public String toString() {
        return Utils.toString(AcceptInformationRequestEvidenceInput.class,
                "auditorEmail", auditorEmail);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String auditorEmail;

        private Builder() {
          // force use of static builder() method
        }


        /**
         * Email of the auditor accepting the evidence.
         * Must match an existing Vanta user who belongs to the audit firm making the API request.
         */
        public Builder auditorEmail(String auditorEmail) {
            Utils.checkNotNull(auditorEmail, "auditorEmail");
            this.auditorEmail = auditorEmail;
            return this;
        }

        public AcceptInformationRequestEvidenceInput build() {

            return new AcceptInformationRequestEvidenceInput(
                auditorEmail);
        }

    }
}
