/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.vanta.vanta_auditor_api.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.vanta.vanta_auditor_api.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Optional;

/**
 * AuditSegment
 * 
 * <p>One segment of an audit's scope. A live single-framework audit has exactly
 * one entry; a live multi-framework audit has one per in-scope framework
 * (and business unit or system, when applicable). Soft-deleted audits return
 * an empty list. `displayName` is the segment label owned by audit scope
 * (for example "{Framework}" or "{Framework} — {Business Unit}").
 * `soc2Deliverable` is the per-segment SOC 2 config, or null. `businessUnit`
 * is set for program segments that are BU-scoped and null otherwise. `system`
 * is set for system segments and null otherwise.
 */
public class AuditSegment {
    /**
     * The unique identifier for the segment.
     */
    @JsonProperty("id")
    private String id;


    @JsonProperty("kind")
    private AuditSegmentKind kind;

    /**
     * The segment's display label. Do not reconstruct this from framework + BU.
     */
    @JsonProperty("displayName")
    private String displayName;

    /**
     * The framework reached through a segment.
     */
    @JsonProperty("framework")
    private AuditSegmentFramework framework;

    /**
     * The business unit this program segment is scoped to, or null when the
     * segment is not BU-scoped or the BU cannot be resolved.
     */
    @JsonInclude(Include.ALWAYS)
    @JsonProperty("businessUnit")
    private Optional<? extends BusinessUnit> businessUnit;

    /**
     * The information system this system segment is scoped to, or null on
     * program segments.
     */
    @JsonInclude(Include.ALWAYS)
    @JsonProperty("system")
    private Optional<? extends System> system;

    /**
     * SOC 2 report type and Trust Services Criteria for this segment, or null.
     */
    @JsonInclude(Include.ALWAYS)
    @JsonProperty("soc2Deliverable")
    private Optional<? extends Soc2Deliverable> soc2Deliverable;

    @JsonCreator
    public AuditSegment(
            @JsonProperty("id") String id,
            @JsonProperty("kind") AuditSegmentKind kind,
            @JsonProperty("displayName") String displayName,
            @JsonProperty("framework") AuditSegmentFramework framework,
            @JsonProperty("businessUnit") Optional<? extends BusinessUnit> businessUnit,
            @JsonProperty("system") Optional<? extends System> system,
            @JsonProperty("soc2Deliverable") Optional<? extends Soc2Deliverable> soc2Deliverable) {
        Utils.checkNotNull(id, "id");
        Utils.checkNotNull(kind, "kind");
        Utils.checkNotNull(displayName, "displayName");
        Utils.checkNotNull(framework, "framework");
        Utils.checkNotNull(businessUnit, "businessUnit");
        Utils.checkNotNull(system, "system");
        Utils.checkNotNull(soc2Deliverable, "soc2Deliverable");
        this.id = id;
        this.kind = kind;
        this.displayName = displayName;
        this.framework = framework;
        this.businessUnit = businessUnit;
        this.system = system;
        this.soc2Deliverable = soc2Deliverable;
    }
    
    public AuditSegment(
            String id,
            AuditSegmentKind kind,
            String displayName,
            AuditSegmentFramework framework) {
        this(id, kind, displayName,
            framework, Optional.empty(), Optional.empty(),
            Optional.empty());
    }

    /**
     * The unique identifier for the segment.
     */
    @JsonIgnore
    public String id() {
        return id;
    }

    @JsonIgnore
    public AuditSegmentKind kind() {
        return kind;
    }

    /**
     * The segment's display label. Do not reconstruct this from framework + BU.
     */
    @JsonIgnore
    public String displayName() {
        return displayName;
    }

    /**
     * The framework reached through a segment.
     */
    @JsonIgnore
    public AuditSegmentFramework framework() {
        return framework;
    }

    /**
     * The business unit this program segment is scoped to, or null when the
     * segment is not BU-scoped or the BU cannot be resolved.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<BusinessUnit> businessUnit() {
        return (Optional<BusinessUnit>) businessUnit;
    }

    /**
     * The information system this system segment is scoped to, or null on
     * program segments.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<System> system() {
        return (Optional<System>) system;
    }

    /**
     * SOC 2 report type and Trust Services Criteria for this segment, or null.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<Soc2Deliverable> soc2Deliverable() {
        return (Optional<Soc2Deliverable>) soc2Deliverable;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The unique identifier for the segment.
     */
    public AuditSegment withId(String id) {
        Utils.checkNotNull(id, "id");
        this.id = id;
        return this;
    }

    public AuditSegment withKind(AuditSegmentKind kind) {
        Utils.checkNotNull(kind, "kind");
        this.kind = kind;
        return this;
    }

    /**
     * The segment's display label. Do not reconstruct this from framework + BU.
     */
    public AuditSegment withDisplayName(String displayName) {
        Utils.checkNotNull(displayName, "displayName");
        this.displayName = displayName;
        return this;
    }

    /**
     * The framework reached through a segment.
     */
    public AuditSegment withFramework(AuditSegmentFramework framework) {
        Utils.checkNotNull(framework, "framework");
        this.framework = framework;
        return this;
    }

    /**
     * The business unit this program segment is scoped to, or null when the
     * segment is not BU-scoped or the BU cannot be resolved.
     */
    public AuditSegment withBusinessUnit(BusinessUnit businessUnit) {
        Utils.checkNotNull(businessUnit, "businessUnit");
        this.businessUnit = Optional.ofNullable(businessUnit);
        return this;
    }


    /**
     * The business unit this program segment is scoped to, or null when the
     * segment is not BU-scoped or the BU cannot be resolved.
     */
    public AuditSegment withBusinessUnit(Optional<? extends BusinessUnit> businessUnit) {
        Utils.checkNotNull(businessUnit, "businessUnit");
        this.businessUnit = businessUnit;
        return this;
    }

    /**
     * The information system this system segment is scoped to, or null on
     * program segments.
     */
    public AuditSegment withSystem(System system) {
        Utils.checkNotNull(system, "system");
        this.system = Optional.ofNullable(system);
        return this;
    }


    /**
     * The information system this system segment is scoped to, or null on
     * program segments.
     */
    public AuditSegment withSystem(Optional<? extends System> system) {
        Utils.checkNotNull(system, "system");
        this.system = system;
        return this;
    }

    /**
     * SOC 2 report type and Trust Services Criteria for this segment, or null.
     */
    public AuditSegment withSoc2Deliverable(Soc2Deliverable soc2Deliverable) {
        Utils.checkNotNull(soc2Deliverable, "soc2Deliverable");
        this.soc2Deliverable = Optional.ofNullable(soc2Deliverable);
        return this;
    }


    /**
     * SOC 2 report type and Trust Services Criteria for this segment, or null.
     */
    public AuditSegment withSoc2Deliverable(Optional<? extends Soc2Deliverable> soc2Deliverable) {
        Utils.checkNotNull(soc2Deliverable, "soc2Deliverable");
        this.soc2Deliverable = soc2Deliverable;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AuditSegment other = (AuditSegment) o;
        return 
            Utils.enhancedDeepEquals(this.id, other.id) &&
            Utils.enhancedDeepEquals(this.kind, other.kind) &&
            Utils.enhancedDeepEquals(this.displayName, other.displayName) &&
            Utils.enhancedDeepEquals(this.framework, other.framework) &&
            Utils.enhancedDeepEquals(this.businessUnit, other.businessUnit) &&
            Utils.enhancedDeepEquals(this.system, other.system) &&
            Utils.enhancedDeepEquals(this.soc2Deliverable, other.soc2Deliverable);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            id, kind, displayName,
            framework, businessUnit, system,
            soc2Deliverable);
    }
    
    @Override
    public String toString() {
        return Utils.toString(AuditSegment.class,
                "id", id,
                "kind", kind,
                "displayName", displayName,
                "framework", framework,
                "businessUnit", businessUnit,
                "system", system,
                "soc2Deliverable", soc2Deliverable);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String id;

        private AuditSegmentKind kind;

        private String displayName;

        private AuditSegmentFramework framework;

        private Optional<? extends BusinessUnit> businessUnit = Optional.empty();

        private Optional<? extends System> system = Optional.empty();

        private Optional<? extends Soc2Deliverable> soc2Deliverable = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * The unique identifier for the segment.
         */
        public Builder id(String id) {
            Utils.checkNotNull(id, "id");
            this.id = id;
            return this;
        }


        public Builder kind(AuditSegmentKind kind) {
            Utils.checkNotNull(kind, "kind");
            this.kind = kind;
            return this;
        }


        /**
         * The segment's display label. Do not reconstruct this from framework + BU.
         */
        public Builder displayName(String displayName) {
            Utils.checkNotNull(displayName, "displayName");
            this.displayName = displayName;
            return this;
        }


        /**
         * The framework reached through a segment.
         */
        public Builder framework(AuditSegmentFramework framework) {
            Utils.checkNotNull(framework, "framework");
            this.framework = framework;
            return this;
        }


        /**
         * The business unit this program segment is scoped to, or null when the
         * segment is not BU-scoped or the BU cannot be resolved.
         */
        public Builder businessUnit(BusinessUnit businessUnit) {
            Utils.checkNotNull(businessUnit, "businessUnit");
            this.businessUnit = Optional.ofNullable(businessUnit);
            return this;
        }

        /**
         * The business unit this program segment is scoped to, or null when the
         * segment is not BU-scoped or the BU cannot be resolved.
         */
        public Builder businessUnit(Optional<? extends BusinessUnit> businessUnit) {
            Utils.checkNotNull(businessUnit, "businessUnit");
            this.businessUnit = businessUnit;
            return this;
        }


        /**
         * The information system this system segment is scoped to, or null on
         * program segments.
         */
        public Builder system(System system) {
            Utils.checkNotNull(system, "system");
            this.system = Optional.ofNullable(system);
            return this;
        }

        /**
         * The information system this system segment is scoped to, or null on
         * program segments.
         */
        public Builder system(Optional<? extends System> system) {
            Utils.checkNotNull(system, "system");
            this.system = system;
            return this;
        }


        /**
         * SOC 2 report type and Trust Services Criteria for this segment, or null.
         */
        public Builder soc2Deliverable(Soc2Deliverable soc2Deliverable) {
            Utils.checkNotNull(soc2Deliverable, "soc2Deliverable");
            this.soc2Deliverable = Optional.ofNullable(soc2Deliverable);
            return this;
        }

        /**
         * SOC 2 report type and Trust Services Criteria for this segment, or null.
         */
        public Builder soc2Deliverable(Optional<? extends Soc2Deliverable> soc2Deliverable) {
            Utils.checkNotNull(soc2Deliverable, "soc2Deliverable");
            this.soc2Deliverable = soc2Deliverable;
            return this;
        }

        public AuditSegment build() {

            return new AuditSegment(
                id, kind, displayName,
                framework, businessUnit, system,
                soc2Deliverable);
        }

    }
}
