/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.vanta.vanta_auditor_api.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * AuditControlAssessmentState
 * 
 * <p>An auditor's assessment of a control within an audit. This is the full flat
 * union of every framework's assessment states (the superset); a given audit's
 * framework only uses its own subset. `NOT_ASSESSED` is shared by all
 * frameworks and is the default for a control that has not yet been assessed.
 * 
 * <p>Which states apply to which framework:
 * - Most frameworks (e.g. SOC 2): `IN_PLACE`, `NOT_IN_PLACE`, `PARTIAL`, `NOT_ASSESSED`
 * - ISO 27001: `CONFORMING`, `MINOR_NON_CONFORMITY`, `MAJOR_NON_CONFORMITY`, `NOT_ASSESSED`
 * - FedRAMP: `SATISFIED`, `NOT_SATISFIED`, `OTHER_THAN_SATISFIED`, `NOT_ASSESSED`
 * - FedRAMP Key Security Indicators (KSI): `TRUE`, `FALSE`, `PARTIAL`, `NOT_ASSESSED`
 * 
 * <p>Distinct from `ControlStatus`, which is the computed tests/documents-passing
 * status — a different concept.
 */
public enum AuditControlAssessmentState {
    IN_PLACE("IN_PLACE"),
    NOT_IN_PLACE("NOT_IN_PLACE"),
    PARTIAL("PARTIAL"),
    NOT_ASSESSED("NOT_ASSESSED"),
    CONFORMING("CONFORMING"),
    MINOR_NON_CONFORMITY("MINOR_NON_CONFORMITY"),
    MAJOR_NON_CONFORMITY("MAJOR_NON_CONFORMITY"),
    SATISFIED("SATISFIED"),
    NOT_SATISFIED("NOT_SATISFIED"),
    OTHER_THAN_SATISFIED("OTHER_THAN_SATISFIED"),
    TRUE("TRUE"),
    FALSE("FALSE");

    @JsonValue
    private final String value;

    AuditControlAssessmentState(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<AuditControlAssessmentState> fromValue(String value) {
        for (AuditControlAssessmentState o: AuditControlAssessmentState.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

