/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.vanta.vanta_auditor_api.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.vanta.vanta_auditor_api.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.Optional;

/**
 * AuditorRequestListMetadata
 * 
 * <p>Metadata about the auditor request list. This field is only present for IRL (Information
 * Request List) based audits and will be undefined for standard audits. Use the presence
 * of this field to differentiate between IRL and non-IRL audits.
 */
public class AuditorRequestListMetadata {
    /**
     * Timestamp when information requests were shared with the customer. Null if not shared.
     */
    @JsonInclude(Include.ALWAYS)
    @JsonProperty("requestsSharedWithCustomer")
    private Optional<OffsetDateTime> requestsSharedWithCustomer;

    @JsonCreator
    public AuditorRequestListMetadata(
            @JsonProperty("requestsSharedWithCustomer") Optional<OffsetDateTime> requestsSharedWithCustomer) {
        Utils.checkNotNull(requestsSharedWithCustomer, "requestsSharedWithCustomer");
        this.requestsSharedWithCustomer = requestsSharedWithCustomer;
    }
    
    public AuditorRequestListMetadata() {
        this(Optional.empty());
    }

    /**
     * Timestamp when information requests were shared with the customer. Null if not shared.
     */
    @JsonIgnore
    public Optional<OffsetDateTime> requestsSharedWithCustomer() {
        return requestsSharedWithCustomer;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Timestamp when information requests were shared with the customer. Null if not shared.
     */
    public AuditorRequestListMetadata withRequestsSharedWithCustomer(OffsetDateTime requestsSharedWithCustomer) {
        Utils.checkNotNull(requestsSharedWithCustomer, "requestsSharedWithCustomer");
        this.requestsSharedWithCustomer = Optional.ofNullable(requestsSharedWithCustomer);
        return this;
    }


    /**
     * Timestamp when information requests were shared with the customer. Null if not shared.
     */
    public AuditorRequestListMetadata withRequestsSharedWithCustomer(Optional<OffsetDateTime> requestsSharedWithCustomer) {
        Utils.checkNotNull(requestsSharedWithCustomer, "requestsSharedWithCustomer");
        this.requestsSharedWithCustomer = requestsSharedWithCustomer;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AuditorRequestListMetadata other = (AuditorRequestListMetadata) o;
        return 
            Utils.enhancedDeepEquals(this.requestsSharedWithCustomer, other.requestsSharedWithCustomer);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            requestsSharedWithCustomer);
    }
    
    @Override
    public String toString() {
        return Utils.toString(AuditorRequestListMetadata.class,
                "requestsSharedWithCustomer", requestsSharedWithCustomer);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<OffsetDateTime> requestsSharedWithCustomer = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * Timestamp when information requests were shared with the customer. Null if not shared.
         */
        public Builder requestsSharedWithCustomer(OffsetDateTime requestsSharedWithCustomer) {
            Utils.checkNotNull(requestsSharedWithCustomer, "requestsSharedWithCustomer");
            this.requestsSharedWithCustomer = Optional.ofNullable(requestsSharedWithCustomer);
            return this;
        }

        /**
         * Timestamp when information requests were shared with the customer. Null if not shared.
         */
        public Builder requestsSharedWithCustomer(Optional<OffsetDateTime> requestsSharedWithCustomer) {
            Utils.checkNotNull(requestsSharedWithCustomer, "requestsSharedWithCustomer");
            this.requestsSharedWithCustomer = requestsSharedWithCustomer;
            return this;
        }

        public AuditorRequestListMetadata build() {

            return new AuditorRequestListMetadata(
                requestsSharedWithCustomer);
        }

    }
}
