/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.vanta.vanta_auditor_api.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.vanta.vanta_auditor_api.utils.Utils;
import java.lang.Boolean;
import java.lang.Double;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Optional;

/**
 * AuthDetails
 * 
 * <p>The vendor's authentication details.
 */
public class AuthDetails {
    /**
     * Minimum number for chacters required for passwords for this vendor.
     */
    @JsonInclude(Include.ALWAYS)
    @JsonProperty("passwordMinimumLength")
    private Optional<Double> passwordMinimumLength;

    /**
     * Whether or not the vendor requires passwords to have a symbol.
     */
    @JsonInclude(Include.ALWAYS)
    @JsonProperty("passwordRequiresSymbol")
    private Optional<Boolean> passwordRequiresSymbol;

    /**
     * Whether or not the vendor requires passwords to have a number.
     */
    @JsonInclude(Include.ALWAYS)
    @JsonProperty("passwordRequiresNumber")
    private Optional<Boolean> passwordRequiresNumber;

    /**
     * Whether or not the vendor requires passwords to have multi factor authentication.
     */
    @JsonInclude(Include.ALWAYS)
    @JsonProperty("passwordMFA")
    private Optional<Boolean> passwordMFA;

    /**
     * The vendor's authentication method.
     */
    @JsonInclude(Include.ALWAYS)
    @JsonProperty("method")
    private Optional<? extends Method> method;

    @JsonCreator
    public AuthDetails(
            @JsonProperty("passwordMinimumLength") Optional<Double> passwordMinimumLength,
            @JsonProperty("passwordRequiresSymbol") Optional<Boolean> passwordRequiresSymbol,
            @JsonProperty("passwordRequiresNumber") Optional<Boolean> passwordRequiresNumber,
            @JsonProperty("passwordMFA") Optional<Boolean> passwordMFA,
            @JsonProperty("method") Optional<? extends Method> method) {
        Utils.checkNotNull(passwordMinimumLength, "passwordMinimumLength");
        Utils.checkNotNull(passwordRequiresSymbol, "passwordRequiresSymbol");
        Utils.checkNotNull(passwordRequiresNumber, "passwordRequiresNumber");
        Utils.checkNotNull(passwordMFA, "passwordMFA");
        Utils.checkNotNull(method, "method");
        this.passwordMinimumLength = passwordMinimumLength;
        this.passwordRequiresSymbol = passwordRequiresSymbol;
        this.passwordRequiresNumber = passwordRequiresNumber;
        this.passwordMFA = passwordMFA;
        this.method = method;
    }
    
    public AuthDetails() {
        this(Optional.empty(), Optional.empty(), Optional.empty(),
            Optional.empty(), Optional.empty());
    }

    /**
     * Minimum number for chacters required for passwords for this vendor.
     */
    @JsonIgnore
    public Optional<Double> passwordMinimumLength() {
        return passwordMinimumLength;
    }

    /**
     * Whether or not the vendor requires passwords to have a symbol.
     */
    @JsonIgnore
    public Optional<Boolean> passwordRequiresSymbol() {
        return passwordRequiresSymbol;
    }

    /**
     * Whether or not the vendor requires passwords to have a number.
     */
    @JsonIgnore
    public Optional<Boolean> passwordRequiresNumber() {
        return passwordRequiresNumber;
    }

    /**
     * Whether or not the vendor requires passwords to have multi factor authentication.
     */
    @JsonIgnore
    public Optional<Boolean> passwordMFA() {
        return passwordMFA;
    }

    /**
     * The vendor's authentication method.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<Method> method() {
        return (Optional<Method>) method;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Minimum number for chacters required for passwords for this vendor.
     */
    public AuthDetails withPasswordMinimumLength(double passwordMinimumLength) {
        Utils.checkNotNull(passwordMinimumLength, "passwordMinimumLength");
        this.passwordMinimumLength = Optional.ofNullable(passwordMinimumLength);
        return this;
    }


    /**
     * Minimum number for chacters required for passwords for this vendor.
     */
    public AuthDetails withPasswordMinimumLength(Optional<Double> passwordMinimumLength) {
        Utils.checkNotNull(passwordMinimumLength, "passwordMinimumLength");
        this.passwordMinimumLength = passwordMinimumLength;
        return this;
    }

    /**
     * Whether or not the vendor requires passwords to have a symbol.
     */
    public AuthDetails withPasswordRequiresSymbol(boolean passwordRequiresSymbol) {
        Utils.checkNotNull(passwordRequiresSymbol, "passwordRequiresSymbol");
        this.passwordRequiresSymbol = Optional.ofNullable(passwordRequiresSymbol);
        return this;
    }


    /**
     * Whether or not the vendor requires passwords to have a symbol.
     */
    public AuthDetails withPasswordRequiresSymbol(Optional<Boolean> passwordRequiresSymbol) {
        Utils.checkNotNull(passwordRequiresSymbol, "passwordRequiresSymbol");
        this.passwordRequiresSymbol = passwordRequiresSymbol;
        return this;
    }

    /**
     * Whether or not the vendor requires passwords to have a number.
     */
    public AuthDetails withPasswordRequiresNumber(boolean passwordRequiresNumber) {
        Utils.checkNotNull(passwordRequiresNumber, "passwordRequiresNumber");
        this.passwordRequiresNumber = Optional.ofNullable(passwordRequiresNumber);
        return this;
    }


    /**
     * Whether or not the vendor requires passwords to have a number.
     */
    public AuthDetails withPasswordRequiresNumber(Optional<Boolean> passwordRequiresNumber) {
        Utils.checkNotNull(passwordRequiresNumber, "passwordRequiresNumber");
        this.passwordRequiresNumber = passwordRequiresNumber;
        return this;
    }

    /**
     * Whether or not the vendor requires passwords to have multi factor authentication.
     */
    public AuthDetails withPasswordMFA(boolean passwordMFA) {
        Utils.checkNotNull(passwordMFA, "passwordMFA");
        this.passwordMFA = Optional.ofNullable(passwordMFA);
        return this;
    }


    /**
     * Whether or not the vendor requires passwords to have multi factor authentication.
     */
    public AuthDetails withPasswordMFA(Optional<Boolean> passwordMFA) {
        Utils.checkNotNull(passwordMFA, "passwordMFA");
        this.passwordMFA = passwordMFA;
        return this;
    }

    /**
     * The vendor's authentication method.
     */
    public AuthDetails withMethod(Method method) {
        Utils.checkNotNull(method, "method");
        this.method = Optional.ofNullable(method);
        return this;
    }


    /**
     * The vendor's authentication method.
     */
    public AuthDetails withMethod(Optional<? extends Method> method) {
        Utils.checkNotNull(method, "method");
        this.method = method;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AuthDetails other = (AuthDetails) o;
        return 
            Utils.enhancedDeepEquals(this.passwordMinimumLength, other.passwordMinimumLength) &&
            Utils.enhancedDeepEquals(this.passwordRequiresSymbol, other.passwordRequiresSymbol) &&
            Utils.enhancedDeepEquals(this.passwordRequiresNumber, other.passwordRequiresNumber) &&
            Utils.enhancedDeepEquals(this.passwordMFA, other.passwordMFA) &&
            Utils.enhancedDeepEquals(this.method, other.method);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            passwordMinimumLength, passwordRequiresSymbol, passwordRequiresNumber,
            passwordMFA, method);
    }
    
    @Override
    public String toString() {
        return Utils.toString(AuthDetails.class,
                "passwordMinimumLength", passwordMinimumLength,
                "passwordRequiresSymbol", passwordRequiresSymbol,
                "passwordRequiresNumber", passwordRequiresNumber,
                "passwordMFA", passwordMFA,
                "method", method);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<Double> passwordMinimumLength = Optional.empty();

        private Optional<Boolean> passwordRequiresSymbol = Optional.empty();

        private Optional<Boolean> passwordRequiresNumber = Optional.empty();

        private Optional<Boolean> passwordMFA = Optional.empty();

        private Optional<? extends Method> method = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * Minimum number for chacters required for passwords for this vendor.
         */
        public Builder passwordMinimumLength(double passwordMinimumLength) {
            Utils.checkNotNull(passwordMinimumLength, "passwordMinimumLength");
            this.passwordMinimumLength = Optional.ofNullable(passwordMinimumLength);
            return this;
        }

        /**
         * Minimum number for chacters required for passwords for this vendor.
         */
        public Builder passwordMinimumLength(Optional<Double> passwordMinimumLength) {
            Utils.checkNotNull(passwordMinimumLength, "passwordMinimumLength");
            this.passwordMinimumLength = passwordMinimumLength;
            return this;
        }


        /**
         * Whether or not the vendor requires passwords to have a symbol.
         */
        public Builder passwordRequiresSymbol(boolean passwordRequiresSymbol) {
            Utils.checkNotNull(passwordRequiresSymbol, "passwordRequiresSymbol");
            this.passwordRequiresSymbol = Optional.ofNullable(passwordRequiresSymbol);
            return this;
        }

        /**
         * Whether or not the vendor requires passwords to have a symbol.
         */
        public Builder passwordRequiresSymbol(Optional<Boolean> passwordRequiresSymbol) {
            Utils.checkNotNull(passwordRequiresSymbol, "passwordRequiresSymbol");
            this.passwordRequiresSymbol = passwordRequiresSymbol;
            return this;
        }


        /**
         * Whether or not the vendor requires passwords to have a number.
         */
        public Builder passwordRequiresNumber(boolean passwordRequiresNumber) {
            Utils.checkNotNull(passwordRequiresNumber, "passwordRequiresNumber");
            this.passwordRequiresNumber = Optional.ofNullable(passwordRequiresNumber);
            return this;
        }

        /**
         * Whether or not the vendor requires passwords to have a number.
         */
        public Builder passwordRequiresNumber(Optional<Boolean> passwordRequiresNumber) {
            Utils.checkNotNull(passwordRequiresNumber, "passwordRequiresNumber");
            this.passwordRequiresNumber = passwordRequiresNumber;
            return this;
        }


        /**
         * Whether or not the vendor requires passwords to have multi factor authentication.
         */
        public Builder passwordMFA(boolean passwordMFA) {
            Utils.checkNotNull(passwordMFA, "passwordMFA");
            this.passwordMFA = Optional.ofNullable(passwordMFA);
            return this;
        }

        /**
         * Whether or not the vendor requires passwords to have multi factor authentication.
         */
        public Builder passwordMFA(Optional<Boolean> passwordMFA) {
            Utils.checkNotNull(passwordMFA, "passwordMFA");
            this.passwordMFA = passwordMFA;
            return this;
        }


        /**
         * The vendor's authentication method.
         */
        public Builder method(Method method) {
            Utils.checkNotNull(method, "method");
            this.method = Optional.ofNullable(method);
            return this;
        }

        /**
         * The vendor's authentication method.
         */
        public Builder method(Optional<? extends Method> method) {
            Utils.checkNotNull(method, "method");
            this.method = method;
            return this;
        }

        public AuthDetails build() {

            return new AuthDetails(
                passwordMinimumLength, passwordRequiresSymbol, passwordRequiresNumber,
                passwordMFA, method);
        }

    }
}
