/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.vanta.vanta_auditor_api.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.vanta.vanta_auditor_api.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.time.OffsetDateTime;
import java.util.List;
import java.util.Optional;

/**
 * CompleteTrainingsTaskSummary
 * 
 * <p>Task summary for completing all trainings.
 */
public class CompleteTrainingsTaskSummary {

    @JsonProperty("taskType")
    private TaskTypeCOMPLETETRAININGS taskType;

    /**
     * The status of a task.
     * - COMPLETE: The task has been completed.
     * - DUE_SOON: The task is due soon.
     * - OVERDUE: The task is overdue.
     * - NONE: The task is not assigned.
     */
    @JsonProperty("status")
    private TaskStatus status;

    /**
     * The due date of the task.
     */
    @JsonInclude(Include.ALWAYS)
    @JsonProperty("dueDate")
    private Optional<OffsetDateTime> dueDate;

    /**
     * The date the task was completed.
     */
    @JsonInclude(Include.ALWAYS)
    @JsonProperty("completionDate")
    private Optional<OffsetDateTime> completionDate;

    /**
     * If the task is disabled, the reason and date when it was disabled.
     */
    @JsonInclude(Include.ALWAYS)
    @JsonProperty("disabled")
    private Optional<? extends Disabled> disabled;

    /**
     * Incomplete security trainings that are relevant given a person's requirements.
     */
    @JsonProperty("incompleteTrainings")
    private List<Training> incompleteTrainings;

    /**
     * Security trainings that have been completed and are relevant given a person's current requirements.
     */
    @JsonProperty("completedTrainings")
    private List<Training> completedTrainings;

    @JsonCreator
    public CompleteTrainingsTaskSummary(
            @JsonProperty("taskType") TaskTypeCOMPLETETRAININGS taskType,
            @JsonProperty("status") TaskStatus status,
            @JsonProperty("dueDate") Optional<OffsetDateTime> dueDate,
            @JsonProperty("completionDate") Optional<OffsetDateTime> completionDate,
            @JsonProperty("disabled") Optional<? extends Disabled> disabled,
            @JsonProperty("incompleteTrainings") List<Training> incompleteTrainings,
            @JsonProperty("completedTrainings") List<Training> completedTrainings) {
        Utils.checkNotNull(taskType, "taskType");
        Utils.checkNotNull(status, "status");
        Utils.checkNotNull(dueDate, "dueDate");
        Utils.checkNotNull(completionDate, "completionDate");
        Utils.checkNotNull(disabled, "disabled");
        Utils.checkNotNull(incompleteTrainings, "incompleteTrainings");
        Utils.checkNotNull(completedTrainings, "completedTrainings");
        this.taskType = taskType;
        this.status = status;
        this.dueDate = dueDate;
        this.completionDate = completionDate;
        this.disabled = disabled;
        this.incompleteTrainings = incompleteTrainings;
        this.completedTrainings = completedTrainings;
    }
    
    public CompleteTrainingsTaskSummary(
            TaskTypeCOMPLETETRAININGS taskType,
            TaskStatus status,
            List<Training> incompleteTrainings,
            List<Training> completedTrainings) {
        this(taskType, status, Optional.empty(),
            Optional.empty(), Optional.empty(), incompleteTrainings,
            completedTrainings);
    }

    @JsonIgnore
    public TaskTypeCOMPLETETRAININGS taskType() {
        return taskType;
    }

    /**
     * The status of a task.
     * - COMPLETE: The task has been completed.
     * - DUE_SOON: The task is due soon.
     * - OVERDUE: The task is overdue.
     * - NONE: The task is not assigned.
     */
    @JsonIgnore
    public TaskStatus status() {
        return status;
    }

    /**
     * The due date of the task.
     */
    @JsonIgnore
    public Optional<OffsetDateTime> dueDate() {
        return dueDate;
    }

    /**
     * The date the task was completed.
     */
    @JsonIgnore
    public Optional<OffsetDateTime> completionDate() {
        return completionDate;
    }

    /**
     * If the task is disabled, the reason and date when it was disabled.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<Disabled> disabled() {
        return (Optional<Disabled>) disabled;
    }

    /**
     * Incomplete security trainings that are relevant given a person's requirements.
     */
    @JsonIgnore
    public List<Training> incompleteTrainings() {
        return incompleteTrainings;
    }

    /**
     * Security trainings that have been completed and are relevant given a person's current requirements.
     */
    @JsonIgnore
    public List<Training> completedTrainings() {
        return completedTrainings;
    }

    public static Builder builder() {
        return new Builder();
    }


    public CompleteTrainingsTaskSummary withTaskType(TaskTypeCOMPLETETRAININGS taskType) {
        Utils.checkNotNull(taskType, "taskType");
        this.taskType = taskType;
        return this;
    }

    /**
     * The status of a task.
     * - COMPLETE: The task has been completed.
     * - DUE_SOON: The task is due soon.
     * - OVERDUE: The task is overdue.
     * - NONE: The task is not assigned.
     */
    public CompleteTrainingsTaskSummary withStatus(TaskStatus status) {
        Utils.checkNotNull(status, "status");
        this.status = status;
        return this;
    }

    /**
     * The due date of the task.
     */
    public CompleteTrainingsTaskSummary withDueDate(OffsetDateTime dueDate) {
        Utils.checkNotNull(dueDate, "dueDate");
        this.dueDate = Optional.ofNullable(dueDate);
        return this;
    }


    /**
     * The due date of the task.
     */
    public CompleteTrainingsTaskSummary withDueDate(Optional<OffsetDateTime> dueDate) {
        Utils.checkNotNull(dueDate, "dueDate");
        this.dueDate = dueDate;
        return this;
    }

    /**
     * The date the task was completed.
     */
    public CompleteTrainingsTaskSummary withCompletionDate(OffsetDateTime completionDate) {
        Utils.checkNotNull(completionDate, "completionDate");
        this.completionDate = Optional.ofNullable(completionDate);
        return this;
    }


    /**
     * The date the task was completed.
     */
    public CompleteTrainingsTaskSummary withCompletionDate(Optional<OffsetDateTime> completionDate) {
        Utils.checkNotNull(completionDate, "completionDate");
        this.completionDate = completionDate;
        return this;
    }

    /**
     * If the task is disabled, the reason and date when it was disabled.
     */
    public CompleteTrainingsTaskSummary withDisabled(Disabled disabled) {
        Utils.checkNotNull(disabled, "disabled");
        this.disabled = Optional.ofNullable(disabled);
        return this;
    }


    /**
     * If the task is disabled, the reason and date when it was disabled.
     */
    public CompleteTrainingsTaskSummary withDisabled(Optional<? extends Disabled> disabled) {
        Utils.checkNotNull(disabled, "disabled");
        this.disabled = disabled;
        return this;
    }

    /**
     * Incomplete security trainings that are relevant given a person's requirements.
     */
    public CompleteTrainingsTaskSummary withIncompleteTrainings(List<Training> incompleteTrainings) {
        Utils.checkNotNull(incompleteTrainings, "incompleteTrainings");
        this.incompleteTrainings = incompleteTrainings;
        return this;
    }

    /**
     * Security trainings that have been completed and are relevant given a person's current requirements.
     */
    public CompleteTrainingsTaskSummary withCompletedTrainings(List<Training> completedTrainings) {
        Utils.checkNotNull(completedTrainings, "completedTrainings");
        this.completedTrainings = completedTrainings;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CompleteTrainingsTaskSummary other = (CompleteTrainingsTaskSummary) o;
        return 
            Utils.enhancedDeepEquals(this.taskType, other.taskType) &&
            Utils.enhancedDeepEquals(this.status, other.status) &&
            Utils.enhancedDeepEquals(this.dueDate, other.dueDate) &&
            Utils.enhancedDeepEquals(this.completionDate, other.completionDate) &&
            Utils.enhancedDeepEquals(this.disabled, other.disabled) &&
            Utils.enhancedDeepEquals(this.incompleteTrainings, other.incompleteTrainings) &&
            Utils.enhancedDeepEquals(this.completedTrainings, other.completedTrainings);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            taskType, status, dueDate,
            completionDate, disabled, incompleteTrainings,
            completedTrainings);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CompleteTrainingsTaskSummary.class,
                "taskType", taskType,
                "status", status,
                "dueDate", dueDate,
                "completionDate", completionDate,
                "disabled", disabled,
                "incompleteTrainings", incompleteTrainings,
                "completedTrainings", completedTrainings);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private TaskTypeCOMPLETETRAININGS taskType;

        private TaskStatus status;

        private Optional<OffsetDateTime> dueDate = Optional.empty();

        private Optional<OffsetDateTime> completionDate = Optional.empty();

        private Optional<? extends Disabled> disabled = Optional.empty();

        private List<Training> incompleteTrainings;

        private List<Training> completedTrainings;

        private Builder() {
          // force use of static builder() method
        }


        public Builder taskType(TaskTypeCOMPLETETRAININGS taskType) {
            Utils.checkNotNull(taskType, "taskType");
            this.taskType = taskType;
            return this;
        }


        /**
         * The status of a task.
         * - COMPLETE: The task has been completed.
         * - DUE_SOON: The task is due soon.
         * - OVERDUE: The task is overdue.
         * - NONE: The task is not assigned.
         */
        public Builder status(TaskStatus status) {
            Utils.checkNotNull(status, "status");
            this.status = status;
            return this;
        }


        /**
         * The due date of the task.
         */
        public Builder dueDate(OffsetDateTime dueDate) {
            Utils.checkNotNull(dueDate, "dueDate");
            this.dueDate = Optional.ofNullable(dueDate);
            return this;
        }

        /**
         * The due date of the task.
         */
        public Builder dueDate(Optional<OffsetDateTime> dueDate) {
            Utils.checkNotNull(dueDate, "dueDate");
            this.dueDate = dueDate;
            return this;
        }


        /**
         * The date the task was completed.
         */
        public Builder completionDate(OffsetDateTime completionDate) {
            Utils.checkNotNull(completionDate, "completionDate");
            this.completionDate = Optional.ofNullable(completionDate);
            return this;
        }

        /**
         * The date the task was completed.
         */
        public Builder completionDate(Optional<OffsetDateTime> completionDate) {
            Utils.checkNotNull(completionDate, "completionDate");
            this.completionDate = completionDate;
            return this;
        }


        /**
         * If the task is disabled, the reason and date when it was disabled.
         */
        public Builder disabled(Disabled disabled) {
            Utils.checkNotNull(disabled, "disabled");
            this.disabled = Optional.ofNullable(disabled);
            return this;
        }

        /**
         * If the task is disabled, the reason and date when it was disabled.
         */
        public Builder disabled(Optional<? extends Disabled> disabled) {
            Utils.checkNotNull(disabled, "disabled");
            this.disabled = disabled;
            return this;
        }


        /**
         * Incomplete security trainings that are relevant given a person's requirements.
         */
        public Builder incompleteTrainings(List<Training> incompleteTrainings) {
            Utils.checkNotNull(incompleteTrainings, "incompleteTrainings");
            this.incompleteTrainings = incompleteTrainings;
            return this;
        }


        /**
         * Security trainings that have been completed and are relevant given a person's current requirements.
         */
        public Builder completedTrainings(List<Training> completedTrainings) {
            Utils.checkNotNull(completedTrainings, "completedTrainings");
            this.completedTrainings = completedTrainings;
            return this;
        }

        public CompleteTrainingsTaskSummary build() {

            return new CompleteTrainingsTaskSummary(
                taskType, status, dueDate,
                completionDate, disabled, incompleteTrainings,
                completedTrainings);
        }

    }
}
