/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.vanta.vanta_auditor_api.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.vanta.vanta_auditor_api.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.time.OffsetDateTime;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;

/**
 * CreateInformationRequestInput
 * 
 * <p>Input for creating a new information request.
 * New requests are created in an initial state by default.
 */
public class CreateInformationRequestInput {
    /**
     * External unique ID to prevent duplicate requests across audit systems.
     * Must be unique within the audit. Used for idempotency.
     */
    @JsonProperty("uniqueId")
    private String uniqueId;

    /**
     * Short, descriptive title summarizing what is being requested.
     * Must be at least 1 character.
     */
    @JsonProperty("title")
    private String title;

    /**
     * Type of information request, defining what scope of evidence is needed.
     * 
     * <p>- POINT_IN_TIME: Evidence for a specific moment (e.g., current state of a policy)
     * - POPULATION: Evidence covering all items in a category (e.g., all employees)
     * - SAMPLE: Evidence for a representative sample (e.g., 10 random customer records)
     */
    @JsonProperty("requestType")
    private InformationRequestType requestType;

    /**
     * Detailed description explaining what evidence is needed.
     * Helps the customer understand what to submit. Optional.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("description")
    private JsonNullable<String> description;

    /**
     * Framework codes this request addresses.
     * An empty array if no framework codes are associated.
     */
    @JsonProperty("frameworkCodes")
    private List<String> frameworkCodes;

    /**
     * How frequently this request recurs. Null or omitted for one-time requests.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("cadence")
    private JsonNullable<? extends CreateInformationRequestInputCadence> cadence;

    /**
     * Deadline for fulfilling this request. Null or omitted if no deadline.
     * Format: ISO 8601 UTC timestamp.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("dueDate")
    private JsonNullable<OffsetDateTime> dueDate;

    /**
     * Start date of the audit period. Evidence before this date may not be accepted.
     * Null or omitted if not restricted.
     * Format: ISO 8601 UTC timestamp.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("evidenceCaptureDate")
    private JsonNullable<OffsetDateTime> evidenceCaptureDate;

    @JsonCreator
    public CreateInformationRequestInput(
            @JsonProperty("uniqueId") String uniqueId,
            @JsonProperty("title") String title,
            @JsonProperty("requestType") InformationRequestType requestType,
            @JsonProperty("description") JsonNullable<String> description,
            @JsonProperty("frameworkCodes") List<String> frameworkCodes,
            @JsonProperty("cadence") JsonNullable<? extends CreateInformationRequestInputCadence> cadence,
            @JsonProperty("dueDate") JsonNullable<OffsetDateTime> dueDate,
            @JsonProperty("evidenceCaptureDate") JsonNullable<OffsetDateTime> evidenceCaptureDate) {
        Utils.checkNotNull(uniqueId, "uniqueId");
        Utils.checkNotNull(title, "title");
        Utils.checkNotNull(requestType, "requestType");
        Utils.checkNotNull(description, "description");
        Utils.checkNotNull(frameworkCodes, "frameworkCodes");
        Utils.checkNotNull(cadence, "cadence");
        Utils.checkNotNull(dueDate, "dueDate");
        Utils.checkNotNull(evidenceCaptureDate, "evidenceCaptureDate");
        this.uniqueId = uniqueId;
        this.title = title;
        this.requestType = requestType;
        this.description = description;
        this.frameworkCodes = frameworkCodes;
        this.cadence = cadence;
        this.dueDate = dueDate;
        this.evidenceCaptureDate = evidenceCaptureDate;
    }
    
    public CreateInformationRequestInput(
            String uniqueId,
            String title,
            InformationRequestType requestType,
            List<String> frameworkCodes) {
        this(uniqueId, title, requestType,
            JsonNullable.undefined(), frameworkCodes, JsonNullable.undefined(),
            JsonNullable.undefined(), JsonNullable.undefined());
    }

    /**
     * External unique ID to prevent duplicate requests across audit systems.
     * Must be unique within the audit. Used for idempotency.
     */
    @JsonIgnore
    public String uniqueId() {
        return uniqueId;
    }

    /**
     * Short, descriptive title summarizing what is being requested.
     * Must be at least 1 character.
     */
    @JsonIgnore
    public String title() {
        return title;
    }

    /**
     * Type of information request, defining what scope of evidence is needed.
     * 
     * <p>- POINT_IN_TIME: Evidence for a specific moment (e.g., current state of a policy)
     * - POPULATION: Evidence covering all items in a category (e.g., all employees)
     * - SAMPLE: Evidence for a representative sample (e.g., 10 random customer records)
     */
    @JsonIgnore
    public InformationRequestType requestType() {
        return requestType;
    }

    /**
     * Detailed description explaining what evidence is needed.
     * Helps the customer understand what to submit. Optional.
     */
    @JsonIgnore
    public JsonNullable<String> description() {
        return description;
    }

    /**
     * Framework codes this request addresses.
     * An empty array if no framework codes are associated.
     */
    @JsonIgnore
    public List<String> frameworkCodes() {
        return frameworkCodes;
    }

    /**
     * How frequently this request recurs. Null or omitted for one-time requests.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public JsonNullable<CreateInformationRequestInputCadence> cadence() {
        return (JsonNullable<CreateInformationRequestInputCadence>) cadence;
    }

    /**
     * Deadline for fulfilling this request. Null or omitted if no deadline.
     * Format: ISO 8601 UTC timestamp.
     */
    @JsonIgnore
    public JsonNullable<OffsetDateTime> dueDate() {
        return dueDate;
    }

    /**
     * Start date of the audit period. Evidence before this date may not be accepted.
     * Null or omitted if not restricted.
     * Format: ISO 8601 UTC timestamp.
     */
    @JsonIgnore
    public JsonNullable<OffsetDateTime> evidenceCaptureDate() {
        return evidenceCaptureDate;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * External unique ID to prevent duplicate requests across audit systems.
     * Must be unique within the audit. Used for idempotency.
     */
    public CreateInformationRequestInput withUniqueId(String uniqueId) {
        Utils.checkNotNull(uniqueId, "uniqueId");
        this.uniqueId = uniqueId;
        return this;
    }

    /**
     * Short, descriptive title summarizing what is being requested.
     * Must be at least 1 character.
     */
    public CreateInformationRequestInput withTitle(String title) {
        Utils.checkNotNull(title, "title");
        this.title = title;
        return this;
    }

    /**
     * Type of information request, defining what scope of evidence is needed.
     * 
     * <p>- POINT_IN_TIME: Evidence for a specific moment (e.g., current state of a policy)
     * - POPULATION: Evidence covering all items in a category (e.g., all employees)
     * - SAMPLE: Evidence for a representative sample (e.g., 10 random customer records)
     */
    public CreateInformationRequestInput withRequestType(InformationRequestType requestType) {
        Utils.checkNotNull(requestType, "requestType");
        this.requestType = requestType;
        return this;
    }

    /**
     * Detailed description explaining what evidence is needed.
     * Helps the customer understand what to submit. Optional.
     */
    public CreateInformationRequestInput withDescription(String description) {
        Utils.checkNotNull(description, "description");
        this.description = JsonNullable.of(description);
        return this;
    }

    /**
     * Detailed description explaining what evidence is needed.
     * Helps the customer understand what to submit. Optional.
     */
    public CreateInformationRequestInput withDescription(JsonNullable<String> description) {
        Utils.checkNotNull(description, "description");
        this.description = description;
        return this;
    }

    /**
     * Framework codes this request addresses.
     * An empty array if no framework codes are associated.
     */
    public CreateInformationRequestInput withFrameworkCodes(List<String> frameworkCodes) {
        Utils.checkNotNull(frameworkCodes, "frameworkCodes");
        this.frameworkCodes = frameworkCodes;
        return this;
    }

    /**
     * How frequently this request recurs. Null or omitted for one-time requests.
     */
    public CreateInformationRequestInput withCadence(CreateInformationRequestInputCadence cadence) {
        Utils.checkNotNull(cadence, "cadence");
        this.cadence = JsonNullable.of(cadence);
        return this;
    }

    /**
     * How frequently this request recurs. Null or omitted for one-time requests.
     */
    public CreateInformationRequestInput withCadence(JsonNullable<? extends CreateInformationRequestInputCadence> cadence) {
        Utils.checkNotNull(cadence, "cadence");
        this.cadence = cadence;
        return this;
    }

    /**
     * Deadline for fulfilling this request. Null or omitted if no deadline.
     * Format: ISO 8601 UTC timestamp.
     */
    public CreateInformationRequestInput withDueDate(OffsetDateTime dueDate) {
        Utils.checkNotNull(dueDate, "dueDate");
        this.dueDate = JsonNullable.of(dueDate);
        return this;
    }

    /**
     * Deadline for fulfilling this request. Null or omitted if no deadline.
     * Format: ISO 8601 UTC timestamp.
     */
    public CreateInformationRequestInput withDueDate(JsonNullable<OffsetDateTime> dueDate) {
        Utils.checkNotNull(dueDate, "dueDate");
        this.dueDate = dueDate;
        return this;
    }

    /**
     * Start date of the audit period. Evidence before this date may not be accepted.
     * Null or omitted if not restricted.
     * Format: ISO 8601 UTC timestamp.
     */
    public CreateInformationRequestInput withEvidenceCaptureDate(OffsetDateTime evidenceCaptureDate) {
        Utils.checkNotNull(evidenceCaptureDate, "evidenceCaptureDate");
        this.evidenceCaptureDate = JsonNullable.of(evidenceCaptureDate);
        return this;
    }

    /**
     * Start date of the audit period. Evidence before this date may not be accepted.
     * Null or omitted if not restricted.
     * Format: ISO 8601 UTC timestamp.
     */
    public CreateInformationRequestInput withEvidenceCaptureDate(JsonNullable<OffsetDateTime> evidenceCaptureDate) {
        Utils.checkNotNull(evidenceCaptureDate, "evidenceCaptureDate");
        this.evidenceCaptureDate = evidenceCaptureDate;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreateInformationRequestInput other = (CreateInformationRequestInput) o;
        return 
            Utils.enhancedDeepEquals(this.uniqueId, other.uniqueId) &&
            Utils.enhancedDeepEquals(this.title, other.title) &&
            Utils.enhancedDeepEquals(this.requestType, other.requestType) &&
            Utils.enhancedDeepEquals(this.description, other.description) &&
            Utils.enhancedDeepEquals(this.frameworkCodes, other.frameworkCodes) &&
            Utils.enhancedDeepEquals(this.cadence, other.cadence) &&
            Utils.enhancedDeepEquals(this.dueDate, other.dueDate) &&
            Utils.enhancedDeepEquals(this.evidenceCaptureDate, other.evidenceCaptureDate);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            uniqueId, title, requestType,
            description, frameworkCodes, cadence,
            dueDate, evidenceCaptureDate);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CreateInformationRequestInput.class,
                "uniqueId", uniqueId,
                "title", title,
                "requestType", requestType,
                "description", description,
                "frameworkCodes", frameworkCodes,
                "cadence", cadence,
                "dueDate", dueDate,
                "evidenceCaptureDate", evidenceCaptureDate);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String uniqueId;

        private String title;

        private InformationRequestType requestType;

        private JsonNullable<String> description = JsonNullable.undefined();

        private List<String> frameworkCodes;

        private JsonNullable<? extends CreateInformationRequestInputCadence> cadence = JsonNullable.undefined();

        private JsonNullable<OffsetDateTime> dueDate = JsonNullable.undefined();

        private JsonNullable<OffsetDateTime> evidenceCaptureDate = JsonNullable.undefined();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * External unique ID to prevent duplicate requests across audit systems.
         * Must be unique within the audit. Used for idempotency.
         */
        public Builder uniqueId(String uniqueId) {
            Utils.checkNotNull(uniqueId, "uniqueId");
            this.uniqueId = uniqueId;
            return this;
        }


        /**
         * Short, descriptive title summarizing what is being requested.
         * Must be at least 1 character.
         */
        public Builder title(String title) {
            Utils.checkNotNull(title, "title");
            this.title = title;
            return this;
        }


        /**
         * Type of information request, defining what scope of evidence is needed.
         * 
         * <p>- POINT_IN_TIME: Evidence for a specific moment (e.g., current state of a policy)
         * - POPULATION: Evidence covering all items in a category (e.g., all employees)
         * - SAMPLE: Evidence for a representative sample (e.g., 10 random customer records)
         */
        public Builder requestType(InformationRequestType requestType) {
            Utils.checkNotNull(requestType, "requestType");
            this.requestType = requestType;
            return this;
        }


        /**
         * Detailed description explaining what evidence is needed.
         * Helps the customer understand what to submit. Optional.
         */
        public Builder description(String description) {
            Utils.checkNotNull(description, "description");
            this.description = JsonNullable.of(description);
            return this;
        }

        /**
         * Detailed description explaining what evidence is needed.
         * Helps the customer understand what to submit. Optional.
         */
        public Builder description(JsonNullable<String> description) {
            Utils.checkNotNull(description, "description");
            this.description = description;
            return this;
        }


        /**
         * Framework codes this request addresses.
         * An empty array if no framework codes are associated.
         */
        public Builder frameworkCodes(List<String> frameworkCodes) {
            Utils.checkNotNull(frameworkCodes, "frameworkCodes");
            this.frameworkCodes = frameworkCodes;
            return this;
        }


        /**
         * How frequently this request recurs. Null or omitted for one-time requests.
         */
        public Builder cadence(CreateInformationRequestInputCadence cadence) {
            Utils.checkNotNull(cadence, "cadence");
            this.cadence = JsonNullable.of(cadence);
            return this;
        }

        /**
         * How frequently this request recurs. Null or omitted for one-time requests.
         */
        public Builder cadence(JsonNullable<? extends CreateInformationRequestInputCadence> cadence) {
            Utils.checkNotNull(cadence, "cadence");
            this.cadence = cadence;
            return this;
        }


        /**
         * Deadline for fulfilling this request. Null or omitted if no deadline.
         * Format: ISO 8601 UTC timestamp.
         */
        public Builder dueDate(OffsetDateTime dueDate) {
            Utils.checkNotNull(dueDate, "dueDate");
            this.dueDate = JsonNullable.of(dueDate);
            return this;
        }

        /**
         * Deadline for fulfilling this request. Null or omitted if no deadline.
         * Format: ISO 8601 UTC timestamp.
         */
        public Builder dueDate(JsonNullable<OffsetDateTime> dueDate) {
            Utils.checkNotNull(dueDate, "dueDate");
            this.dueDate = dueDate;
            return this;
        }


        /**
         * Start date of the audit period. Evidence before this date may not be accepted.
         * Null or omitted if not restricted.
         * Format: ISO 8601 UTC timestamp.
         */
        public Builder evidenceCaptureDate(OffsetDateTime evidenceCaptureDate) {
            Utils.checkNotNull(evidenceCaptureDate, "evidenceCaptureDate");
            this.evidenceCaptureDate = JsonNullable.of(evidenceCaptureDate);
            return this;
        }

        /**
         * Start date of the audit period. Evidence before this date may not be accepted.
         * Null or omitted if not restricted.
         * Format: ISO 8601 UTC timestamp.
         */
        public Builder evidenceCaptureDate(JsonNullable<OffsetDateTime> evidenceCaptureDate) {
            Utils.checkNotNull(evidenceCaptureDate, "evidenceCaptureDate");
            this.evidenceCaptureDate = evidenceCaptureDate;
            return this;
        }

        public CreateInformationRequestInput build() {

            return new CreateInformationRequestInput(
                uniqueId, title, requestType,
                description, frameworkCodes, cadence,
                dueDate, evidenceCaptureDate);
        }

    }
}
