/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.vanta.vanta_auditor_api.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.vanta.vanta_auditor_api.utils.Utils;
import java.lang.Boolean;
import java.lang.Override;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.Optional;

/**
 * DeactivateMetadata
 * 
 * <p>Metadata for the deactivation of the vulnerability.
 */
public class DeactivateMetadata {
    /**
     * Whether the vulnerability is deactivated indefinitely.
     */
    @JsonProperty("isVulnDeactivatedIndefinitely")
    private boolean isVulnDeactivatedIndefinitely;

    /**
     * Date when the vulnerability will be reactivated.
     */
    @JsonInclude(Include.ALWAYS)
    @JsonProperty("deactivatedUntilDate")
    private Optional<OffsetDateTime> deactivatedUntilDate;

    /**
     * Reason for deactivating the vulnerability.
     */
    @JsonProperty("deactivationReason")
    private String deactivationReason;

    /**
     * Date when the vulnerability was deactivated.
     */
    @JsonProperty("deactivatedOnDate")
    private OffsetDateTime deactivatedOnDate;

    /**
     * Identifier of the user who deactivated the vulnerability.
     */
    @JsonProperty("deactivatedBy")
    private String deactivatedBy;

    @JsonCreator
    public DeactivateMetadata(
            @JsonProperty("isVulnDeactivatedIndefinitely") boolean isVulnDeactivatedIndefinitely,
            @JsonProperty("deactivatedUntilDate") Optional<OffsetDateTime> deactivatedUntilDate,
            @JsonProperty("deactivationReason") String deactivationReason,
            @JsonProperty("deactivatedOnDate") OffsetDateTime deactivatedOnDate,
            @JsonProperty("deactivatedBy") String deactivatedBy) {
        Utils.checkNotNull(isVulnDeactivatedIndefinitely, "isVulnDeactivatedIndefinitely");
        Utils.checkNotNull(deactivatedUntilDate, "deactivatedUntilDate");
        Utils.checkNotNull(deactivationReason, "deactivationReason");
        Utils.checkNotNull(deactivatedOnDate, "deactivatedOnDate");
        Utils.checkNotNull(deactivatedBy, "deactivatedBy");
        this.isVulnDeactivatedIndefinitely = isVulnDeactivatedIndefinitely;
        this.deactivatedUntilDate = deactivatedUntilDate;
        this.deactivationReason = deactivationReason;
        this.deactivatedOnDate = deactivatedOnDate;
        this.deactivatedBy = deactivatedBy;
    }
    
    public DeactivateMetadata(
            boolean isVulnDeactivatedIndefinitely,
            String deactivationReason,
            OffsetDateTime deactivatedOnDate,
            String deactivatedBy) {
        this(isVulnDeactivatedIndefinitely, Optional.empty(), deactivationReason,
            deactivatedOnDate, deactivatedBy);
    }

    /**
     * Whether the vulnerability is deactivated indefinitely.
     */
    @JsonIgnore
    public boolean isVulnDeactivatedIndefinitely() {
        return isVulnDeactivatedIndefinitely;
    }

    /**
     * Date when the vulnerability will be reactivated.
     */
    @JsonIgnore
    public Optional<OffsetDateTime> deactivatedUntilDate() {
        return deactivatedUntilDate;
    }

    /**
     * Reason for deactivating the vulnerability.
     */
    @JsonIgnore
    public String deactivationReason() {
        return deactivationReason;
    }

    /**
     * Date when the vulnerability was deactivated.
     */
    @JsonIgnore
    public OffsetDateTime deactivatedOnDate() {
        return deactivatedOnDate;
    }

    /**
     * Identifier of the user who deactivated the vulnerability.
     */
    @JsonIgnore
    public String deactivatedBy() {
        return deactivatedBy;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Whether the vulnerability is deactivated indefinitely.
     */
    public DeactivateMetadata withIsVulnDeactivatedIndefinitely(boolean isVulnDeactivatedIndefinitely) {
        Utils.checkNotNull(isVulnDeactivatedIndefinitely, "isVulnDeactivatedIndefinitely");
        this.isVulnDeactivatedIndefinitely = isVulnDeactivatedIndefinitely;
        return this;
    }

    /**
     * Date when the vulnerability will be reactivated.
     */
    public DeactivateMetadata withDeactivatedUntilDate(OffsetDateTime deactivatedUntilDate) {
        Utils.checkNotNull(deactivatedUntilDate, "deactivatedUntilDate");
        this.deactivatedUntilDate = Optional.ofNullable(deactivatedUntilDate);
        return this;
    }


    /**
     * Date when the vulnerability will be reactivated.
     */
    public DeactivateMetadata withDeactivatedUntilDate(Optional<OffsetDateTime> deactivatedUntilDate) {
        Utils.checkNotNull(deactivatedUntilDate, "deactivatedUntilDate");
        this.deactivatedUntilDate = deactivatedUntilDate;
        return this;
    }

    /**
     * Reason for deactivating the vulnerability.
     */
    public DeactivateMetadata withDeactivationReason(String deactivationReason) {
        Utils.checkNotNull(deactivationReason, "deactivationReason");
        this.deactivationReason = deactivationReason;
        return this;
    }

    /**
     * Date when the vulnerability was deactivated.
     */
    public DeactivateMetadata withDeactivatedOnDate(OffsetDateTime deactivatedOnDate) {
        Utils.checkNotNull(deactivatedOnDate, "deactivatedOnDate");
        this.deactivatedOnDate = deactivatedOnDate;
        return this;
    }

    /**
     * Identifier of the user who deactivated the vulnerability.
     */
    public DeactivateMetadata withDeactivatedBy(String deactivatedBy) {
        Utils.checkNotNull(deactivatedBy, "deactivatedBy");
        this.deactivatedBy = deactivatedBy;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DeactivateMetadata other = (DeactivateMetadata) o;
        return 
            Utils.enhancedDeepEquals(this.isVulnDeactivatedIndefinitely, other.isVulnDeactivatedIndefinitely) &&
            Utils.enhancedDeepEquals(this.deactivatedUntilDate, other.deactivatedUntilDate) &&
            Utils.enhancedDeepEquals(this.deactivationReason, other.deactivationReason) &&
            Utils.enhancedDeepEquals(this.deactivatedOnDate, other.deactivatedOnDate) &&
            Utils.enhancedDeepEquals(this.deactivatedBy, other.deactivatedBy);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            isVulnDeactivatedIndefinitely, deactivatedUntilDate, deactivationReason,
            deactivatedOnDate, deactivatedBy);
    }
    
    @Override
    public String toString() {
        return Utils.toString(DeactivateMetadata.class,
                "isVulnDeactivatedIndefinitely", isVulnDeactivatedIndefinitely,
                "deactivatedUntilDate", deactivatedUntilDate,
                "deactivationReason", deactivationReason,
                "deactivatedOnDate", deactivatedOnDate,
                "deactivatedBy", deactivatedBy);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Boolean isVulnDeactivatedIndefinitely;

        private Optional<OffsetDateTime> deactivatedUntilDate = Optional.empty();

        private String deactivationReason;

        private OffsetDateTime deactivatedOnDate;

        private String deactivatedBy;

        private Builder() {
          // force use of static builder() method
        }


        /**
         * Whether the vulnerability is deactivated indefinitely.
         */
        public Builder isVulnDeactivatedIndefinitely(boolean isVulnDeactivatedIndefinitely) {
            Utils.checkNotNull(isVulnDeactivatedIndefinitely, "isVulnDeactivatedIndefinitely");
            this.isVulnDeactivatedIndefinitely = isVulnDeactivatedIndefinitely;
            return this;
        }


        /**
         * Date when the vulnerability will be reactivated.
         */
        public Builder deactivatedUntilDate(OffsetDateTime deactivatedUntilDate) {
            Utils.checkNotNull(deactivatedUntilDate, "deactivatedUntilDate");
            this.deactivatedUntilDate = Optional.ofNullable(deactivatedUntilDate);
            return this;
        }

        /**
         * Date when the vulnerability will be reactivated.
         */
        public Builder deactivatedUntilDate(Optional<OffsetDateTime> deactivatedUntilDate) {
            Utils.checkNotNull(deactivatedUntilDate, "deactivatedUntilDate");
            this.deactivatedUntilDate = deactivatedUntilDate;
            return this;
        }


        /**
         * Reason for deactivating the vulnerability.
         */
        public Builder deactivationReason(String deactivationReason) {
            Utils.checkNotNull(deactivationReason, "deactivationReason");
            this.deactivationReason = deactivationReason;
            return this;
        }


        /**
         * Date when the vulnerability was deactivated.
         */
        public Builder deactivatedOnDate(OffsetDateTime deactivatedOnDate) {
            Utils.checkNotNull(deactivatedOnDate, "deactivatedOnDate");
            this.deactivatedOnDate = deactivatedOnDate;
            return this;
        }


        /**
         * Identifier of the user who deactivated the vulnerability.
         */
        public Builder deactivatedBy(String deactivatedBy) {
            Utils.checkNotNull(deactivatedBy, "deactivatedBy");
            this.deactivatedBy = deactivatedBy;
            return this;
        }

        public DeactivateMetadata build() {

            return new DeactivateMetadata(
                isVulnDeactivatedIndefinitely, deactivatedUntilDate, deactivationReason,
                deactivatedOnDate, deactivatedBy);
        }

    }
}
