/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.vanta.vanta_auditor_api.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.vanta.vanta_auditor_api.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.List;

/**
 * DuplicateAuditRequest
 * 
 * <p>Request body for duplicating an IRL audit into a new audit engagement.
 */
public class DuplicateAuditRequest {
    /**
     * ID of the source IRL audit to duplicate.
     */
    @JsonProperty("sourceAuditId")
    private String sourceAuditId;

    /**
     * Display name for the new audit engagement.
     */
    @JsonProperty("displayName")
    private String displayName;

    /**
     * Start of the audit window for the new audit.
     */
    @JsonProperty("auditStartDate")
    private OffsetDateTime auditStartDate;

    /**
     * End of the audit window for the new audit.
     */
    @JsonProperty("auditEndDate")
    private OffsetDateTime auditEndDate;

    /**
     * When auditors gain access to the new audit.
     */
    @JsonProperty("earlyAccessStartsAt")
    private OffsetDateTime earlyAccessStartsAt;

    /**
     * Emails of auditors who may access the new audit. Minimum one entry required.
     * Each email must match an active user in the authenticated audit firm's domain.
     */
    @JsonProperty("allowAuditorEmails")
    private List<String> allowAuditorEmails;

    @JsonCreator
    public DuplicateAuditRequest(
            @JsonProperty("sourceAuditId") String sourceAuditId,
            @JsonProperty("displayName") String displayName,
            @JsonProperty("auditStartDate") OffsetDateTime auditStartDate,
            @JsonProperty("auditEndDate") OffsetDateTime auditEndDate,
            @JsonProperty("earlyAccessStartsAt") OffsetDateTime earlyAccessStartsAt,
            @JsonProperty("allowAuditorEmails") List<String> allowAuditorEmails) {
        Utils.checkNotNull(sourceAuditId, "sourceAuditId");
        Utils.checkNotNull(displayName, "displayName");
        Utils.checkNotNull(auditStartDate, "auditStartDate");
        Utils.checkNotNull(auditEndDate, "auditEndDate");
        Utils.checkNotNull(earlyAccessStartsAt, "earlyAccessStartsAt");
        Utils.checkNotNull(allowAuditorEmails, "allowAuditorEmails");
        this.sourceAuditId = sourceAuditId;
        this.displayName = displayName;
        this.auditStartDate = auditStartDate;
        this.auditEndDate = auditEndDate;
        this.earlyAccessStartsAt = earlyAccessStartsAt;
        this.allowAuditorEmails = allowAuditorEmails;
    }

    /**
     * ID of the source IRL audit to duplicate.
     */
    @JsonIgnore
    public String sourceAuditId() {
        return sourceAuditId;
    }

    /**
     * Display name for the new audit engagement.
     */
    @JsonIgnore
    public String displayName() {
        return displayName;
    }

    /**
     * Start of the audit window for the new audit.
     */
    @JsonIgnore
    public OffsetDateTime auditStartDate() {
        return auditStartDate;
    }

    /**
     * End of the audit window for the new audit.
     */
    @JsonIgnore
    public OffsetDateTime auditEndDate() {
        return auditEndDate;
    }

    /**
     * When auditors gain access to the new audit.
     */
    @JsonIgnore
    public OffsetDateTime earlyAccessStartsAt() {
        return earlyAccessStartsAt;
    }

    /**
     * Emails of auditors who may access the new audit. Minimum one entry required.
     * Each email must match an active user in the authenticated audit firm's domain.
     */
    @JsonIgnore
    public List<String> allowAuditorEmails() {
        return allowAuditorEmails;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * ID of the source IRL audit to duplicate.
     */
    public DuplicateAuditRequest withSourceAuditId(String sourceAuditId) {
        Utils.checkNotNull(sourceAuditId, "sourceAuditId");
        this.sourceAuditId = sourceAuditId;
        return this;
    }

    /**
     * Display name for the new audit engagement.
     */
    public DuplicateAuditRequest withDisplayName(String displayName) {
        Utils.checkNotNull(displayName, "displayName");
        this.displayName = displayName;
        return this;
    }

    /**
     * Start of the audit window for the new audit.
     */
    public DuplicateAuditRequest withAuditStartDate(OffsetDateTime auditStartDate) {
        Utils.checkNotNull(auditStartDate, "auditStartDate");
        this.auditStartDate = auditStartDate;
        return this;
    }

    /**
     * End of the audit window for the new audit.
     */
    public DuplicateAuditRequest withAuditEndDate(OffsetDateTime auditEndDate) {
        Utils.checkNotNull(auditEndDate, "auditEndDate");
        this.auditEndDate = auditEndDate;
        return this;
    }

    /**
     * When auditors gain access to the new audit.
     */
    public DuplicateAuditRequest withEarlyAccessStartsAt(OffsetDateTime earlyAccessStartsAt) {
        Utils.checkNotNull(earlyAccessStartsAt, "earlyAccessStartsAt");
        this.earlyAccessStartsAt = earlyAccessStartsAt;
        return this;
    }

    /**
     * Emails of auditors who may access the new audit. Minimum one entry required.
     * Each email must match an active user in the authenticated audit firm's domain.
     */
    public DuplicateAuditRequest withAllowAuditorEmails(List<String> allowAuditorEmails) {
        Utils.checkNotNull(allowAuditorEmails, "allowAuditorEmails");
        this.allowAuditorEmails = allowAuditorEmails;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DuplicateAuditRequest other = (DuplicateAuditRequest) o;
        return 
            Utils.enhancedDeepEquals(this.sourceAuditId, other.sourceAuditId) &&
            Utils.enhancedDeepEquals(this.displayName, other.displayName) &&
            Utils.enhancedDeepEquals(this.auditStartDate, other.auditStartDate) &&
            Utils.enhancedDeepEquals(this.auditEndDate, other.auditEndDate) &&
            Utils.enhancedDeepEquals(this.earlyAccessStartsAt, other.earlyAccessStartsAt) &&
            Utils.enhancedDeepEquals(this.allowAuditorEmails, other.allowAuditorEmails);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            sourceAuditId, displayName, auditStartDate,
            auditEndDate, earlyAccessStartsAt, allowAuditorEmails);
    }
    
    @Override
    public String toString() {
        return Utils.toString(DuplicateAuditRequest.class,
                "sourceAuditId", sourceAuditId,
                "displayName", displayName,
                "auditStartDate", auditStartDate,
                "auditEndDate", auditEndDate,
                "earlyAccessStartsAt", earlyAccessStartsAt,
                "allowAuditorEmails", allowAuditorEmails);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String sourceAuditId;

        private String displayName;

        private OffsetDateTime auditStartDate;

        private OffsetDateTime auditEndDate;

        private OffsetDateTime earlyAccessStartsAt;

        private List<String> allowAuditorEmails;

        private Builder() {
          // force use of static builder() method
        }


        /**
         * ID of the source IRL audit to duplicate.
         */
        public Builder sourceAuditId(String sourceAuditId) {
            Utils.checkNotNull(sourceAuditId, "sourceAuditId");
            this.sourceAuditId = sourceAuditId;
            return this;
        }


        /**
         * Display name for the new audit engagement.
         */
        public Builder displayName(String displayName) {
            Utils.checkNotNull(displayName, "displayName");
            this.displayName = displayName;
            return this;
        }


        /**
         * Start of the audit window for the new audit.
         */
        public Builder auditStartDate(OffsetDateTime auditStartDate) {
            Utils.checkNotNull(auditStartDate, "auditStartDate");
            this.auditStartDate = auditStartDate;
            return this;
        }


        /**
         * End of the audit window for the new audit.
         */
        public Builder auditEndDate(OffsetDateTime auditEndDate) {
            Utils.checkNotNull(auditEndDate, "auditEndDate");
            this.auditEndDate = auditEndDate;
            return this;
        }


        /**
         * When auditors gain access to the new audit.
         */
        public Builder earlyAccessStartsAt(OffsetDateTime earlyAccessStartsAt) {
            Utils.checkNotNull(earlyAccessStartsAt, "earlyAccessStartsAt");
            this.earlyAccessStartsAt = earlyAccessStartsAt;
            return this;
        }


        /**
         * Emails of auditors who may access the new audit. Minimum one entry required.
         * Each email must match an active user in the authenticated audit firm's domain.
         */
        public Builder allowAuditorEmails(List<String> allowAuditorEmails) {
            Utils.checkNotNull(allowAuditorEmails, "allowAuditorEmails");
            this.allowAuditorEmails = allowAuditorEmails;
            return this;
        }

        public DuplicateAuditRequest build() {

            return new DuplicateAuditRequest(
                sourceAuditId, displayName, auditStartDate,
                auditEndDate, earlyAccessStartsAt, allowAuditorEmails);
        }

    }
}
