/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.vanta.vanta_auditor_api.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.vanta.vanta_auditor_api.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.Optional;

/**
 * InformationRequestComment
 * 
 * <p>A comment on an information request enables communication between auditors
 * and customers regarding evidence requirements and submissions.
 * 
 * <p>These threaded discussions help clarify requests, explain or resolve questions about evidence,
 * and are always visible to both parties once created.
 */
public class InformationRequestComment {
    /**
     * The unique identifier for the comment within Vanta's system.
     * Format: ObjectId as a string (e.g., "6890e473dce1da5d8406f5e7").
     */
    @JsonProperty("id")
    private String id;

    /**
     * The comment message content.
     * Can include explanations, questions, or clarifications about the information request.
     */
    @JsonProperty("text")
    private String text;

    /**
     * Timestamp when the comment was created.
     * Format: ISO 8601 UTC timestamp.
     */
    @JsonProperty("creationDate")
    private OffsetDateTime creationDate;

    /**
     * Timestamp when the comment was last edited.
     * Null if the comment has never been modified.
     * Format: ISO 8601 UTC timestamp.
     */
    @JsonInclude(Include.ALWAYS)
    @JsonProperty("modificationDate")
    private Optional<OffsetDateTime> modificationDate;

    /**
     * Timestamp when the comment was soft-deleted.
     * Null if the comment has not been deleted.
     * Soft deletes retain the comment for audit history while hiding it from normal operations.
     * Format: ISO 8601 UTC timestamp.
     */
    @JsonInclude(Include.ALWAYS)
    @JsonProperty("deletionDate")
    private Optional<OffsetDateTime> deletionDate;

    /**
     * Email address of the comment author.
     * This email uniquely identifies users between Vanta and external audit systems.
     */
    @JsonInclude(Include.ALWAYS)
    @JsonProperty("email")
    private Optional<String> email;

    /**
     * Human-readable display name of the comment author.
     * Null if the author's name is not available (e.g., user was deleted).
     * This enables correct author attribution in integrations where users cannot
     * be reliably matched across systems by email alone.
     */
    @JsonInclude(Include.ALWAYS)
    @JsonProperty("authorName")
    private Optional<String> authorName;

    @JsonCreator
    public InformationRequestComment(
            @JsonProperty("id") String id,
            @JsonProperty("text") String text,
            @JsonProperty("creationDate") OffsetDateTime creationDate,
            @JsonProperty("modificationDate") Optional<OffsetDateTime> modificationDate,
            @JsonProperty("deletionDate") Optional<OffsetDateTime> deletionDate,
            @JsonProperty("email") Optional<String> email,
            @JsonProperty("authorName") Optional<String> authorName) {
        Utils.checkNotNull(id, "id");
        Utils.checkNotNull(text, "text");
        Utils.checkNotNull(creationDate, "creationDate");
        Utils.checkNotNull(modificationDate, "modificationDate");
        Utils.checkNotNull(deletionDate, "deletionDate");
        Utils.checkNotNull(email, "email");
        Utils.checkNotNull(authorName, "authorName");
        this.id = id;
        this.text = text;
        this.creationDate = creationDate;
        this.modificationDate = modificationDate;
        this.deletionDate = deletionDate;
        this.email = email;
        this.authorName = authorName;
    }
    
    public InformationRequestComment(
            String id,
            String text,
            OffsetDateTime creationDate) {
        this(id, text, creationDate,
            Optional.empty(), Optional.empty(), Optional.empty(),
            Optional.empty());
    }

    /**
     * The unique identifier for the comment within Vanta's system.
     * Format: ObjectId as a string (e.g., "6890e473dce1da5d8406f5e7").
     */
    @JsonIgnore
    public String id() {
        return id;
    }

    /**
     * The comment message content.
     * Can include explanations, questions, or clarifications about the information request.
     */
    @JsonIgnore
    public String text() {
        return text;
    }

    /**
     * Timestamp when the comment was created.
     * Format: ISO 8601 UTC timestamp.
     */
    @JsonIgnore
    public OffsetDateTime creationDate() {
        return creationDate;
    }

    /**
     * Timestamp when the comment was last edited.
     * Null if the comment has never been modified.
     * Format: ISO 8601 UTC timestamp.
     */
    @JsonIgnore
    public Optional<OffsetDateTime> modificationDate() {
        return modificationDate;
    }

    /**
     * Timestamp when the comment was soft-deleted.
     * Null if the comment has not been deleted.
     * Soft deletes retain the comment for audit history while hiding it from normal operations.
     * Format: ISO 8601 UTC timestamp.
     */
    @JsonIgnore
    public Optional<OffsetDateTime> deletionDate() {
        return deletionDate;
    }

    /**
     * Email address of the comment author.
     * This email uniquely identifies users between Vanta and external audit systems.
     */
    @JsonIgnore
    public Optional<String> email() {
        return email;
    }

    /**
     * Human-readable display name of the comment author.
     * Null if the author's name is not available (e.g., user was deleted).
     * This enables correct author attribution in integrations where users cannot
     * be reliably matched across systems by email alone.
     */
    @JsonIgnore
    public Optional<String> authorName() {
        return authorName;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The unique identifier for the comment within Vanta's system.
     * Format: ObjectId as a string (e.g., "6890e473dce1da5d8406f5e7").
     */
    public InformationRequestComment withId(String id) {
        Utils.checkNotNull(id, "id");
        this.id = id;
        return this;
    }

    /**
     * The comment message content.
     * Can include explanations, questions, or clarifications about the information request.
     */
    public InformationRequestComment withText(String text) {
        Utils.checkNotNull(text, "text");
        this.text = text;
        return this;
    }

    /**
     * Timestamp when the comment was created.
     * Format: ISO 8601 UTC timestamp.
     */
    public InformationRequestComment withCreationDate(OffsetDateTime creationDate) {
        Utils.checkNotNull(creationDate, "creationDate");
        this.creationDate = creationDate;
        return this;
    }

    /**
     * Timestamp when the comment was last edited.
     * Null if the comment has never been modified.
     * Format: ISO 8601 UTC timestamp.
     */
    public InformationRequestComment withModificationDate(OffsetDateTime modificationDate) {
        Utils.checkNotNull(modificationDate, "modificationDate");
        this.modificationDate = Optional.ofNullable(modificationDate);
        return this;
    }


    /**
     * Timestamp when the comment was last edited.
     * Null if the comment has never been modified.
     * Format: ISO 8601 UTC timestamp.
     */
    public InformationRequestComment withModificationDate(Optional<OffsetDateTime> modificationDate) {
        Utils.checkNotNull(modificationDate, "modificationDate");
        this.modificationDate = modificationDate;
        return this;
    }

    /**
     * Timestamp when the comment was soft-deleted.
     * Null if the comment has not been deleted.
     * Soft deletes retain the comment for audit history while hiding it from normal operations.
     * Format: ISO 8601 UTC timestamp.
     */
    public InformationRequestComment withDeletionDate(OffsetDateTime deletionDate) {
        Utils.checkNotNull(deletionDate, "deletionDate");
        this.deletionDate = Optional.ofNullable(deletionDate);
        return this;
    }


    /**
     * Timestamp when the comment was soft-deleted.
     * Null if the comment has not been deleted.
     * Soft deletes retain the comment for audit history while hiding it from normal operations.
     * Format: ISO 8601 UTC timestamp.
     */
    public InformationRequestComment withDeletionDate(Optional<OffsetDateTime> deletionDate) {
        Utils.checkNotNull(deletionDate, "deletionDate");
        this.deletionDate = deletionDate;
        return this;
    }

    /**
     * Email address of the comment author.
     * This email uniquely identifies users between Vanta and external audit systems.
     */
    public InformationRequestComment withEmail(String email) {
        Utils.checkNotNull(email, "email");
        this.email = Optional.ofNullable(email);
        return this;
    }


    /**
     * Email address of the comment author.
     * This email uniquely identifies users between Vanta and external audit systems.
     */
    public InformationRequestComment withEmail(Optional<String> email) {
        Utils.checkNotNull(email, "email");
        this.email = email;
        return this;
    }

    /**
     * Human-readable display name of the comment author.
     * Null if the author's name is not available (e.g., user was deleted).
     * This enables correct author attribution in integrations where users cannot
     * be reliably matched across systems by email alone.
     */
    public InformationRequestComment withAuthorName(String authorName) {
        Utils.checkNotNull(authorName, "authorName");
        this.authorName = Optional.ofNullable(authorName);
        return this;
    }


    /**
     * Human-readable display name of the comment author.
     * Null if the author's name is not available (e.g., user was deleted).
     * This enables correct author attribution in integrations where users cannot
     * be reliably matched across systems by email alone.
     */
    public InformationRequestComment withAuthorName(Optional<String> authorName) {
        Utils.checkNotNull(authorName, "authorName");
        this.authorName = authorName;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        InformationRequestComment other = (InformationRequestComment) o;
        return 
            Utils.enhancedDeepEquals(this.id, other.id) &&
            Utils.enhancedDeepEquals(this.text, other.text) &&
            Utils.enhancedDeepEquals(this.creationDate, other.creationDate) &&
            Utils.enhancedDeepEquals(this.modificationDate, other.modificationDate) &&
            Utils.enhancedDeepEquals(this.deletionDate, other.deletionDate) &&
            Utils.enhancedDeepEquals(this.email, other.email) &&
            Utils.enhancedDeepEquals(this.authorName, other.authorName);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            id, text, creationDate,
            modificationDate, deletionDate, email,
            authorName);
    }
    
    @Override
    public String toString() {
        return Utils.toString(InformationRequestComment.class,
                "id", id,
                "text", text,
                "creationDate", creationDate,
                "modificationDate", modificationDate,
                "deletionDate", deletionDate,
                "email", email,
                "authorName", authorName);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String id;

        private String text;

        private OffsetDateTime creationDate;

        private Optional<OffsetDateTime> modificationDate = Optional.empty();

        private Optional<OffsetDateTime> deletionDate = Optional.empty();

        private Optional<String> email = Optional.empty();

        private Optional<String> authorName = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * The unique identifier for the comment within Vanta's system.
         * Format: ObjectId as a string (e.g., "6890e473dce1da5d8406f5e7").
         */
        public Builder id(String id) {
            Utils.checkNotNull(id, "id");
            this.id = id;
            return this;
        }


        /**
         * The comment message content.
         * Can include explanations, questions, or clarifications about the information request.
         */
        public Builder text(String text) {
            Utils.checkNotNull(text, "text");
            this.text = text;
            return this;
        }


        /**
         * Timestamp when the comment was created.
         * Format: ISO 8601 UTC timestamp.
         */
        public Builder creationDate(OffsetDateTime creationDate) {
            Utils.checkNotNull(creationDate, "creationDate");
            this.creationDate = creationDate;
            return this;
        }


        /**
         * Timestamp when the comment was last edited.
         * Null if the comment has never been modified.
         * Format: ISO 8601 UTC timestamp.
         */
        public Builder modificationDate(OffsetDateTime modificationDate) {
            Utils.checkNotNull(modificationDate, "modificationDate");
            this.modificationDate = Optional.ofNullable(modificationDate);
            return this;
        }

        /**
         * Timestamp when the comment was last edited.
         * Null if the comment has never been modified.
         * Format: ISO 8601 UTC timestamp.
         */
        public Builder modificationDate(Optional<OffsetDateTime> modificationDate) {
            Utils.checkNotNull(modificationDate, "modificationDate");
            this.modificationDate = modificationDate;
            return this;
        }


        /**
         * Timestamp when the comment was soft-deleted.
         * Null if the comment has not been deleted.
         * Soft deletes retain the comment for audit history while hiding it from normal operations.
         * Format: ISO 8601 UTC timestamp.
         */
        public Builder deletionDate(OffsetDateTime deletionDate) {
            Utils.checkNotNull(deletionDate, "deletionDate");
            this.deletionDate = Optional.ofNullable(deletionDate);
            return this;
        }

        /**
         * Timestamp when the comment was soft-deleted.
         * Null if the comment has not been deleted.
         * Soft deletes retain the comment for audit history while hiding it from normal operations.
         * Format: ISO 8601 UTC timestamp.
         */
        public Builder deletionDate(Optional<OffsetDateTime> deletionDate) {
            Utils.checkNotNull(deletionDate, "deletionDate");
            this.deletionDate = deletionDate;
            return this;
        }


        /**
         * Email address of the comment author.
         * This email uniquely identifies users between Vanta and external audit systems.
         */
        public Builder email(String email) {
            Utils.checkNotNull(email, "email");
            this.email = Optional.ofNullable(email);
            return this;
        }

        /**
         * Email address of the comment author.
         * This email uniquely identifies users between Vanta and external audit systems.
         */
        public Builder email(Optional<String> email) {
            Utils.checkNotNull(email, "email");
            this.email = email;
            return this;
        }


        /**
         * Human-readable display name of the comment author.
         * Null if the author's name is not available (e.g., user was deleted).
         * This enables correct author attribution in integrations where users cannot
         * be reliably matched across systems by email alone.
         */
        public Builder authorName(String authorName) {
            Utils.checkNotNull(authorName, "authorName");
            this.authorName = Optional.ofNullable(authorName);
            return this;
        }

        /**
         * Human-readable display name of the comment author.
         * Null if the author's name is not available (e.g., user was deleted).
         * This enables correct author attribution in integrations where users cannot
         * be reliably matched across systems by email alone.
         */
        public Builder authorName(Optional<String> authorName) {
            Utils.checkNotNull(authorName, "authorName");
            this.authorName = authorName;
            return this;
        }

        public InformationRequestComment build() {

            return new InformationRequestComment(
                id, text, creationDate,
                modificationDate, deletionDate, email,
                authorName);
        }

    }
}
