/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.vanta.vanta_auditor_api.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * InformationRequestCadence
 * 
 * <p>Frequency cadence for the information request, indicating how often it recurs.
 */
public enum InformationRequestCadence {
    ANNUALLY("ANNUALLY"),
    BIANNUALLY("BIANNUALLY"),
    MONTHLY("MONTHLY"),
    QUARTERLY("QUARTERLY");

    @JsonValue
    private final String value;

    InformationRequestCadence(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<InformationRequestCadence> fromValue(String value) {
        for (InformationRequestCadence o: InformationRequestCadence.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

