/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.vanta.vanta_auditor_api.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * InformationRequestApprovalStatus
 * 
 * <p>Current approval status of the information request, tracking its lifecycle through the audit
 * process.
 * 
 * <p>The status progresses through the workflow: initial state → awaiting review → approved or flagged.
 * Status can move between awaiting review and flagged states as evidence is reviewed and resubmitted.
 */
public enum InformationRequestApprovalStatus {
    NEEDS_EVIDENCE("NEEDS_EVIDENCE"),
    READY_FOR_AUDIT("READY_FOR_AUDIT"),
    AUDITOR_APPROVED("AUDITOR_APPROVED"),
    AUDITOR_FLAGGED("AUDITOR_FLAGGED");

    @JsonValue
    private final String value;

    InformationRequestApprovalStatus(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<InformationRequestApprovalStatus> fromValue(String value) {
        for (InformationRequestApprovalStatus o: InformationRequestApprovalStatus.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

