/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.vanta.vanta_auditor_api.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * IssueSnapshotItemOrderBy
 * 
 * <p>Allowed values for the `orderBy` query parameter on issue snapshot item endpoints.
 */
public enum IssueSnapshotItemOrderBy {
    CREATED_AT("createdAt"),
    LAST_MODIFIED_AT("lastModifiedAt"),
    DETECTED_AT("detectedAt");

    @JsonValue
    private final String value;

    IssueSnapshotItemOrderBy(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<IssueSnapshotItemOrderBy> fromValue(String value) {
        for (IssueSnapshotItemOrderBy o: IssueSnapshotItemOrderBy.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

