/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.vanta.vanta_auditor_api.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.vanta.vanta_auditor_api.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.time.OffsetDateTime;
import java.util.Optional;


public class MonitoredComputer {
    /**
     * Unique identifier for the monitored computer.
     */
    @JsonProperty("id")
    private String id;

    /**
     * Hard-coded enums for Vanta-built integrations or application IDs for 3rd-party-built integrations.
     */
    @JsonProperty("integrationId")
    private String integrationId;

    /**
     * Date of the computer's most recent report.
     */
    @JsonInclude(Include.ALWAYS)
    @JsonProperty("lastCheckDate")
    private Optional<OffsetDateTime> lastCheckDate;

    /**
     * The a status check for a computer. Representation for screenlock, diskEncryption, passwordManager,
     * and antivirusInstallation.
     */
    @JsonProperty("screenlock")
    private ComputerStatus screenlock;

    /**
     * The a status check for a computer. Representation for screenlock, diskEncryption, passwordManager,
     * and antivirusInstallation.
     */
    @JsonProperty("diskEncryption")
    private ComputerStatus diskEncryption;

    /**
     * The a status check for a computer. Representation for screenlock, diskEncryption, passwordManager,
     * and antivirusInstallation.
     */
    @JsonProperty("passwordManager")
    private ComputerStatus passwordManager;

    /**
     * The a status check for a computer. Representation for screenlock, diskEncryption, passwordManager,
     * and antivirusInstallation.
     */
    @JsonProperty("antivirusInstallation")
    private ComputerStatus antivirusInstallation;

    /**
     * The computer's operating system name and version.
     */
    @JsonInclude(Include.ALWAYS)
    @JsonProperty("operatingSystem")
    private Optional<? extends OperatingSystem> operatingSystem;

    /**
     * The name, unique identifier, and email address of the computer's owner.
     */
    @JsonInclude(Include.ALWAYS)
    @JsonProperty("owner")
    private Optional<? extends MonitoredComputerOwner> owner;

    /**
     * The serial number of the computer. This value may be null if it is not reported by the device.
     */
    @JsonInclude(Include.ALWAYS)
    @JsonProperty("serialNumber")
    private Optional<String> serialNumber;

    /**
     * The universal device id of the computer.
     */
    @JsonInclude(Include.ALWAYS)
    @JsonProperty("udid")
    private Optional<String> udid;

    @JsonCreator
    public MonitoredComputer(
            @JsonProperty("id") String id,
            @JsonProperty("integrationId") String integrationId,
            @JsonProperty("lastCheckDate") Optional<OffsetDateTime> lastCheckDate,
            @JsonProperty("screenlock") ComputerStatus screenlock,
            @JsonProperty("diskEncryption") ComputerStatus diskEncryption,
            @JsonProperty("passwordManager") ComputerStatus passwordManager,
            @JsonProperty("antivirusInstallation") ComputerStatus antivirusInstallation,
            @JsonProperty("operatingSystem") Optional<? extends OperatingSystem> operatingSystem,
            @JsonProperty("owner") Optional<? extends MonitoredComputerOwner> owner,
            @JsonProperty("serialNumber") Optional<String> serialNumber,
            @JsonProperty("udid") Optional<String> udid) {
        Utils.checkNotNull(id, "id");
        Utils.checkNotNull(integrationId, "integrationId");
        Utils.checkNotNull(lastCheckDate, "lastCheckDate");
        Utils.checkNotNull(screenlock, "screenlock");
        Utils.checkNotNull(diskEncryption, "diskEncryption");
        Utils.checkNotNull(passwordManager, "passwordManager");
        Utils.checkNotNull(antivirusInstallation, "antivirusInstallation");
        Utils.checkNotNull(operatingSystem, "operatingSystem");
        Utils.checkNotNull(owner, "owner");
        Utils.checkNotNull(serialNumber, "serialNumber");
        Utils.checkNotNull(udid, "udid");
        this.id = id;
        this.integrationId = integrationId;
        this.lastCheckDate = lastCheckDate;
        this.screenlock = screenlock;
        this.diskEncryption = diskEncryption;
        this.passwordManager = passwordManager;
        this.antivirusInstallation = antivirusInstallation;
        this.operatingSystem = operatingSystem;
        this.owner = owner;
        this.serialNumber = serialNumber;
        this.udid = udid;
    }
    
    public MonitoredComputer(
            String id,
            String integrationId,
            ComputerStatus screenlock,
            ComputerStatus diskEncryption,
            ComputerStatus passwordManager,
            ComputerStatus antivirusInstallation) {
        this(id, integrationId, Optional.empty(),
            screenlock, diskEncryption, passwordManager,
            antivirusInstallation, Optional.empty(), Optional.empty(),
            Optional.empty(), Optional.empty());
    }

    /**
     * Unique identifier for the monitored computer.
     */
    @JsonIgnore
    public String id() {
        return id;
    }

    /**
     * Hard-coded enums for Vanta-built integrations or application IDs for 3rd-party-built integrations.
     */
    @JsonIgnore
    public String integrationId() {
        return integrationId;
    }

    /**
     * Date of the computer's most recent report.
     */
    @JsonIgnore
    public Optional<OffsetDateTime> lastCheckDate() {
        return lastCheckDate;
    }

    /**
     * The a status check for a computer. Representation for screenlock, diskEncryption, passwordManager,
     * and antivirusInstallation.
     */
    @JsonIgnore
    public ComputerStatus screenlock() {
        return screenlock;
    }

    /**
     * The a status check for a computer. Representation for screenlock, diskEncryption, passwordManager,
     * and antivirusInstallation.
     */
    @JsonIgnore
    public ComputerStatus diskEncryption() {
        return diskEncryption;
    }

    /**
     * The a status check for a computer. Representation for screenlock, diskEncryption, passwordManager,
     * and antivirusInstallation.
     */
    @JsonIgnore
    public ComputerStatus passwordManager() {
        return passwordManager;
    }

    /**
     * The a status check for a computer. Representation for screenlock, diskEncryption, passwordManager,
     * and antivirusInstallation.
     */
    @JsonIgnore
    public ComputerStatus antivirusInstallation() {
        return antivirusInstallation;
    }

    /**
     * The computer's operating system name and version.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<OperatingSystem> operatingSystem() {
        return (Optional<OperatingSystem>) operatingSystem;
    }

    /**
     * The name, unique identifier, and email address of the computer's owner.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<MonitoredComputerOwner> owner() {
        return (Optional<MonitoredComputerOwner>) owner;
    }

    /**
     * The serial number of the computer. This value may be null if it is not reported by the device.
     */
    @JsonIgnore
    public Optional<String> serialNumber() {
        return serialNumber;
    }

    /**
     * The universal device id of the computer.
     */
    @JsonIgnore
    public Optional<String> udid() {
        return udid;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Unique identifier for the monitored computer.
     */
    public MonitoredComputer withId(String id) {
        Utils.checkNotNull(id, "id");
        this.id = id;
        return this;
    }

    /**
     * Hard-coded enums for Vanta-built integrations or application IDs for 3rd-party-built integrations.
     */
    public MonitoredComputer withIntegrationId(String integrationId) {
        Utils.checkNotNull(integrationId, "integrationId");
        this.integrationId = integrationId;
        return this;
    }

    /**
     * Date of the computer's most recent report.
     */
    public MonitoredComputer withLastCheckDate(OffsetDateTime lastCheckDate) {
        Utils.checkNotNull(lastCheckDate, "lastCheckDate");
        this.lastCheckDate = Optional.ofNullable(lastCheckDate);
        return this;
    }


    /**
     * Date of the computer's most recent report.
     */
    public MonitoredComputer withLastCheckDate(Optional<OffsetDateTime> lastCheckDate) {
        Utils.checkNotNull(lastCheckDate, "lastCheckDate");
        this.lastCheckDate = lastCheckDate;
        return this;
    }

    /**
     * The a status check for a computer. Representation for screenlock, diskEncryption, passwordManager,
     * and antivirusInstallation.
     */
    public MonitoredComputer withScreenlock(ComputerStatus screenlock) {
        Utils.checkNotNull(screenlock, "screenlock");
        this.screenlock = screenlock;
        return this;
    }

    /**
     * The a status check for a computer. Representation for screenlock, diskEncryption, passwordManager,
     * and antivirusInstallation.
     */
    public MonitoredComputer withDiskEncryption(ComputerStatus diskEncryption) {
        Utils.checkNotNull(diskEncryption, "diskEncryption");
        this.diskEncryption = diskEncryption;
        return this;
    }

    /**
     * The a status check for a computer. Representation for screenlock, diskEncryption, passwordManager,
     * and antivirusInstallation.
     */
    public MonitoredComputer withPasswordManager(ComputerStatus passwordManager) {
        Utils.checkNotNull(passwordManager, "passwordManager");
        this.passwordManager = passwordManager;
        return this;
    }

    /**
     * The a status check for a computer. Representation for screenlock, diskEncryption, passwordManager,
     * and antivirusInstallation.
     */
    public MonitoredComputer withAntivirusInstallation(ComputerStatus antivirusInstallation) {
        Utils.checkNotNull(antivirusInstallation, "antivirusInstallation");
        this.antivirusInstallation = antivirusInstallation;
        return this;
    }

    /**
     * The computer's operating system name and version.
     */
    public MonitoredComputer withOperatingSystem(OperatingSystem operatingSystem) {
        Utils.checkNotNull(operatingSystem, "operatingSystem");
        this.operatingSystem = Optional.ofNullable(operatingSystem);
        return this;
    }


    /**
     * The computer's operating system name and version.
     */
    public MonitoredComputer withOperatingSystem(Optional<? extends OperatingSystem> operatingSystem) {
        Utils.checkNotNull(operatingSystem, "operatingSystem");
        this.operatingSystem = operatingSystem;
        return this;
    }

    /**
     * The name, unique identifier, and email address of the computer's owner.
     */
    public MonitoredComputer withOwner(MonitoredComputerOwner owner) {
        Utils.checkNotNull(owner, "owner");
        this.owner = Optional.ofNullable(owner);
        return this;
    }


    /**
     * The name, unique identifier, and email address of the computer's owner.
     */
    public MonitoredComputer withOwner(Optional<? extends MonitoredComputerOwner> owner) {
        Utils.checkNotNull(owner, "owner");
        this.owner = owner;
        return this;
    }

    /**
     * The serial number of the computer. This value may be null if it is not reported by the device.
     */
    public MonitoredComputer withSerialNumber(String serialNumber) {
        Utils.checkNotNull(serialNumber, "serialNumber");
        this.serialNumber = Optional.ofNullable(serialNumber);
        return this;
    }


    /**
     * The serial number of the computer. This value may be null if it is not reported by the device.
     */
    public MonitoredComputer withSerialNumber(Optional<String> serialNumber) {
        Utils.checkNotNull(serialNumber, "serialNumber");
        this.serialNumber = serialNumber;
        return this;
    }

    /**
     * The universal device id of the computer.
     */
    public MonitoredComputer withUdid(String udid) {
        Utils.checkNotNull(udid, "udid");
        this.udid = Optional.ofNullable(udid);
        return this;
    }


    /**
     * The universal device id of the computer.
     */
    public MonitoredComputer withUdid(Optional<String> udid) {
        Utils.checkNotNull(udid, "udid");
        this.udid = udid;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        MonitoredComputer other = (MonitoredComputer) o;
        return 
            Utils.enhancedDeepEquals(this.id, other.id) &&
            Utils.enhancedDeepEquals(this.integrationId, other.integrationId) &&
            Utils.enhancedDeepEquals(this.lastCheckDate, other.lastCheckDate) &&
            Utils.enhancedDeepEquals(this.screenlock, other.screenlock) &&
            Utils.enhancedDeepEquals(this.diskEncryption, other.diskEncryption) &&
            Utils.enhancedDeepEquals(this.passwordManager, other.passwordManager) &&
            Utils.enhancedDeepEquals(this.antivirusInstallation, other.antivirusInstallation) &&
            Utils.enhancedDeepEquals(this.operatingSystem, other.operatingSystem) &&
            Utils.enhancedDeepEquals(this.owner, other.owner) &&
            Utils.enhancedDeepEquals(this.serialNumber, other.serialNumber) &&
            Utils.enhancedDeepEquals(this.udid, other.udid);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            id, integrationId, lastCheckDate,
            screenlock, diskEncryption, passwordManager,
            antivirusInstallation, operatingSystem, owner,
            serialNumber, udid);
    }
    
    @Override
    public String toString() {
        return Utils.toString(MonitoredComputer.class,
                "id", id,
                "integrationId", integrationId,
                "lastCheckDate", lastCheckDate,
                "screenlock", screenlock,
                "diskEncryption", diskEncryption,
                "passwordManager", passwordManager,
                "antivirusInstallation", antivirusInstallation,
                "operatingSystem", operatingSystem,
                "owner", owner,
                "serialNumber", serialNumber,
                "udid", udid);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String id;

        private String integrationId;

        private Optional<OffsetDateTime> lastCheckDate = Optional.empty();

        private ComputerStatus screenlock;

        private ComputerStatus diskEncryption;

        private ComputerStatus passwordManager;

        private ComputerStatus antivirusInstallation;

        private Optional<? extends OperatingSystem> operatingSystem = Optional.empty();

        private Optional<? extends MonitoredComputerOwner> owner = Optional.empty();

        private Optional<String> serialNumber = Optional.empty();

        private Optional<String> udid = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * Unique identifier for the monitored computer.
         */
        public Builder id(String id) {
            Utils.checkNotNull(id, "id");
            this.id = id;
            return this;
        }


        /**
         * Hard-coded enums for Vanta-built integrations or application IDs for 3rd-party-built integrations.
         */
        public Builder integrationId(String integrationId) {
            Utils.checkNotNull(integrationId, "integrationId");
            this.integrationId = integrationId;
            return this;
        }


        /**
         * Date of the computer's most recent report.
         */
        public Builder lastCheckDate(OffsetDateTime lastCheckDate) {
            Utils.checkNotNull(lastCheckDate, "lastCheckDate");
            this.lastCheckDate = Optional.ofNullable(lastCheckDate);
            return this;
        }

        /**
         * Date of the computer's most recent report.
         */
        public Builder lastCheckDate(Optional<OffsetDateTime> lastCheckDate) {
            Utils.checkNotNull(lastCheckDate, "lastCheckDate");
            this.lastCheckDate = lastCheckDate;
            return this;
        }


        /**
         * The a status check for a computer. Representation for screenlock, diskEncryption, passwordManager,
         * and antivirusInstallation.
         */
        public Builder screenlock(ComputerStatus screenlock) {
            Utils.checkNotNull(screenlock, "screenlock");
            this.screenlock = screenlock;
            return this;
        }


        /**
         * The a status check for a computer. Representation for screenlock, diskEncryption, passwordManager,
         * and antivirusInstallation.
         */
        public Builder diskEncryption(ComputerStatus diskEncryption) {
            Utils.checkNotNull(diskEncryption, "diskEncryption");
            this.diskEncryption = diskEncryption;
            return this;
        }


        /**
         * The a status check for a computer. Representation for screenlock, diskEncryption, passwordManager,
         * and antivirusInstallation.
         */
        public Builder passwordManager(ComputerStatus passwordManager) {
            Utils.checkNotNull(passwordManager, "passwordManager");
            this.passwordManager = passwordManager;
            return this;
        }


        /**
         * The a status check for a computer. Representation for screenlock, diskEncryption, passwordManager,
         * and antivirusInstallation.
         */
        public Builder antivirusInstallation(ComputerStatus antivirusInstallation) {
            Utils.checkNotNull(antivirusInstallation, "antivirusInstallation");
            this.antivirusInstallation = antivirusInstallation;
            return this;
        }


        /**
         * The computer's operating system name and version.
         */
        public Builder operatingSystem(OperatingSystem operatingSystem) {
            Utils.checkNotNull(operatingSystem, "operatingSystem");
            this.operatingSystem = Optional.ofNullable(operatingSystem);
            return this;
        }

        /**
         * The computer's operating system name and version.
         */
        public Builder operatingSystem(Optional<? extends OperatingSystem> operatingSystem) {
            Utils.checkNotNull(operatingSystem, "operatingSystem");
            this.operatingSystem = operatingSystem;
            return this;
        }


        /**
         * The name, unique identifier, and email address of the computer's owner.
         */
        public Builder owner(MonitoredComputerOwner owner) {
            Utils.checkNotNull(owner, "owner");
            this.owner = Optional.ofNullable(owner);
            return this;
        }

        /**
         * The name, unique identifier, and email address of the computer's owner.
         */
        public Builder owner(Optional<? extends MonitoredComputerOwner> owner) {
            Utils.checkNotNull(owner, "owner");
            this.owner = owner;
            return this;
        }


        /**
         * The serial number of the computer. This value may be null if it is not reported by the device.
         */
        public Builder serialNumber(String serialNumber) {
            Utils.checkNotNull(serialNumber, "serialNumber");
            this.serialNumber = Optional.ofNullable(serialNumber);
            return this;
        }

        /**
         * The serial number of the computer. This value may be null if it is not reported by the device.
         */
        public Builder serialNumber(Optional<String> serialNumber) {
            Utils.checkNotNull(serialNumber, "serialNumber");
            this.serialNumber = serialNumber;
            return this;
        }


        /**
         * The universal device id of the computer.
         */
        public Builder udid(String udid) {
            Utils.checkNotNull(udid, "udid");
            this.udid = Optional.ofNullable(udid);
            return this;
        }

        /**
         * The universal device id of the computer.
         */
        public Builder udid(Optional<String> udid) {
            Utils.checkNotNull(udid, "udid");
            this.udid = udid;
            return this;
        }

        public MonitoredComputer build() {

            return new MonitoredComputer(
                id, integrationId, lastCheckDate,
                screenlock, diskEncryption, passwordManager,
                antivirusInstallation, operatingSystem, owner,
                serialNumber, udid);
        }

    }
}
