/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.vanta.vanta_auditor_api.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.vanta.vanta_auditor_api.utils.Utils;
import java.lang.Override;
import java.lang.String;

/**
 * ObservationEvidence
 * 
 * <p>Evidence in the form of a text observation or note.
 */
public class ObservationEvidence {
    /**
     * The text content of the observation.
     */
    @JsonProperty("observationDetails")
    private String observationDetails;

    @JsonCreator
    public ObservationEvidence(
            @JsonProperty("observationDetails") String observationDetails) {
        Utils.checkNotNull(observationDetails, "observationDetails");
        this.observationDetails = observationDetails;
    }

    /**
     * The text content of the observation.
     */
    @JsonIgnore
    public String observationDetails() {
        return observationDetails;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The text content of the observation.
     */
    public ObservationEvidence withObservationDetails(String observationDetails) {
        Utils.checkNotNull(observationDetails, "observationDetails");
        this.observationDetails = observationDetails;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ObservationEvidence other = (ObservationEvidence) o;
        return 
            Utils.enhancedDeepEquals(this.observationDetails, other.observationDetails);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            observationDetails);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ObservationEvidence.class,
                "observationDetails", observationDetails);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String observationDetails;

        private Builder() {
          // force use of static builder() method
        }


        /**
         * The text content of the observation.
         */
        public Builder observationDetails(String observationDetails) {
            Utils.checkNotNull(observationDetails, "observationDetails");
            this.observationDetails = observationDetails;
            return this;
        }

        public ObservationEvidence build() {

            return new ObservationEvidence(
                observationDetails);
        }

    }
}
