/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.vanta.vanta_auditor_api.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.vanta.vanta_auditor_api.utils.Utils;
import java.lang.Override;
import java.lang.String;


public class One {

    @JsonProperty("displayName")
    private String displayName;


    @JsonProperty("id")
    private String id;


    @JsonProperty("type")
    private InformationRequestOwnerAssignmentType type;

    @JsonCreator
    public One(
            @JsonProperty("displayName") String displayName,
            @JsonProperty("id") String id,
            @JsonProperty("type") InformationRequestOwnerAssignmentType type) {
        Utils.checkNotNull(displayName, "displayName");
        Utils.checkNotNull(id, "id");
        Utils.checkNotNull(type, "type");
        this.displayName = displayName;
        this.id = id;
        this.type = type;
    }

    @JsonIgnore
    public String displayName() {
        return displayName;
    }

    @JsonIgnore
    public String id() {
        return id;
    }

    @JsonIgnore
    public InformationRequestOwnerAssignmentType type() {
        return type;
    }

    public static Builder builder() {
        return new Builder();
    }


    public One withDisplayName(String displayName) {
        Utils.checkNotNull(displayName, "displayName");
        this.displayName = displayName;
        return this;
    }

    public One withId(String id) {
        Utils.checkNotNull(id, "id");
        this.id = id;
        return this;
    }

    public One withType(InformationRequestOwnerAssignmentType type) {
        Utils.checkNotNull(type, "type");
        this.type = type;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        One other = (One) o;
        return 
            Utils.enhancedDeepEquals(this.displayName, other.displayName) &&
            Utils.enhancedDeepEquals(this.id, other.id) &&
            Utils.enhancedDeepEquals(this.type, other.type);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            displayName, id, type);
    }
    
    @Override
    public String toString() {
        return Utils.toString(One.class,
                "displayName", displayName,
                "id", id,
                "type", type);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String displayName;

        private String id;

        private InformationRequestOwnerAssignmentType type;

        private Builder() {
          // force use of static builder() method
        }


        public Builder displayName(String displayName) {
            Utils.checkNotNull(displayName, "displayName");
            this.displayName = displayName;
            return this;
        }


        public Builder id(String id) {
            Utils.checkNotNull(id, "id");
            this.id = id;
            return this;
        }


        public Builder type(InformationRequestOwnerAssignmentType type) {
            Utils.checkNotNull(type, "type");
            this.type = type;
            return this;
        }

        public One build() {

            return new One(
                displayName, id, type);
        }

    }
}
