/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.vanta.vanta_auditor_api.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * OperatingSystemType
 * 
 * <p>The possible types of the operating system. One of `mac_OS`, `linux`, or `windows`.
 */
public enum OperatingSystemType {
    MAC_OS("macOS"),
    LINUX("linux"),
    WINDOWS("windows");

    @JsonValue
    private final String value;

    OperatingSystemType(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<OperatingSystemType> fromValue(String value) {
        for (OperatingSystemType o: OperatingSystemType.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

