/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.vanta.vanta_auditor_api.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.vanta.vanta_auditor_api.utils.Utils;
import java.lang.Override;
import java.lang.String;


public class PaginatedResponsePersonnelGroup {

    @JsonProperty("results")
    private PaginatedResponsePersonnelGroupResults results;

    @JsonCreator
    public PaginatedResponsePersonnelGroup(
            @JsonProperty("results") PaginatedResponsePersonnelGroupResults results) {
        Utils.checkNotNull(results, "results");
        this.results = results;
    }

    @JsonIgnore
    public PaginatedResponsePersonnelGroupResults results() {
        return results;
    }

    public static Builder builder() {
        return new Builder();
    }


    public PaginatedResponsePersonnelGroup withResults(PaginatedResponsePersonnelGroupResults results) {
        Utils.checkNotNull(results, "results");
        this.results = results;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PaginatedResponsePersonnelGroup other = (PaginatedResponsePersonnelGroup) o;
        return 
            Utils.enhancedDeepEquals(this.results, other.results);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            results);
    }
    
    @Override
    public String toString() {
        return Utils.toString(PaginatedResponsePersonnelGroup.class,
                "results", results);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private PaginatedResponsePersonnelGroupResults results;

        private Builder() {
          // force use of static builder() method
        }


        public Builder results(PaginatedResponsePersonnelGroupResults results) {
            Utils.checkNotNull(results, "results");
            this.results = results;
            return this;
        }

        public PaginatedResponsePersonnelGroup build() {

            return new PaginatedResponsePersonnelGroup(
                results);
        }

    }
}
