/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.vanta.vanta_auditor_api.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.vanta.vanta_auditor_api.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.util.List;


public class PaginatedResponseCodeChangeResults {

    @JsonProperty("data")
    private List<CodeChange> data;

    /**
     * Provides information about the pagination of a dataset.
     */
    @JsonProperty("pageInfo")
    private PageInfo pageInfo;

    @JsonCreator
    public PaginatedResponseCodeChangeResults(
            @JsonProperty("data") List<CodeChange> data,
            @JsonProperty("pageInfo") PageInfo pageInfo) {
        Utils.checkNotNull(data, "data");
        Utils.checkNotNull(pageInfo, "pageInfo");
        this.data = data;
        this.pageInfo = pageInfo;
    }

    @JsonIgnore
    public List<CodeChange> data() {
        return data;
    }

    /**
     * Provides information about the pagination of a dataset.
     */
    @JsonIgnore
    public PageInfo pageInfo() {
        return pageInfo;
    }

    public static Builder builder() {
        return new Builder();
    }


    public PaginatedResponseCodeChangeResults withData(List<CodeChange> data) {
        Utils.checkNotNull(data, "data");
        this.data = data;
        return this;
    }

    /**
     * Provides information about the pagination of a dataset.
     */
    public PaginatedResponseCodeChangeResults withPageInfo(PageInfo pageInfo) {
        Utils.checkNotNull(pageInfo, "pageInfo");
        this.pageInfo = pageInfo;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PaginatedResponseCodeChangeResults other = (PaginatedResponseCodeChangeResults) o;
        return 
            Utils.enhancedDeepEquals(this.data, other.data) &&
            Utils.enhancedDeepEquals(this.pageInfo, other.pageInfo);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            data, pageInfo);
    }
    
    @Override
    public String toString() {
        return Utils.toString(PaginatedResponseCodeChangeResults.class,
                "data", data,
                "pageInfo", pageInfo);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private List<CodeChange> data;

        private PageInfo pageInfo;

        private Builder() {
          // force use of static builder() method
        }


        public Builder data(List<CodeChange> data) {
            Utils.checkNotNull(data, "data");
            this.data = data;
            return this;
        }


        /**
         * Provides information about the pagination of a dataset.
         */
        public Builder pageInfo(PageInfo pageInfo) {
            Utils.checkNotNull(pageInfo, "pageInfo");
            this.pageInfo = pageInfo;
            return this;
        }

        public PaginatedResponseCodeChangeResults build() {

            return new PaginatedResponseCodeChangeResults(
                data, pageInfo);
        }

    }
}
