/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.vanta.vanta_auditor_api.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

public enum PeopleOrderBy {
    NAME("name"),
    EMPLOYMENT_STATUS("employmentStatus");

    @JsonValue
    private final String value;

    PeopleOrderBy(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<PeopleOrderBy> fromValue(String value) {
        for (PeopleOrderBy o: PeopleOrderBy.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

