/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.vanta.vanta_auditor_api.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * PeopleEmploymentStatus
 * 
 * <p>Employment status filter for people queries.
 */
public enum PeopleEmploymentStatus {
    CURRENTLY_EMPLOYED("CURRENTLY_EMPLOYED"),
    INACTIVE_EMPLOYEE("INACTIVE_EMPLOYEE"),
    NOT_PEOPLE("NOT_PEOPLE"),
    ON_LEAVE("ON_LEAVE"),
    PREVIOUSLY_EMPLOYED("PREVIOUSLY_EMPLOYED"),
    UPCOMING_EMPLOYEE("UPCOMING_EMPLOYEE");

    @JsonValue
    private final String value;

    PeopleEmploymentStatus(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<PeopleEmploymentStatus> fromValue(String value) {
        for (PeopleEmploymentStatus o: PeopleEmploymentStatus.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

