/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.vanta.vanta_auditor_api.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.vanta.vanta_auditor_api.utils.OneOfDeserializer;
import com.vanta.vanta_auditor_api.utils.TypedObject;
import com.vanta.vanta_auditor_api.utils.Utils.JsonShape;
import com.vanta.vanta_auditor_api.utils.Utils.TypeReferenceWithShape;
import com.vanta.vanta_auditor_api.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;

/**
 * PersonInfoSource
 * 
 * <p>The source of the person's information.
 */
@JsonDeserialize(using = PersonInfoSource._Deserializer.class)
public class PersonInfoSource {

    @JsonValue
    private final TypedObject value;
    
    private PersonInfoSource(TypedObject value) {
        this.value = value;
    }

    public static PersonInfoSource of(VantaBasedPersonInfoSource value) {
        Utils.checkNotNull(value, "value");
        return new PersonInfoSource(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>(){}));
    }

    public static PersonInfoSource of(ScimBasedPersonInfoSource value) {
        Utils.checkNotNull(value, "value");
        return new PersonInfoSource(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>(){}));
    }

    public static PersonInfoSource of(IntegrationBasedPersonInfoSource value) {
        Utils.checkNotNull(value, "value");
        return new PersonInfoSource(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<>(){}));
    }
    
    /**
     * Returns an instance of one of these types:
     * <ul>
     * <li>{@code com.vanta.vanta_auditor_api.models.components.VantaBasedPersonInfoSource}</li>
     * <li>{@code com.vanta.vanta_auditor_api.models.components.ScimBasedPersonInfoSource}</li>
     * <li>{@code com.vanta.vanta_auditor_api.models.components.IntegrationBasedPersonInfoSource}</li>
     * </ul>
     * 
     * <p>Use {@code instanceof} to determine what type is returned. For example:
     * 
     * <pre>
     * if (obj.value() instanceof String) {
     *     String answer = (String) obj.value();
     *     System.out.println("answer=" + answer);
     * }
     * </pre>
     * 
     * @return value of oneOf type
     **/ 
    public java.lang.Object value() {
        return value.value();
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PersonInfoSource other = (PersonInfoSource) o;
        return Utils.enhancedDeepEquals(this.value.value(), other.value.value());
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(value.value());
    }
    
    @SuppressWarnings("serial")
    public static final class _Deserializer extends OneOfDeserializer<PersonInfoSource> {

        public _Deserializer() {
            super(PersonInfoSource.class, false,
                  TypeReferenceWithShape.of(new TypeReference<VantaBasedPersonInfoSource>() {}, JsonShape.DEFAULT),
                  TypeReferenceWithShape.of(new TypeReference<ScimBasedPersonInfoSource>() {}, JsonShape.DEFAULT),
                  TypeReferenceWithShape.of(new TypeReference<IntegrationBasedPersonInfoSource>() {}, JsonShape.DEFAULT));
        }
    }
    
    @Override
    public String toString() {
        return Utils.toString(PersonInfoSource.class,
                "value", value);
    }

}

