/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.vanta.vanta_auditor_api.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.vanta.vanta_auditor_api.utils.Utils;
import java.lang.Override;
import java.lang.String;


public class PersonEmployment {
    /**
     * The source of the person's information.
     */
    @JsonProperty("endDate")
    private PersonInfoSource endDate;

    /**
     * The source of the person's information.
     */
    @JsonProperty("startDate")
    private PersonInfoSource startDate;

    @JsonCreator
    public PersonEmployment(
            @JsonProperty("endDate") PersonInfoSource endDate,
            @JsonProperty("startDate") PersonInfoSource startDate) {
        Utils.checkNotNull(endDate, "endDate");
        Utils.checkNotNull(startDate, "startDate");
        this.endDate = endDate;
        this.startDate = startDate;
    }

    /**
     * The source of the person's information.
     */
    @JsonIgnore
    public PersonInfoSource endDate() {
        return endDate;
    }

    /**
     * The source of the person's information.
     */
    @JsonIgnore
    public PersonInfoSource startDate() {
        return startDate;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The source of the person's information.
     */
    public PersonEmployment withEndDate(PersonInfoSource endDate) {
        Utils.checkNotNull(endDate, "endDate");
        this.endDate = endDate;
        return this;
    }

    /**
     * The source of the person's information.
     */
    public PersonEmployment withStartDate(PersonInfoSource startDate) {
        Utils.checkNotNull(startDate, "startDate");
        this.startDate = startDate;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PersonEmployment other = (PersonEmployment) o;
        return 
            Utils.enhancedDeepEquals(this.endDate, other.endDate) &&
            Utils.enhancedDeepEquals(this.startDate, other.startDate);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            endDate, startDate);
    }
    
    @Override
    public String toString() {
        return Utils.toString(PersonEmployment.class,
                "endDate", endDate,
                "startDate", startDate);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private PersonInfoSource endDate;

        private PersonInfoSource startDate;

        private Builder() {
          // force use of static builder() method
        }


        /**
         * The source of the person's information.
         */
        public Builder endDate(PersonInfoSource endDate) {
            Utils.checkNotNull(endDate, "endDate");
            this.endDate = endDate;
            return this;
        }


        /**
         * The source of the person's information.
         */
        public Builder startDate(PersonInfoSource startDate) {
            Utils.checkNotNull(startDate, "startDate");
            this.startDate = startDate;
            return this;
        }

        public PersonEmployment build() {

            return new PersonEmployment(
                endDate, startDate);
        }

    }
}
