/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.vanta.vanta_auditor_api.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

public enum RecurrenceDuration {
    P0_D("P0D"),
    P1_D("P1D"),
    P1_W("P1W"),
    P1_M("P1M"),
    P3_M("P3M"),
    P6_M("P6M"),
    P1_Y("P1Y");

    @JsonValue
    private final String value;

    private RecurrenceDuration(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<RecurrenceDuration> fromValue(String value) {
        for (RecurrenceDuration o: RecurrenceDuration.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

