/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.vanta.vanta_auditor_api.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * TaskStatus
 * 
 * <p>The status of a task.
 * - COMPLETE: The task has been completed.
 * - DUE_SOON: The task is due soon.
 * - OVERDUE: The task is overdue.
 * - NONE: The task is not assigned.
 */
public enum TaskStatus {
    COMPLETE("COMPLETE"),
    DUE_SOON("DUE_SOON"),
    OVERDUE("OVERDUE"),
    NONE("NONE");

    @JsonValue
    private final String value;

    TaskStatus(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<TaskStatus> fromValue(String value) {
        for (TaskStatus o: TaskStatus.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

