/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.vanta.vanta_auditor_api.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

public enum TaskTypeCOMPLETETRAININGS {
    COMPLETE_TRAININGS("COMPLETE_TRAININGS");

    @JsonValue
    private final String value;

    TaskTypeCOMPLETETRAININGS(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<TaskTypeCOMPLETETRAININGS> fromValue(String value) {
        for (TaskTypeCOMPLETETRAININGS o: TaskTypeCOMPLETETRAININGS.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

