/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.vanta.vanta_auditor_api.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

public enum TaskTypeCOMPLETECUSTOMOFFBOARDINGTASKS {
    COMPLETE_CUSTOM_OFFBOARDING_TASKS("COMPLETE_CUSTOM_OFFBOARDING_TASKS");

    @JsonValue
    private final String value;

    TaskTypeCOMPLETECUSTOMOFFBOARDINGTASKS(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<TaskTypeCOMPLETECUSTOMOFFBOARDINGTASKS> fromValue(String value) {
        for (TaskTypeCOMPLETECUSTOMOFFBOARDINGTASKS o: TaskTypeCOMPLETECUSTOMOFFBOARDINGTASKS.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

