/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.vanta.vanta_auditor_api.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.vanta.vanta_auditor_api.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.time.OffsetDateTime;

/**
 * VantaTestEvidence
 * 
 * <p>Evidence in the form of a Vanta automated test run.
 * Vanta Tests are automated compliance tests with metadata like test status,
 * execution time, and file type. Tests generate evidence files that can be
 * workpapers, raw data, or API request logs.
 */
public class VantaTestEvidence {
    /**
     * The title of the test run as displayed in Vanta.
     */
    @JsonProperty("title")
    private String title;

    /**
     * The unique identifier for the test in Vanta's system.
     */
    @JsonProperty("testId")
    private String testId;

    /**
     * The unique identifier for the point-in-time capture of this test run's evidence.
     * A snapshot is an immutable record of all files (workpapers, raw data, etc.)
     * generated during a single test execution.
     */
    @JsonProperty("snapshotId")
    private String snapshotId;


    @JsonProperty("testRunStatus")
    private VantaTestRunStatus testRunStatus;

    /**
     * The date and time when the test was executed.
     * Format: ISO 8601 UTC timestamp.
     */
    @JsonProperty("executedAt")
    private OffsetDateTime executedAt;


    @JsonProperty("fileType")
    private VantaTestFileType fileType;

    /**
     * The evidence file for this test run.
     */
    @JsonProperty("file")
    private VantaTestEvidenceFile file;

    @JsonCreator
    public VantaTestEvidence(
            @JsonProperty("title") String title,
            @JsonProperty("testId") String testId,
            @JsonProperty("snapshotId") String snapshotId,
            @JsonProperty("testRunStatus") VantaTestRunStatus testRunStatus,
            @JsonProperty("executedAt") OffsetDateTime executedAt,
            @JsonProperty("fileType") VantaTestFileType fileType,
            @JsonProperty("file") VantaTestEvidenceFile file) {
        Utils.checkNotNull(title, "title");
        Utils.checkNotNull(testId, "testId");
        Utils.checkNotNull(snapshotId, "snapshotId");
        Utils.checkNotNull(testRunStatus, "testRunStatus");
        Utils.checkNotNull(executedAt, "executedAt");
        Utils.checkNotNull(fileType, "fileType");
        Utils.checkNotNull(file, "file");
        this.title = title;
        this.testId = testId;
        this.snapshotId = snapshotId;
        this.testRunStatus = testRunStatus;
        this.executedAt = executedAt;
        this.fileType = fileType;
        this.file = file;
    }

    /**
     * The title of the test run as displayed in Vanta.
     */
    @JsonIgnore
    public String title() {
        return title;
    }

    /**
     * The unique identifier for the test in Vanta's system.
     */
    @JsonIgnore
    public String testId() {
        return testId;
    }

    /**
     * The unique identifier for the point-in-time capture of this test run's evidence.
     * A snapshot is an immutable record of all files (workpapers, raw data, etc.)
     * generated during a single test execution.
     */
    @JsonIgnore
    public String snapshotId() {
        return snapshotId;
    }

    @JsonIgnore
    public VantaTestRunStatus testRunStatus() {
        return testRunStatus;
    }

    /**
     * The date and time when the test was executed.
     * Format: ISO 8601 UTC timestamp.
     */
    @JsonIgnore
    public OffsetDateTime executedAt() {
        return executedAt;
    }

    @JsonIgnore
    public VantaTestFileType fileType() {
        return fileType;
    }

    /**
     * The evidence file for this test run.
     */
    @JsonIgnore
    public VantaTestEvidenceFile file() {
        return file;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The title of the test run as displayed in Vanta.
     */
    public VantaTestEvidence withTitle(String title) {
        Utils.checkNotNull(title, "title");
        this.title = title;
        return this;
    }

    /**
     * The unique identifier for the test in Vanta's system.
     */
    public VantaTestEvidence withTestId(String testId) {
        Utils.checkNotNull(testId, "testId");
        this.testId = testId;
        return this;
    }

    /**
     * The unique identifier for the point-in-time capture of this test run's evidence.
     * A snapshot is an immutable record of all files (workpapers, raw data, etc.)
     * generated during a single test execution.
     */
    public VantaTestEvidence withSnapshotId(String snapshotId) {
        Utils.checkNotNull(snapshotId, "snapshotId");
        this.snapshotId = snapshotId;
        return this;
    }

    public VantaTestEvidence withTestRunStatus(VantaTestRunStatus testRunStatus) {
        Utils.checkNotNull(testRunStatus, "testRunStatus");
        this.testRunStatus = testRunStatus;
        return this;
    }

    /**
     * The date and time when the test was executed.
     * Format: ISO 8601 UTC timestamp.
     */
    public VantaTestEvidence withExecutedAt(OffsetDateTime executedAt) {
        Utils.checkNotNull(executedAt, "executedAt");
        this.executedAt = executedAt;
        return this;
    }

    public VantaTestEvidence withFileType(VantaTestFileType fileType) {
        Utils.checkNotNull(fileType, "fileType");
        this.fileType = fileType;
        return this;
    }

    /**
     * The evidence file for this test run.
     */
    public VantaTestEvidence withFile(VantaTestEvidenceFile file) {
        Utils.checkNotNull(file, "file");
        this.file = file;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        VantaTestEvidence other = (VantaTestEvidence) o;
        return 
            Utils.enhancedDeepEquals(this.title, other.title) &&
            Utils.enhancedDeepEquals(this.testId, other.testId) &&
            Utils.enhancedDeepEquals(this.snapshotId, other.snapshotId) &&
            Utils.enhancedDeepEquals(this.testRunStatus, other.testRunStatus) &&
            Utils.enhancedDeepEquals(this.executedAt, other.executedAt) &&
            Utils.enhancedDeepEquals(this.fileType, other.fileType) &&
            Utils.enhancedDeepEquals(this.file, other.file);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            title, testId, snapshotId,
            testRunStatus, executedAt, fileType,
            file);
    }
    
    @Override
    public String toString() {
        return Utils.toString(VantaTestEvidence.class,
                "title", title,
                "testId", testId,
                "snapshotId", snapshotId,
                "testRunStatus", testRunStatus,
                "executedAt", executedAt,
                "fileType", fileType,
                "file", file);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String title;

        private String testId;

        private String snapshotId;

        private VantaTestRunStatus testRunStatus;

        private OffsetDateTime executedAt;

        private VantaTestFileType fileType;

        private VantaTestEvidenceFile file;

        private Builder() {
          // force use of static builder() method
        }


        /**
         * The title of the test run as displayed in Vanta.
         */
        public Builder title(String title) {
            Utils.checkNotNull(title, "title");
            this.title = title;
            return this;
        }


        /**
         * The unique identifier for the test in Vanta's system.
         */
        public Builder testId(String testId) {
            Utils.checkNotNull(testId, "testId");
            this.testId = testId;
            return this;
        }


        /**
         * The unique identifier for the point-in-time capture of this test run's evidence.
         * A snapshot is an immutable record of all files (workpapers, raw data, etc.)
         * generated during a single test execution.
         */
        public Builder snapshotId(String snapshotId) {
            Utils.checkNotNull(snapshotId, "snapshotId");
            this.snapshotId = snapshotId;
            return this;
        }


        public Builder testRunStatus(VantaTestRunStatus testRunStatus) {
            Utils.checkNotNull(testRunStatus, "testRunStatus");
            this.testRunStatus = testRunStatus;
            return this;
        }


        /**
         * The date and time when the test was executed.
         * Format: ISO 8601 UTC timestamp.
         */
        public Builder executedAt(OffsetDateTime executedAt) {
            Utils.checkNotNull(executedAt, "executedAt");
            this.executedAt = executedAt;
            return this;
        }


        public Builder fileType(VantaTestFileType fileType) {
            Utils.checkNotNull(fileType, "fileType");
            this.fileType = fileType;
            return this;
        }


        /**
         * The evidence file for this test run.
         */
        public Builder file(VantaTestEvidenceFile file) {
            Utils.checkNotNull(file, "file");
            this.file = file;
            return this;
        }

        public VantaTestEvidence build() {

            return new VantaTestEvidence(
                title, testId, snapshotId,
                testRunStatus, executedAt, fileType,
                file);
        }

    }
}
