/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.vanta.vanta_auditor_api.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.vanta.vanta_auditor_api.utils.Utils;
import java.lang.Override;
import java.lang.String;

/**
 * VantaDocumentLinkEvidence
 * 
 * <p>Represents an external link in a Vanta Document.
 * The link points to documentation hosted outside of Vanta's system.
 */
public class VantaDocumentLinkEvidence {
    /**
     * Discriminator to identify this as an external link.
     */
    @JsonProperty("type")
    private VantaDocumentLinkEvidenceType type;

    /**
     * The unique identifier for the file version in Vanta's system.
     */
    @JsonProperty("id")
    private String id;

    /**
     * The URL pointing to the external documentation or resource.
     */
    @JsonProperty("url")
    private String url;

    @JsonCreator
    public VantaDocumentLinkEvidence(
            @JsonProperty("type") VantaDocumentLinkEvidenceType type,
            @JsonProperty("id") String id,
            @JsonProperty("url") String url) {
        Utils.checkNotNull(type, "type");
        Utils.checkNotNull(id, "id");
        Utils.checkNotNull(url, "url");
        this.type = type;
        this.id = id;
        this.url = url;
    }

    /**
     * Discriminator to identify this as an external link.
     */
    @JsonIgnore
    public VantaDocumentLinkEvidenceType type() {
        return type;
    }

    /**
     * The unique identifier for the file version in Vanta's system.
     */
    @JsonIgnore
    public String id() {
        return id;
    }

    /**
     * The URL pointing to the external documentation or resource.
     */
    @JsonIgnore
    public String url() {
        return url;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Discriminator to identify this as an external link.
     */
    public VantaDocumentLinkEvidence withType(VantaDocumentLinkEvidenceType type) {
        Utils.checkNotNull(type, "type");
        this.type = type;
        return this;
    }

    /**
     * The unique identifier for the file version in Vanta's system.
     */
    public VantaDocumentLinkEvidence withId(String id) {
        Utils.checkNotNull(id, "id");
        this.id = id;
        return this;
    }

    /**
     * The URL pointing to the external documentation or resource.
     */
    public VantaDocumentLinkEvidence withUrl(String url) {
        Utils.checkNotNull(url, "url");
        this.url = url;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        VantaDocumentLinkEvidence other = (VantaDocumentLinkEvidence) o;
        return 
            Utils.enhancedDeepEquals(this.type, other.type) &&
            Utils.enhancedDeepEquals(this.id, other.id) &&
            Utils.enhancedDeepEquals(this.url, other.url);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            type, id, url);
    }
    
    @Override
    public String toString() {
        return Utils.toString(VantaDocumentLinkEvidence.class,
                "type", type,
                "id", id,
                "url", url);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private VantaDocumentLinkEvidenceType type;

        private String id;

        private String url;

        private Builder() {
          // force use of static builder() method
        }


        /**
         * Discriminator to identify this as an external link.
         */
        public Builder type(VantaDocumentLinkEvidenceType type) {
            Utils.checkNotNull(type, "type");
            this.type = type;
            return this;
        }


        /**
         * The unique identifier for the file version in Vanta's system.
         */
        public Builder id(String id) {
            Utils.checkNotNull(id, "id");
            this.id = id;
            return this;
        }


        /**
         * The URL pointing to the external documentation or resource.
         */
        public Builder url(String url) {
            Utils.checkNotNull(url, "url");
            this.url = url;
            return this;
        }

        public VantaDocumentLinkEvidence build() {

            return new VantaDocumentLinkEvidence(
                type, id, url);
        }

    }
}
