/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.vanta.vanta_auditor_api.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.vanta.vanta_auditor_api.utils.Utils;
import java.lang.Override;
import java.lang.String;

/**
 * VantaBasedPersonInfoSource
 * 
 * <p>The person's information comes from what is set in Vanta.
 */
public class VantaBasedPersonInfoSource {

    @JsonProperty("type")
    private PersonInfoSourceTypeVANTA type;

    @JsonCreator
    public VantaBasedPersonInfoSource(
            @JsonProperty("type") PersonInfoSourceTypeVANTA type) {
        Utils.checkNotNull(type, "type");
        this.type = type;
    }

    @JsonIgnore
    public PersonInfoSourceTypeVANTA type() {
        return type;
    }

    public static Builder builder() {
        return new Builder();
    }


    public VantaBasedPersonInfoSource withType(PersonInfoSourceTypeVANTA type) {
        Utils.checkNotNull(type, "type");
        this.type = type;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        VantaBasedPersonInfoSource other = (VantaBasedPersonInfoSource) o;
        return 
            Utils.enhancedDeepEquals(this.type, other.type);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            type);
    }
    
    @Override
    public String toString() {
        return Utils.toString(VantaBasedPersonInfoSource.class,
                "type", type);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private PersonInfoSourceTypeVANTA type;

        private Builder() {
          // force use of static builder() method
        }


        public Builder type(PersonInfoSourceTypeVANTA type) {
            Utils.checkNotNull(type, "type");
            this.type = type;
            return this;
        }

        public VantaBasedPersonInfoSource build() {

            return new VantaBasedPersonInfoSource(
                type);
        }

    }
}
