/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.vanta.vanta_auditor_api.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.vanta.vanta_auditor_api.utils.Utils;
import java.lang.Override;
import java.lang.String;

/**
 * VantaTestSnapshotIntegration
 * 
 * <p>Integration metadata for a test, mirroring the Vanta web app.
 */
public class VantaTestSnapshotIntegration {

    @JsonProperty("integrationId")
    private String integrationId;


    @JsonProperty("displayName")
    private String displayName;

    @JsonCreator
    public VantaTestSnapshotIntegration(
            @JsonProperty("integrationId") String integrationId,
            @JsonProperty("displayName") String displayName) {
        Utils.checkNotNull(integrationId, "integrationId");
        Utils.checkNotNull(displayName, "displayName");
        this.integrationId = integrationId;
        this.displayName = displayName;
    }

    @JsonIgnore
    public String integrationId() {
        return integrationId;
    }

    @JsonIgnore
    public String displayName() {
        return displayName;
    }

    public static Builder builder() {
        return new Builder();
    }


    public VantaTestSnapshotIntegration withIntegrationId(String integrationId) {
        Utils.checkNotNull(integrationId, "integrationId");
        this.integrationId = integrationId;
        return this;
    }

    public VantaTestSnapshotIntegration withDisplayName(String displayName) {
        Utils.checkNotNull(displayName, "displayName");
        this.displayName = displayName;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        VantaTestSnapshotIntegration other = (VantaTestSnapshotIntegration) o;
        return 
            Utils.enhancedDeepEquals(this.integrationId, other.integrationId) &&
            Utils.enhancedDeepEquals(this.displayName, other.displayName);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            integrationId, displayName);
    }
    
    @Override
    public String toString() {
        return Utils.toString(VantaTestSnapshotIntegration.class,
                "integrationId", integrationId,
                "displayName", displayName);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String integrationId;

        private String displayName;

        private Builder() {
          // force use of static builder() method
        }


        public Builder integrationId(String integrationId) {
            Utils.checkNotNull(integrationId, "integrationId");
            this.integrationId = integrationId;
            return this;
        }


        public Builder displayName(String displayName) {
            Utils.checkNotNull(displayName, "displayName");
            this.displayName = displayName;
            return this;
        }

        public VantaTestSnapshotIntegration build() {

            return new VantaTestSnapshotIntegration(
                integrationId, displayName);
        }

    }
}
