/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.vanta.vanta_auditor_api.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.vanta.vanta_auditor_api.utils.Utils;
import java.lang.Boolean;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;


public class VulnerableAsset {
    /**
     * Unique identifier for the vulnerable asset.
     */
    @JsonProperty("id")
    private String id;

    /**
     * Display name of the vulnerable asset.
     */
    @JsonProperty("name")
    private String name;

    /**
     * VulnerableAssetType describes the types of assets a vulnerability is on.
     */
    @JsonProperty("assetType")
    private VulnerableAssetType assetType;

    /**
     * Whether the vulnerable asset has been scanned.
     */
    @JsonProperty("hasBeenScanned")
    private boolean hasBeenScanned;

    /**
     * Only relevant for container repositories. This field sets the container image tag that
     * vulnerabilities will be retrieved for. If null, the latest image will be retrieved.
     */
    @JsonInclude(Include.ALWAYS)
    @JsonProperty("imageScanTag")
    private Optional<String> imageScanTag;

    /**
     * The integrations that are scanning this vulnerable asset.
     */
    @JsonProperty("scanners")
    private List<VulnerableAssetScanner> scanners;

    @JsonCreator
    public VulnerableAsset(
            @JsonProperty("id") String id,
            @JsonProperty("name") String name,
            @JsonProperty("assetType") VulnerableAssetType assetType,
            @JsonProperty("hasBeenScanned") boolean hasBeenScanned,
            @JsonProperty("imageScanTag") Optional<String> imageScanTag,
            @JsonProperty("scanners") List<VulnerableAssetScanner> scanners) {
        Utils.checkNotNull(id, "id");
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(assetType, "assetType");
        Utils.checkNotNull(hasBeenScanned, "hasBeenScanned");
        Utils.checkNotNull(imageScanTag, "imageScanTag");
        Utils.checkNotNull(scanners, "scanners");
        this.id = id;
        this.name = name;
        this.assetType = assetType;
        this.hasBeenScanned = hasBeenScanned;
        this.imageScanTag = imageScanTag;
        this.scanners = scanners;
    }
    
    public VulnerableAsset(
            String id,
            String name,
            VulnerableAssetType assetType,
            boolean hasBeenScanned,
            List<VulnerableAssetScanner> scanners) {
        this(id, name, assetType,
            hasBeenScanned, Optional.empty(), scanners);
    }

    /**
     * Unique identifier for the vulnerable asset.
     */
    @JsonIgnore
    public String id() {
        return id;
    }

    /**
     * Display name of the vulnerable asset.
     */
    @JsonIgnore
    public String name() {
        return name;
    }

    /**
     * VulnerableAssetType describes the types of assets a vulnerability is on.
     */
    @JsonIgnore
    public VulnerableAssetType assetType() {
        return assetType;
    }

    /**
     * Whether the vulnerable asset has been scanned.
     */
    @JsonIgnore
    public boolean hasBeenScanned() {
        return hasBeenScanned;
    }

    /**
     * Only relevant for container repositories. This field sets the container image tag that
     * vulnerabilities will be retrieved for. If null, the latest image will be retrieved.
     */
    @JsonIgnore
    public Optional<String> imageScanTag() {
        return imageScanTag;
    }

    /**
     * The integrations that are scanning this vulnerable asset.
     */
    @JsonIgnore
    public List<VulnerableAssetScanner> scanners() {
        return scanners;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Unique identifier for the vulnerable asset.
     */
    public VulnerableAsset withId(String id) {
        Utils.checkNotNull(id, "id");
        this.id = id;
        return this;
    }

    /**
     * Display name of the vulnerable asset.
     */
    public VulnerableAsset withName(String name) {
        Utils.checkNotNull(name, "name");
        this.name = name;
        return this;
    }

    /**
     * VulnerableAssetType describes the types of assets a vulnerability is on.
     */
    public VulnerableAsset withAssetType(VulnerableAssetType assetType) {
        Utils.checkNotNull(assetType, "assetType");
        this.assetType = assetType;
        return this;
    }

    /**
     * Whether the vulnerable asset has been scanned.
     */
    public VulnerableAsset withHasBeenScanned(boolean hasBeenScanned) {
        Utils.checkNotNull(hasBeenScanned, "hasBeenScanned");
        this.hasBeenScanned = hasBeenScanned;
        return this;
    }

    /**
     * Only relevant for container repositories. This field sets the container image tag that
     * vulnerabilities will be retrieved for. If null, the latest image will be retrieved.
     */
    public VulnerableAsset withImageScanTag(String imageScanTag) {
        Utils.checkNotNull(imageScanTag, "imageScanTag");
        this.imageScanTag = Optional.ofNullable(imageScanTag);
        return this;
    }


    /**
     * Only relevant for container repositories. This field sets the container image tag that
     * vulnerabilities will be retrieved for. If null, the latest image will be retrieved.
     */
    public VulnerableAsset withImageScanTag(Optional<String> imageScanTag) {
        Utils.checkNotNull(imageScanTag, "imageScanTag");
        this.imageScanTag = imageScanTag;
        return this;
    }

    /**
     * The integrations that are scanning this vulnerable asset.
     */
    public VulnerableAsset withScanners(List<VulnerableAssetScanner> scanners) {
        Utils.checkNotNull(scanners, "scanners");
        this.scanners = scanners;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        VulnerableAsset other = (VulnerableAsset) o;
        return 
            Utils.enhancedDeepEquals(this.id, other.id) &&
            Utils.enhancedDeepEquals(this.name, other.name) &&
            Utils.enhancedDeepEquals(this.assetType, other.assetType) &&
            Utils.enhancedDeepEquals(this.hasBeenScanned, other.hasBeenScanned) &&
            Utils.enhancedDeepEquals(this.imageScanTag, other.imageScanTag) &&
            Utils.enhancedDeepEquals(this.scanners, other.scanners);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            id, name, assetType,
            hasBeenScanned, imageScanTag, scanners);
    }
    
    @Override
    public String toString() {
        return Utils.toString(VulnerableAsset.class,
                "id", id,
                "name", name,
                "assetType", assetType,
                "hasBeenScanned", hasBeenScanned,
                "imageScanTag", imageScanTag,
                "scanners", scanners);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String id;

        private String name;

        private VulnerableAssetType assetType;

        private Boolean hasBeenScanned;

        private Optional<String> imageScanTag = Optional.empty();

        private List<VulnerableAssetScanner> scanners;

        private Builder() {
          // force use of static builder() method
        }


        /**
         * Unique identifier for the vulnerable asset.
         */
        public Builder id(String id) {
            Utils.checkNotNull(id, "id");
            this.id = id;
            return this;
        }


        /**
         * Display name of the vulnerable asset.
         */
        public Builder name(String name) {
            Utils.checkNotNull(name, "name");
            this.name = name;
            return this;
        }


        /**
         * VulnerableAssetType describes the types of assets a vulnerability is on.
         */
        public Builder assetType(VulnerableAssetType assetType) {
            Utils.checkNotNull(assetType, "assetType");
            this.assetType = assetType;
            return this;
        }


        /**
         * Whether the vulnerable asset has been scanned.
         */
        public Builder hasBeenScanned(boolean hasBeenScanned) {
            Utils.checkNotNull(hasBeenScanned, "hasBeenScanned");
            this.hasBeenScanned = hasBeenScanned;
            return this;
        }


        /**
         * Only relevant for container repositories. This field sets the container image tag that
         * vulnerabilities will be retrieved for. If null, the latest image will be retrieved.
         */
        public Builder imageScanTag(String imageScanTag) {
            Utils.checkNotNull(imageScanTag, "imageScanTag");
            this.imageScanTag = Optional.ofNullable(imageScanTag);
            return this;
        }

        /**
         * Only relevant for container repositories. This field sets the container image tag that
         * vulnerabilities will be retrieved for. If null, the latest image will be retrieved.
         */
        public Builder imageScanTag(Optional<String> imageScanTag) {
            Utils.checkNotNull(imageScanTag, "imageScanTag");
            this.imageScanTag = imageScanTag;
            return this;
        }


        /**
         * The integrations that are scanning this vulnerable asset.
         */
        public Builder scanners(List<VulnerableAssetScanner> scanners) {
            Utils.checkNotNull(scanners, "scanners");
            this.scanners = scanners;
            return this;
        }

        public VulnerableAsset build() {

            return new VulnerableAsset(
                id, name, assetType,
                hasBeenScanned, imageScanTag, scanners);
        }

    }
}
