/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.vanta.vanta_auditor_api;

import static com.vanta.vanta_auditor_api.operations.Operations.RequestOperation;

import com.vanta.vanta_auditor_api.models.components.AddAuditorInput;
import com.vanta.vanta_auditor_api.models.operations.CreateAuditorRequestBuilder;
import com.vanta.vanta_auditor_api.models.operations.CreateAuditorResponse;
import com.vanta.vanta_auditor_api.operations.CreateAuditorOperation;
import java.lang.Exception;


public class Auditors {
    private final SDKConfiguration sdkConfiguration;

    Auditors(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    /**
     * Create an auditor
     * 
     * <p>Create an auditor in Vanta.
     * 
     * @return The call builder
     */
    public CreateAuditorRequestBuilder create() {
        return new CreateAuditorRequestBuilder(sdkConfiguration);
    }

    /**
     * Create an auditor
     * 
     * <p>Create an auditor in Vanta.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public CreateAuditorResponse create(AddAuditorInput request) throws Exception {
        RequestOperation<AddAuditorInput, CreateAuditorResponse> operation
              = new CreateAuditorOperation(sdkConfiguration);
        return operation.handleResponse(operation.doRequest(request));
    }

}
