workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Conduct an audit:
        inputs:
            - location: api_spec.yaml
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
        registry:
            location: registry.speakeasyapi.dev/vanta/vanta/conduct-an-audit
targets:
    vanta:
        target: java
        source: Conduct an audit
        publish:
            java:
                ossrhUsername: $ossrh_username
                ossrhPassword: $ossrh_password
                gpgSecretKey: $java_gpg_secret_key
                gpgPassPhrase: $java_gpg_passphrase
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/vanta/vanta/conduct-an-audit-java-code-samples
            blocking: false
