/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.vanta.vanta_auditor_api.models.operations.async;

import static com.vanta.vanta_auditor_api.operations.Operations.AsyncRequestOperation;

import com.vanta.vanta_auditor_api.SDKConfiguration;
import com.vanta.vanta_auditor_api.models.components.AddAuditControlCommentInput;
import com.vanta.vanta_auditor_api.models.operations.CreateCommentForControlRequest;
import com.vanta.vanta_auditor_api.operations.CreateCommentForControl;
import com.vanta.vanta_auditor_api.utils.Headers;
import com.vanta.vanta_auditor_api.utils.Utils;
import java.lang.String;
import java.util.concurrent.CompletableFuture;

public class CreateCommentForControlRequestBuilder {

    private String auditId;
    private String controlId;
    private AddAuditControlCommentInput addAuditControlCommentInput;
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public CreateCommentForControlRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public CreateCommentForControlRequestBuilder auditId(String auditId) {
        Utils.checkNotNull(auditId, "auditId");
        this.auditId = auditId;
        return this;
    }

    public CreateCommentForControlRequestBuilder controlId(String controlId) {
        Utils.checkNotNull(controlId, "controlId");
        this.controlId = controlId;
        return this;
    }

    public CreateCommentForControlRequestBuilder addAuditControlCommentInput(AddAuditControlCommentInput addAuditControlCommentInput) {
        Utils.checkNotNull(addAuditControlCommentInput, "addAuditControlCommentInput");
        this.addAuditControlCommentInput = addAuditControlCommentInput;
        return this;
    }


    private CreateCommentForControlRequest buildRequest() {

        CreateCommentForControlRequest request = new CreateCommentForControlRequest(auditId,
            controlId,
            addAuditControlCommentInput);

        return request;
    }

    public CompletableFuture<CreateCommentForControlResponse> call() {
        
        AsyncRequestOperation<CreateCommentForControlRequest, CreateCommentForControlResponse> operation
              = new CreateCommentForControl.Async(sdkConfiguration, _headers);
        CreateCommentForControlRequest request = buildRequest();

        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }
}
