/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.vanta.vanta_auditor_api.models.operations.async;

import static com.vanta.vanta_auditor_api.operations.Operations.AsyncRequestOperation;

import com.vanta.vanta_auditor_api.SDKConfiguration;
import com.vanta.vanta_auditor_api.models.components.CreateCustomEvidenceRequestInput;
import com.vanta.vanta_auditor_api.models.operations.CreateCustomEvidenceRequestRequest;
import com.vanta.vanta_auditor_api.operations.CreateCustomEvidenceRequest;
import com.vanta.vanta_auditor_api.utils.Headers;
import com.vanta.vanta_auditor_api.utils.Utils;
import java.lang.Exception;
import java.lang.String;
import java.util.concurrent.CompletableFuture;

public class CreateCustomEvidenceRequestRequestBuilder {

    private String auditId;
    private CreateCustomEvidenceRequestInput createCustomEvidenceRequestInput;
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public CreateCustomEvidenceRequestRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public CreateCustomEvidenceRequestRequestBuilder auditId(String auditId) {
        Utils.checkNotNull(auditId, "auditId");
        this.auditId = auditId;
        return this;
    }

    public CreateCustomEvidenceRequestRequestBuilder createCustomEvidenceRequestInput(CreateCustomEvidenceRequestInput createCustomEvidenceRequestInput) {
        Utils.checkNotNull(createCustomEvidenceRequestInput, "createCustomEvidenceRequestInput");
        this.createCustomEvidenceRequestInput = createCustomEvidenceRequestInput;
        return this;
    }


    private CreateCustomEvidenceRequestRequest buildRequest() {

        CreateCustomEvidenceRequestRequest request = new CreateCustomEvidenceRequestRequest(auditId,
            createCustomEvidenceRequestInput);

        return request;
    }

    public CompletableFuture<CreateCustomEvidenceRequestResponse> call() throws Exception {
        
        AsyncRequestOperation<CreateCustomEvidenceRequestRequest, CreateCustomEvidenceRequestResponse> operation
              = new CreateCustomEvidenceRequest.Async(sdkConfiguration, _headers);
        CreateCustomEvidenceRequestRequest request = buildRequest();

        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }
}
