/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.vanta.vanta_auditor_api.models.operations.async;

import static com.vanta.vanta_auditor_api.operations.Operations.AsyncRequestOperation;

import com.vanta.vanta_auditor_api.SDKConfiguration;
import com.vanta.vanta_auditor_api.models.operations.GetInformationRequestEvidenceRequest;
import com.vanta.vanta_auditor_api.operations.GetInformationRequestEvidence;
import com.vanta.vanta_auditor_api.utils.Headers;
import com.vanta.vanta_auditor_api.utils.Utils;
import java.lang.String;
import java.util.concurrent.CompletableFuture;

public class GetInformationRequestEvidenceRequestBuilder {

    private String auditId;
    private String requestId;
    private String evidenceId;
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public GetInformationRequestEvidenceRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public GetInformationRequestEvidenceRequestBuilder auditId(String auditId) {
        Utils.checkNotNull(auditId, "auditId");
        this.auditId = auditId;
        return this;
    }

    public GetInformationRequestEvidenceRequestBuilder requestId(String requestId) {
        Utils.checkNotNull(requestId, "requestId");
        this.requestId = requestId;
        return this;
    }

    public GetInformationRequestEvidenceRequestBuilder evidenceId(String evidenceId) {
        Utils.checkNotNull(evidenceId, "evidenceId");
        this.evidenceId = evidenceId;
        return this;
    }


    private GetInformationRequestEvidenceRequest buildRequest() {

        GetInformationRequestEvidenceRequest request = new GetInformationRequestEvidenceRequest(auditId,
            requestId,
            evidenceId);

        return request;
    }

    public CompletableFuture<GetInformationRequestEvidenceResponse> call() {
        
        AsyncRequestOperation<GetInformationRequestEvidenceRequest, GetInformationRequestEvidenceResponse> operation
              = new GetInformationRequestEvidence.Async(sdkConfiguration, _headers);
        GetInformationRequestEvidenceRequest request = buildRequest();

        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }
}
