/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.vanta.vanta_auditor_api.models.operations.async;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.vanta.vanta_auditor_api.models.components.PaginatedResponseInformationRequest;
import com.vanta.vanta_auditor_api.utils.AsyncResponse;
import com.vanta.vanta_auditor_api.utils.Blob;
import com.vanta.vanta_auditor_api.utils.Utils;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.net.http.HttpResponse;
import java.util.Optional;


public class ListInformationRequestsForControlResponse implements AsyncResponse {
    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<Blob> rawResponse;

    /**
     * Ok
     */
    private Optional<? extends PaginatedResponseInformationRequest> paginatedResponseInformationRequest;

    @JsonCreator
    public ListInformationRequestsForControlResponse(
            String contentType,
            int statusCode,
            HttpResponse<Blob> rawResponse,
            Optional<? extends PaginatedResponseInformationRequest> paginatedResponseInformationRequest) {
        Utils.checkNotNull(contentType, "contentType");
        Utils.checkNotNull(statusCode, "statusCode");
        Utils.checkNotNull(rawResponse, "rawResponse");
        Utils.checkNotNull(paginatedResponseInformationRequest, "paginatedResponseInformationRequest");
        this.contentType = contentType;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
        this.paginatedResponseInformationRequest = paginatedResponseInformationRequest;
    }
    
    public ListInformationRequestsForControlResponse(
            String contentType,
            int statusCode,
            HttpResponse<Blob> rawResponse) {
        this(contentType, statusCode, rawResponse,
            Optional.empty());
    }

    /**
     * HTTP response content type for this operation
     */
    @JsonIgnore
    public String contentType() {
        return contentType;
    }

    /**
     * HTTP response status code for this operation
     */
    @JsonIgnore
    public int statusCode() {
        return statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @JsonIgnore
    public HttpResponse<Blob> rawResponse() {
        return rawResponse;
    }

    /**
     * Ok
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<PaginatedResponseInformationRequest> paginatedResponseInformationRequest() {
        return (Optional<PaginatedResponseInformationRequest>) paginatedResponseInformationRequest;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * HTTP response content type for this operation
     */
    public ListInformationRequestsForControlResponse withContentType(String contentType) {
        Utils.checkNotNull(contentType, "contentType");
        this.contentType = contentType;
        return this;
    }

    /**
     * HTTP response status code for this operation
     */
    public ListInformationRequestsForControlResponse withStatusCode(int statusCode) {
        Utils.checkNotNull(statusCode, "statusCode");
        this.statusCode = statusCode;
        return this;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public ListInformationRequestsForControlResponse withRawResponse(HttpResponse<Blob> rawResponse) {
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.rawResponse = rawResponse;
        return this;
    }

    /**
     * Ok
     */
    public ListInformationRequestsForControlResponse withPaginatedResponseInformationRequest(PaginatedResponseInformationRequest paginatedResponseInformationRequest) {
        Utils.checkNotNull(paginatedResponseInformationRequest, "paginatedResponseInformationRequest");
        this.paginatedResponseInformationRequest = Optional.ofNullable(paginatedResponseInformationRequest);
        return this;
    }


    /**
     * Ok
     */
    public ListInformationRequestsForControlResponse withPaginatedResponseInformationRequest(Optional<? extends PaginatedResponseInformationRequest> paginatedResponseInformationRequest) {
        Utils.checkNotNull(paginatedResponseInformationRequest, "paginatedResponseInformationRequest");
        this.paginatedResponseInformationRequest = paginatedResponseInformationRequest;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ListInformationRequestsForControlResponse other = (ListInformationRequestsForControlResponse) o;
        return 
            Utils.enhancedDeepEquals(this.contentType, other.contentType) &&
            Utils.enhancedDeepEquals(this.statusCode, other.statusCode) &&
            Utils.enhancedDeepEquals(this.rawResponse, other.rawResponse) &&
            Utils.enhancedDeepEquals(this.paginatedResponseInformationRequest, other.paginatedResponseInformationRequest);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            contentType, statusCode, rawResponse,
            paginatedResponseInformationRequest);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ListInformationRequestsForControlResponse.class,
                "contentType", contentType,
                "statusCode", statusCode,
                "rawResponse", rawResponse,
                "paginatedResponseInformationRequest", paginatedResponseInformationRequest);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String contentType;

        private Integer statusCode;

        private HttpResponse<Blob> rawResponse;

        private Optional<? extends PaginatedResponseInformationRequest> paginatedResponseInformationRequest = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(String contentType) {
            Utils.checkNotNull(contentType, "contentType");
            this.contentType = contentType;
            return this;
        }


        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            Utils.checkNotNull(statusCode, "statusCode");
            this.statusCode = statusCode;
            return this;
        }


        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(HttpResponse<Blob> rawResponse) {
            Utils.checkNotNull(rawResponse, "rawResponse");
            this.rawResponse = rawResponse;
            return this;
        }


        /**
         * Ok
         */
        public Builder paginatedResponseInformationRequest(PaginatedResponseInformationRequest paginatedResponseInformationRequest) {
            Utils.checkNotNull(paginatedResponseInformationRequest, "paginatedResponseInformationRequest");
            this.paginatedResponseInformationRequest = Optional.ofNullable(paginatedResponseInformationRequest);
            return this;
        }

        /**
         * Ok
         */
        public Builder paginatedResponseInformationRequest(Optional<? extends PaginatedResponseInformationRequest> paginatedResponseInformationRequest) {
            Utils.checkNotNull(paginatedResponseInformationRequest, "paginatedResponseInformationRequest");
            this.paginatedResponseInformationRequest = paginatedResponseInformationRequest;
            return this;
        }

        public ListInformationRequestsForControlResponse build() {

            return new ListInformationRequestsForControlResponse(
                contentType, statusCode, rawResponse,
                paginatedResponseInformationRequest);
        }

    }
}
