/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.vanta.vanta_auditor_api.models.operations.async;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.vanta.vanta_auditor_api.models.components.PaginatedResponseRiskSnapshot;
import com.vanta.vanta_auditor_api.utils.AsyncResponse;
import com.vanta.vanta_auditor_api.utils.Blob;
import com.vanta.vanta_auditor_api.utils.Utils;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.net.http.HttpResponse;
import java.util.Optional;


public class ListRiskSnapshotsResponse implements AsyncResponse {
    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<Blob> rawResponse;

    /**
     * Paginated list of risk snapshots with pagination metadata
     */
    private Optional<? extends PaginatedResponseRiskSnapshot> paginatedResponseRiskSnapshot;

    @JsonCreator
    public ListRiskSnapshotsResponse(
            String contentType,
            int statusCode,
            HttpResponse<Blob> rawResponse,
            Optional<? extends PaginatedResponseRiskSnapshot> paginatedResponseRiskSnapshot) {
        Utils.checkNotNull(contentType, "contentType");
        Utils.checkNotNull(statusCode, "statusCode");
        Utils.checkNotNull(rawResponse, "rawResponse");
        Utils.checkNotNull(paginatedResponseRiskSnapshot, "paginatedResponseRiskSnapshot");
        this.contentType = contentType;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
        this.paginatedResponseRiskSnapshot = paginatedResponseRiskSnapshot;
    }
    
    public ListRiskSnapshotsResponse(
            String contentType,
            int statusCode,
            HttpResponse<Blob> rawResponse) {
        this(contentType, statusCode, rawResponse,
            Optional.empty());
    }

    /**
     * HTTP response content type for this operation
     */
    @JsonIgnore
    public String contentType() {
        return contentType;
    }

    /**
     * HTTP response status code for this operation
     */
    @JsonIgnore
    public int statusCode() {
        return statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @JsonIgnore
    public HttpResponse<Blob> rawResponse() {
        return rawResponse;
    }

    /**
     * Paginated list of risk snapshots with pagination metadata
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<PaginatedResponseRiskSnapshot> paginatedResponseRiskSnapshot() {
        return (Optional<PaginatedResponseRiskSnapshot>) paginatedResponseRiskSnapshot;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * HTTP response content type for this operation
     */
    public ListRiskSnapshotsResponse withContentType(String contentType) {
        Utils.checkNotNull(contentType, "contentType");
        this.contentType = contentType;
        return this;
    }

    /**
     * HTTP response status code for this operation
     */
    public ListRiskSnapshotsResponse withStatusCode(int statusCode) {
        Utils.checkNotNull(statusCode, "statusCode");
        this.statusCode = statusCode;
        return this;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public ListRiskSnapshotsResponse withRawResponse(HttpResponse<Blob> rawResponse) {
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.rawResponse = rawResponse;
        return this;
    }

    /**
     * Paginated list of risk snapshots with pagination metadata
     */
    public ListRiskSnapshotsResponse withPaginatedResponseRiskSnapshot(PaginatedResponseRiskSnapshot paginatedResponseRiskSnapshot) {
        Utils.checkNotNull(paginatedResponseRiskSnapshot, "paginatedResponseRiskSnapshot");
        this.paginatedResponseRiskSnapshot = Optional.ofNullable(paginatedResponseRiskSnapshot);
        return this;
    }


    /**
     * Paginated list of risk snapshots with pagination metadata
     */
    public ListRiskSnapshotsResponse withPaginatedResponseRiskSnapshot(Optional<? extends PaginatedResponseRiskSnapshot> paginatedResponseRiskSnapshot) {
        Utils.checkNotNull(paginatedResponseRiskSnapshot, "paginatedResponseRiskSnapshot");
        this.paginatedResponseRiskSnapshot = paginatedResponseRiskSnapshot;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ListRiskSnapshotsResponse other = (ListRiskSnapshotsResponse) o;
        return 
            Utils.enhancedDeepEquals(this.contentType, other.contentType) &&
            Utils.enhancedDeepEquals(this.statusCode, other.statusCode) &&
            Utils.enhancedDeepEquals(this.rawResponse, other.rawResponse) &&
            Utils.enhancedDeepEquals(this.paginatedResponseRiskSnapshot, other.paginatedResponseRiskSnapshot);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            contentType, statusCode, rawResponse,
            paginatedResponseRiskSnapshot);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ListRiskSnapshotsResponse.class,
                "contentType", contentType,
                "statusCode", statusCode,
                "rawResponse", rawResponse,
                "paginatedResponseRiskSnapshot", paginatedResponseRiskSnapshot);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String contentType;

        private Integer statusCode;

        private HttpResponse<Blob> rawResponse;

        private Optional<? extends PaginatedResponseRiskSnapshot> paginatedResponseRiskSnapshot = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(String contentType) {
            Utils.checkNotNull(contentType, "contentType");
            this.contentType = contentType;
            return this;
        }


        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            Utils.checkNotNull(statusCode, "statusCode");
            this.statusCode = statusCode;
            return this;
        }


        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(HttpResponse<Blob> rawResponse) {
            Utils.checkNotNull(rawResponse, "rawResponse");
            this.rawResponse = rawResponse;
            return this;
        }


        /**
         * Paginated list of risk snapshots with pagination metadata
         */
        public Builder paginatedResponseRiskSnapshot(PaginatedResponseRiskSnapshot paginatedResponseRiskSnapshot) {
            Utils.checkNotNull(paginatedResponseRiskSnapshot, "paginatedResponseRiskSnapshot");
            this.paginatedResponseRiskSnapshot = Optional.ofNullable(paginatedResponseRiskSnapshot);
            return this;
        }

        /**
         * Paginated list of risk snapshots with pagination metadata
         */
        public Builder paginatedResponseRiskSnapshot(Optional<? extends PaginatedResponseRiskSnapshot> paginatedResponseRiskSnapshot) {
            Utils.checkNotNull(paginatedResponseRiskSnapshot, "paginatedResponseRiskSnapshot");
            this.paginatedResponseRiskSnapshot = paginatedResponseRiskSnapshot;
            return this;
        }

        public ListRiskSnapshotsResponse build() {

            return new ListRiskSnapshotsResponse(
                contentType, statusCode, rawResponse,
                paginatedResponseRiskSnapshot);
        }

    }
}
