/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.vanta.vanta_auditor_api.models.operations.async;

import static com.vanta.vanta_auditor_api.operations.Operations.AsyncRequestOperation;

import com.vanta.vanta_auditor_api.SDKConfiguration;
import com.vanta.vanta_auditor_api.models.operations.ListCommentsForInformationRequestRequest;
import com.vanta.vanta_auditor_api.operations.ListCommentsForInformationRequest;
import com.vanta.vanta_auditor_api.utils.Headers;
import com.vanta.vanta_auditor_api.utils.Utils;
import java.util.concurrent.CompletableFuture;

public class ListCommentsForInformationRequestRequestBuilder {

    private ListCommentsForInformationRequestRequest request;
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public ListCommentsForInformationRequestRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public ListCommentsForInformationRequestRequestBuilder request(ListCommentsForInformationRequestRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public CompletableFuture<ListCommentsForInformationRequestResponse> call() {
        
        AsyncRequestOperation<ListCommentsForInformationRequestRequest, ListCommentsForInformationRequestResponse> operation
              = new ListCommentsForInformationRequest.Async(sdkConfiguration, _headers);

        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }
}
