/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.vanta.vanta_auditor_api.models.operations.async;

import static com.vanta.vanta_auditor_api.operations.Operations.AsyncRequestOperation;

import com.vanta.vanta_auditor_api.SDKConfiguration;
import com.vanta.vanta_auditor_api.models.operations.ListInformationRequestActivityRequest;
import com.vanta.vanta_auditor_api.operations.ListInformationRequestActivity;
import com.vanta.vanta_auditor_api.utils.Headers;
import com.vanta.vanta_auditor_api.utils.Utils;
import java.util.concurrent.CompletableFuture;

public class ListInformationRequestActivityRequestBuilder {

    private ListInformationRequestActivityRequest request;
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public ListInformationRequestActivityRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public ListInformationRequestActivityRequestBuilder request(ListInformationRequestActivityRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public CompletableFuture<ListInformationRequestActivityResponse> call() {
        
        AsyncRequestOperation<ListInformationRequestActivityRequest, ListInformationRequestActivityResponse> operation
              = new ListInformationRequestActivity.Async(sdkConfiguration, _headers);

        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }
}
