/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.vanta.vanta_auditor_api.models.operations.async;

import static com.vanta.vanta_auditor_api.operations.Operations.AsyncRequestOperation;

import com.vanta.vanta_auditor_api.SDKConfiguration;
import com.vanta.vanta_auditor_api.models.operations.ListInformationRequestsRequest;
import com.vanta.vanta_auditor_api.operations.ListInformationRequests;
import com.vanta.vanta_auditor_api.utils.Headers;
import com.vanta.vanta_auditor_api.utils.Utils;
import java.util.concurrent.CompletableFuture;

public class ListInformationRequestsRequestBuilder {

    private ListInformationRequestsRequest request;
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public ListInformationRequestsRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public ListInformationRequestsRequestBuilder request(ListInformationRequestsRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public CompletableFuture<ListInformationRequestsResponse> call() {
        
        AsyncRequestOperation<ListInformationRequestsRequest, ListInformationRequestsResponse> operation
              = new ListInformationRequests.Async(sdkConfiguration, _headers);

        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }
}
