/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.vanta.vanta_auditor_api.models.operations.async;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.vanta.vanta_auditor_api.models.components.PaginatedResponsePerson;
import com.vanta.vanta_auditor_api.utils.AsyncResponse;
import com.vanta.vanta_auditor_api.utils.Blob;
import com.vanta.vanta_auditor_api.utils.Utils;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.net.http.HttpResponse;
import java.util.Optional;


public class ListPeopleInAuditScopeResponse implements AsyncResponse {
    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<Blob> rawResponse;

    /**
     * Ok
     */
    private Optional<? extends PaginatedResponsePerson> paginatedResponsePerson;

    @JsonCreator
    public ListPeopleInAuditScopeResponse(
            String contentType,
            int statusCode,
            HttpResponse<Blob> rawResponse,
            Optional<? extends PaginatedResponsePerson> paginatedResponsePerson) {
        Utils.checkNotNull(contentType, "contentType");
        Utils.checkNotNull(statusCode, "statusCode");
        Utils.checkNotNull(rawResponse, "rawResponse");
        Utils.checkNotNull(paginatedResponsePerson, "paginatedResponsePerson");
        this.contentType = contentType;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
        this.paginatedResponsePerson = paginatedResponsePerson;
    }
    
    public ListPeopleInAuditScopeResponse(
            String contentType,
            int statusCode,
            HttpResponse<Blob> rawResponse) {
        this(contentType, statusCode, rawResponse,
            Optional.empty());
    }

    /**
     * HTTP response content type for this operation
     */
    @JsonIgnore
    public String contentType() {
        return contentType;
    }

    /**
     * HTTP response status code for this operation
     */
    @JsonIgnore
    public int statusCode() {
        return statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @JsonIgnore
    public HttpResponse<Blob> rawResponse() {
        return rawResponse;
    }

    /**
     * Ok
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<PaginatedResponsePerson> paginatedResponsePerson() {
        return (Optional<PaginatedResponsePerson>) paginatedResponsePerson;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * HTTP response content type for this operation
     */
    public ListPeopleInAuditScopeResponse withContentType(String contentType) {
        Utils.checkNotNull(contentType, "contentType");
        this.contentType = contentType;
        return this;
    }

    /**
     * HTTP response status code for this operation
     */
    public ListPeopleInAuditScopeResponse withStatusCode(int statusCode) {
        Utils.checkNotNull(statusCode, "statusCode");
        this.statusCode = statusCode;
        return this;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public ListPeopleInAuditScopeResponse withRawResponse(HttpResponse<Blob> rawResponse) {
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.rawResponse = rawResponse;
        return this;
    }

    /**
     * Ok
     */
    public ListPeopleInAuditScopeResponse withPaginatedResponsePerson(PaginatedResponsePerson paginatedResponsePerson) {
        Utils.checkNotNull(paginatedResponsePerson, "paginatedResponsePerson");
        this.paginatedResponsePerson = Optional.ofNullable(paginatedResponsePerson);
        return this;
    }


    /**
     * Ok
     */
    public ListPeopleInAuditScopeResponse withPaginatedResponsePerson(Optional<? extends PaginatedResponsePerson> paginatedResponsePerson) {
        Utils.checkNotNull(paginatedResponsePerson, "paginatedResponsePerson");
        this.paginatedResponsePerson = paginatedResponsePerson;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ListPeopleInAuditScopeResponse other = (ListPeopleInAuditScopeResponse) o;
        return 
            Utils.enhancedDeepEquals(this.contentType, other.contentType) &&
            Utils.enhancedDeepEquals(this.statusCode, other.statusCode) &&
            Utils.enhancedDeepEquals(this.rawResponse, other.rawResponse) &&
            Utils.enhancedDeepEquals(this.paginatedResponsePerson, other.paginatedResponsePerson);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            contentType, statusCode, rawResponse,
            paginatedResponsePerson);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ListPeopleInAuditScopeResponse.class,
                "contentType", contentType,
                "statusCode", statusCode,
                "rawResponse", rawResponse,
                "paginatedResponsePerson", paginatedResponsePerson);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String contentType;

        private Integer statusCode;

        private HttpResponse<Blob> rawResponse;

        private Optional<? extends PaginatedResponsePerson> paginatedResponsePerson = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(String contentType) {
            Utils.checkNotNull(contentType, "contentType");
            this.contentType = contentType;
            return this;
        }


        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            Utils.checkNotNull(statusCode, "statusCode");
            this.statusCode = statusCode;
            return this;
        }


        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(HttpResponse<Blob> rawResponse) {
            Utils.checkNotNull(rawResponse, "rawResponse");
            this.rawResponse = rawResponse;
            return this;
        }


        /**
         * Ok
         */
        public Builder paginatedResponsePerson(PaginatedResponsePerson paginatedResponsePerson) {
            Utils.checkNotNull(paginatedResponsePerson, "paginatedResponsePerson");
            this.paginatedResponsePerson = Optional.ofNullable(paginatedResponsePerson);
            return this;
        }

        /**
         * Ok
         */
        public Builder paginatedResponsePerson(Optional<? extends PaginatedResponsePerson> paginatedResponsePerson) {
            Utils.checkNotNull(paginatedResponsePerson, "paginatedResponsePerson");
            this.paginatedResponsePerson = paginatedResponsePerson;
            return this;
        }

        public ListPeopleInAuditScopeResponse build() {

            return new ListPeopleInAuditScopeResponse(
                contentType, statusCode, rawResponse,
                paginatedResponsePerson);
        }

    }
}
