/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.vanta.vanta_auditor_api.models.operations.async;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.vanta.vanta_auditor_api.models.components.PaginatedResponseInformationRequestEvidence;
import com.vanta.vanta_auditor_api.utils.AsyncResponse;
import com.vanta.vanta_auditor_api.utils.Blob;
import com.vanta.vanta_auditor_api.utils.Utils;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.net.http.HttpResponse;
import java.util.Optional;


public class ListInformationRequestEvidenceResponse implements AsyncResponse {
    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<Blob> rawResponse;

    /**
     * Ok
     */
    private Optional<? extends PaginatedResponseInformationRequestEvidence> paginatedResponseInformationRequestEvidence;

    @JsonCreator
    public ListInformationRequestEvidenceResponse(
            String contentType,
            int statusCode,
            HttpResponse<Blob> rawResponse,
            Optional<? extends PaginatedResponseInformationRequestEvidence> paginatedResponseInformationRequestEvidence) {
        Utils.checkNotNull(contentType, "contentType");
        Utils.checkNotNull(statusCode, "statusCode");
        Utils.checkNotNull(rawResponse, "rawResponse");
        Utils.checkNotNull(paginatedResponseInformationRequestEvidence, "paginatedResponseInformationRequestEvidence");
        this.contentType = contentType;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
        this.paginatedResponseInformationRequestEvidence = paginatedResponseInformationRequestEvidence;
    }
    
    public ListInformationRequestEvidenceResponse(
            String contentType,
            int statusCode,
            HttpResponse<Blob> rawResponse) {
        this(contentType, statusCode, rawResponse,
            Optional.empty());
    }

    /**
     * HTTP response content type for this operation
     */
    @JsonIgnore
    public String contentType() {
        return contentType;
    }

    /**
     * HTTP response status code for this operation
     */
    @JsonIgnore
    public int statusCode() {
        return statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @JsonIgnore
    public HttpResponse<Blob> rawResponse() {
        return rawResponse;
    }

    /**
     * Ok
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<PaginatedResponseInformationRequestEvidence> paginatedResponseInformationRequestEvidence() {
        return (Optional<PaginatedResponseInformationRequestEvidence>) paginatedResponseInformationRequestEvidence;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * HTTP response content type for this operation
     */
    public ListInformationRequestEvidenceResponse withContentType(String contentType) {
        Utils.checkNotNull(contentType, "contentType");
        this.contentType = contentType;
        return this;
    }

    /**
     * HTTP response status code for this operation
     */
    public ListInformationRequestEvidenceResponse withStatusCode(int statusCode) {
        Utils.checkNotNull(statusCode, "statusCode");
        this.statusCode = statusCode;
        return this;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public ListInformationRequestEvidenceResponse withRawResponse(HttpResponse<Blob> rawResponse) {
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.rawResponse = rawResponse;
        return this;
    }

    /**
     * Ok
     */
    public ListInformationRequestEvidenceResponse withPaginatedResponseInformationRequestEvidence(PaginatedResponseInformationRequestEvidence paginatedResponseInformationRequestEvidence) {
        Utils.checkNotNull(paginatedResponseInformationRequestEvidence, "paginatedResponseInformationRequestEvidence");
        this.paginatedResponseInformationRequestEvidence = Optional.ofNullable(paginatedResponseInformationRequestEvidence);
        return this;
    }


    /**
     * Ok
     */
    public ListInformationRequestEvidenceResponse withPaginatedResponseInformationRequestEvidence(Optional<? extends PaginatedResponseInformationRequestEvidence> paginatedResponseInformationRequestEvidence) {
        Utils.checkNotNull(paginatedResponseInformationRequestEvidence, "paginatedResponseInformationRequestEvidence");
        this.paginatedResponseInformationRequestEvidence = paginatedResponseInformationRequestEvidence;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ListInformationRequestEvidenceResponse other = (ListInformationRequestEvidenceResponse) o;
        return 
            Utils.enhancedDeepEquals(this.contentType, other.contentType) &&
            Utils.enhancedDeepEquals(this.statusCode, other.statusCode) &&
            Utils.enhancedDeepEquals(this.rawResponse, other.rawResponse) &&
            Utils.enhancedDeepEquals(this.paginatedResponseInformationRequestEvidence, other.paginatedResponseInformationRequestEvidence);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            contentType, statusCode, rawResponse,
            paginatedResponseInformationRequestEvidence);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ListInformationRequestEvidenceResponse.class,
                "contentType", contentType,
                "statusCode", statusCode,
                "rawResponse", rawResponse,
                "paginatedResponseInformationRequestEvidence", paginatedResponseInformationRequestEvidence);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String contentType;

        private Integer statusCode;

        private HttpResponse<Blob> rawResponse;

        private Optional<? extends PaginatedResponseInformationRequestEvidence> paginatedResponseInformationRequestEvidence = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(String contentType) {
            Utils.checkNotNull(contentType, "contentType");
            this.contentType = contentType;
            return this;
        }


        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            Utils.checkNotNull(statusCode, "statusCode");
            this.statusCode = statusCode;
            return this;
        }


        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(HttpResponse<Blob> rawResponse) {
            Utils.checkNotNull(rawResponse, "rawResponse");
            this.rawResponse = rawResponse;
            return this;
        }


        /**
         * Ok
         */
        public Builder paginatedResponseInformationRequestEvidence(PaginatedResponseInformationRequestEvidence paginatedResponseInformationRequestEvidence) {
            Utils.checkNotNull(paginatedResponseInformationRequestEvidence, "paginatedResponseInformationRequestEvidence");
            this.paginatedResponseInformationRequestEvidence = Optional.ofNullable(paginatedResponseInformationRequestEvidence);
            return this;
        }

        /**
         * Ok
         */
        public Builder paginatedResponseInformationRequestEvidence(Optional<? extends PaginatedResponseInformationRequestEvidence> paginatedResponseInformationRequestEvidence) {
            Utils.checkNotNull(paginatedResponseInformationRequestEvidence, "paginatedResponseInformationRequestEvidence");
            this.paginatedResponseInformationRequestEvidence = paginatedResponseInformationRequestEvidence;
            return this;
        }

        public ListInformationRequestEvidenceResponse build() {

            return new ListInformationRequestEvidenceResponse(
                contentType, statusCode, rawResponse,
                paginatedResponseInformationRequestEvidence);
        }

    }
}
