/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.vanta.vanta_auditor_api.models.operations.async;

import static com.vanta.vanta_auditor_api.operations.Operations.AsyncRequestOperation;

import com.fasterxml.jackson.core.type.TypeReference;
import com.vanta.vanta_auditor_api.SDKConfiguration;
import com.vanta.vanta_auditor_api.models.operations.ListVendorsInAuditScopeRequest;
import com.vanta.vanta_auditor_api.operations.ListVendorsInAuditScope;
import com.vanta.vanta_auditor_api.utils.Headers;
import com.vanta.vanta_auditor_api.utils.LazySingletonValue;
import com.vanta.vanta_auditor_api.utils.Utils;
import java.lang.Integer;
import java.lang.String;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;

public class ListVendorsInAuditScopeRequestBuilder {

    private String auditId;
    private Optional<Integer> pageSize = Utils.readDefaultOrConstValue(
                            "pageSize",
                            "10",
                            new TypeReference<Optional<Integer>>() {});
    private Optional<String> pageCursor = Optional.empty();
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public ListVendorsInAuditScopeRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public ListVendorsInAuditScopeRequestBuilder auditId(String auditId) {
        Utils.checkNotNull(auditId, "auditId");
        this.auditId = auditId;
        return this;
    }
                
    public ListVendorsInAuditScopeRequestBuilder pageSize(int pageSize) {
        Utils.checkNotNull(pageSize, "pageSize");
        this.pageSize = Optional.of(pageSize);
        return this;
    }

    public ListVendorsInAuditScopeRequestBuilder pageSize(Optional<Integer> pageSize) {
        Utils.checkNotNull(pageSize, "pageSize");
        this.pageSize = pageSize;
        return this;
    }
                
    public ListVendorsInAuditScopeRequestBuilder pageCursor(String pageCursor) {
        Utils.checkNotNull(pageCursor, "pageCursor");
        this.pageCursor = Optional.of(pageCursor);
        return this;
    }

    public ListVendorsInAuditScopeRequestBuilder pageCursor(Optional<String> pageCursor) {
        Utils.checkNotNull(pageCursor, "pageCursor");
        this.pageCursor = pageCursor;
        return this;
    }


    private ListVendorsInAuditScopeRequest buildRequest() {
        if (pageSize == null) {
            pageSize = _SINGLETON_VALUE_PageSize.value();
        }

        ListVendorsInAuditScopeRequest request = new ListVendorsInAuditScopeRequest(auditId,
            pageSize,
            pageCursor);

        return request;
    }

    public CompletableFuture<ListVendorsInAuditScopeResponse> call() {
        
        AsyncRequestOperation<ListVendorsInAuditScopeRequest, ListVendorsInAuditScopeResponse> operation
              = new ListVendorsInAuditScope.Async(sdkConfiguration, _headers);
        ListVendorsInAuditScopeRequest request = buildRequest();

        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }

    private static final LazySingletonValue<Optional<Integer>> _SINGLETON_VALUE_PageSize =
            new LazySingletonValue<>(
                    "pageSize",
                    "10",
                    new TypeReference<Optional<Integer>>() {});
}
