/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.vanta.vanta_auditor_api.models.operations.async;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.vanta.vanta_auditor_api.models.components.InformationRequestComment;
import com.vanta.vanta_auditor_api.utils.AsyncResponse;
import com.vanta.vanta_auditor_api.utils.Blob;
import com.vanta.vanta_auditor_api.utils.Utils;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.net.http.HttpResponse;
import java.util.Optional;


public class UpdateCommentForInformationRequestResponse implements AsyncResponse {
    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<Blob> rawResponse;

    /**
     * Ok
     */
    private Optional<? extends InformationRequestComment> informationRequestComment;

    @JsonCreator
    public UpdateCommentForInformationRequestResponse(
            String contentType,
            int statusCode,
            HttpResponse<Blob> rawResponse,
            Optional<? extends InformationRequestComment> informationRequestComment) {
        Utils.checkNotNull(contentType, "contentType");
        Utils.checkNotNull(statusCode, "statusCode");
        Utils.checkNotNull(rawResponse, "rawResponse");
        Utils.checkNotNull(informationRequestComment, "informationRequestComment");
        this.contentType = contentType;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
        this.informationRequestComment = informationRequestComment;
    }
    
    public UpdateCommentForInformationRequestResponse(
            String contentType,
            int statusCode,
            HttpResponse<Blob> rawResponse) {
        this(contentType, statusCode, rawResponse,
            Optional.empty());
    }

    /**
     * HTTP response content type for this operation
     */
    @JsonIgnore
    public String contentType() {
        return contentType;
    }

    /**
     * HTTP response status code for this operation
     */
    @JsonIgnore
    public int statusCode() {
        return statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @JsonIgnore
    public HttpResponse<Blob> rawResponse() {
        return rawResponse;
    }

    /**
     * Ok
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<InformationRequestComment> informationRequestComment() {
        return (Optional<InformationRequestComment>) informationRequestComment;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * HTTP response content type for this operation
     */
    public UpdateCommentForInformationRequestResponse withContentType(String contentType) {
        Utils.checkNotNull(contentType, "contentType");
        this.contentType = contentType;
        return this;
    }

    /**
     * HTTP response status code for this operation
     */
    public UpdateCommentForInformationRequestResponse withStatusCode(int statusCode) {
        Utils.checkNotNull(statusCode, "statusCode");
        this.statusCode = statusCode;
        return this;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public UpdateCommentForInformationRequestResponse withRawResponse(HttpResponse<Blob> rawResponse) {
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.rawResponse = rawResponse;
        return this;
    }

    /**
     * Ok
     */
    public UpdateCommentForInformationRequestResponse withInformationRequestComment(InformationRequestComment informationRequestComment) {
        Utils.checkNotNull(informationRequestComment, "informationRequestComment");
        this.informationRequestComment = Optional.ofNullable(informationRequestComment);
        return this;
    }


    /**
     * Ok
     */
    public UpdateCommentForInformationRequestResponse withInformationRequestComment(Optional<? extends InformationRequestComment> informationRequestComment) {
        Utils.checkNotNull(informationRequestComment, "informationRequestComment");
        this.informationRequestComment = informationRequestComment;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UpdateCommentForInformationRequestResponse other = (UpdateCommentForInformationRequestResponse) o;
        return 
            Utils.enhancedDeepEquals(this.contentType, other.contentType) &&
            Utils.enhancedDeepEquals(this.statusCode, other.statusCode) &&
            Utils.enhancedDeepEquals(this.rawResponse, other.rawResponse) &&
            Utils.enhancedDeepEquals(this.informationRequestComment, other.informationRequestComment);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            contentType, statusCode, rawResponse,
            informationRequestComment);
    }
    
    @Override
    public String toString() {
        return Utils.toString(UpdateCommentForInformationRequestResponse.class,
                "contentType", contentType,
                "statusCode", statusCode,
                "rawResponse", rawResponse,
                "informationRequestComment", informationRequestComment);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String contentType;

        private Integer statusCode;

        private HttpResponse<Blob> rawResponse;

        private Optional<? extends InformationRequestComment> informationRequestComment = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(String contentType) {
            Utils.checkNotNull(contentType, "contentType");
            this.contentType = contentType;
            return this;
        }


        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            Utils.checkNotNull(statusCode, "statusCode");
            this.statusCode = statusCode;
            return this;
        }


        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(HttpResponse<Blob> rawResponse) {
            Utils.checkNotNull(rawResponse, "rawResponse");
            this.rawResponse = rawResponse;
            return this;
        }


        /**
         * Ok
         */
        public Builder informationRequestComment(InformationRequestComment informationRequestComment) {
            Utils.checkNotNull(informationRequestComment, "informationRequestComment");
            this.informationRequestComment = Optional.ofNullable(informationRequestComment);
            return this;
        }

        /**
         * Ok
         */
        public Builder informationRequestComment(Optional<? extends InformationRequestComment> informationRequestComment) {
            Utils.checkNotNull(informationRequestComment, "informationRequestComment");
            this.informationRequestComment = informationRequestComment;
            return this;
        }

        public UpdateCommentForInformationRequestResponse build() {

            return new UpdateCommentForInformationRequestResponse(
                contentType, statusCode, rawResponse,
                informationRequestComment);
        }

    }
}
