/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.vanta.vanta_auditor_api.models.operations;

import static com.vanta.vanta_auditor_api.operations.Operations.RequestOperation;

import com.vanta.vanta_auditor_api.SDKConfiguration;
import com.vanta.vanta_auditor_api.models.components.CreateCustomControlInput;
import com.vanta.vanta_auditor_api.operations.CreateCustomControl;
import com.vanta.vanta_auditor_api.utils.Headers;
import com.vanta.vanta_auditor_api.utils.Utils;
import java.lang.Exception;
import java.lang.String;

public class CreateCustomControlRequestBuilder {

    private String auditId;
    private CreateCustomControlInput createCustomControlInput;
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public CreateCustomControlRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public CreateCustomControlRequestBuilder auditId(String auditId) {
        Utils.checkNotNull(auditId, "auditId");
        this.auditId = auditId;
        return this;
    }

    public CreateCustomControlRequestBuilder createCustomControlInput(CreateCustomControlInput createCustomControlInput) {
        Utils.checkNotNull(createCustomControlInput, "createCustomControlInput");
        this.createCustomControlInput = createCustomControlInput;
        return this;
    }


    private CreateCustomControlRequest buildRequest() {

        CreateCustomControlRequest request = new CreateCustomControlRequest(auditId,
            createCustomControlInput);

        return request;
    }

    public CreateCustomControlResponse call() throws Exception {
        
        RequestOperation<CreateCustomControlRequest, CreateCustomControlResponse> operation
              = new CreateCustomControl.Sync(sdkConfiguration, _headers);
        CreateCustomControlRequest request = buildRequest();

        return operation.handleResponse(operation.doRequest(request));
    }
}
