/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.vanta.vanta_auditor_api.models.operations;

import static com.vanta.vanta_auditor_api.operations.Operations.RequestOperation;

import com.vanta.vanta_auditor_api.SDKConfiguration;
import com.vanta.vanta_auditor_api.operations.GetAuditEvidence;
import com.vanta.vanta_auditor_api.utils.Headers;
import com.vanta.vanta_auditor_api.utils.Utils;
import java.lang.String;

public class GetAuditEvidenceRequestBuilder {

    private String auditId;
    private String auditEvidenceId;
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public GetAuditEvidenceRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public GetAuditEvidenceRequestBuilder auditId(String auditId) {
        Utils.checkNotNull(auditId, "auditId");
        this.auditId = auditId;
        return this;
    }

    public GetAuditEvidenceRequestBuilder auditEvidenceId(String auditEvidenceId) {
        Utils.checkNotNull(auditEvidenceId, "auditEvidenceId");
        this.auditEvidenceId = auditEvidenceId;
        return this;
    }


    private GetAuditEvidenceRequest buildRequest() {

        GetAuditEvidenceRequest request = new GetAuditEvidenceRequest(auditId,
            auditEvidenceId);

        return request;
    }

    public GetAuditEvidenceResponse call() {
        
        RequestOperation<GetAuditEvidenceRequest, GetAuditEvidenceResponse> operation
              = new GetAuditEvidence.Sync(sdkConfiguration, _headers);
        GetAuditEvidenceRequest request = buildRequest();

        return operation.handleResponse(operation.doRequest(request));
    }
}
