/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.vanta.vanta_auditor_api.models.operations;

import static com.vanta.vanta_auditor_api.operations.Operations.RequestOperation;

import com.vanta.vanta_auditor_api.SDKConfiguration;
import com.vanta.vanta_auditor_api.operations.GetInformationRequestTestSnapshotEvidenceDetail;
import com.vanta.vanta_auditor_api.utils.Headers;
import com.vanta.vanta_auditor_api.utils.Utils;
import java.lang.String;

public class GetInformationRequestTestSnapshotEvidenceDetailRequestBuilder {

    private String auditId;
    private String requestId;
    private String evidenceId;
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public GetInformationRequestTestSnapshotEvidenceDetailRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public GetInformationRequestTestSnapshotEvidenceDetailRequestBuilder auditId(String auditId) {
        Utils.checkNotNull(auditId, "auditId");
        this.auditId = auditId;
        return this;
    }

    public GetInformationRequestTestSnapshotEvidenceDetailRequestBuilder requestId(String requestId) {
        Utils.checkNotNull(requestId, "requestId");
        this.requestId = requestId;
        return this;
    }

    public GetInformationRequestTestSnapshotEvidenceDetailRequestBuilder evidenceId(String evidenceId) {
        Utils.checkNotNull(evidenceId, "evidenceId");
        this.evidenceId = evidenceId;
        return this;
    }


    private GetInformationRequestTestSnapshotEvidenceDetailRequest buildRequest() {

        GetInformationRequestTestSnapshotEvidenceDetailRequest request = new GetInformationRequestTestSnapshotEvidenceDetailRequest(auditId,
            requestId,
            evidenceId);

        return request;
    }

    public GetInformationRequestTestSnapshotEvidenceDetailResponse call() {
        
        RequestOperation<GetInformationRequestTestSnapshotEvidenceDetailRequest, GetInformationRequestTestSnapshotEvidenceDetailResponse> operation
              = new GetInformationRequestTestSnapshotEvidenceDetail.Sync(sdkConfiguration, _headers);
        GetInformationRequestTestSnapshotEvidenceDetailRequest request = buildRequest();

        return operation.handleResponse(operation.doRequest(request));
    }
}
