/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.vanta.vanta_auditor_api.models.operations;

import static com.vanta.vanta_auditor_api.operations.Operations.RequestOperation;

import com.vanta.vanta_auditor_api.SDKConfiguration;
import com.vanta.vanta_auditor_api.operations.GetOrganizationNotifications;
import com.vanta.vanta_auditor_api.utils.Headers;
import com.vanta.vanta_auditor_api.utils.Utils;
import java.lang.String;

public class GetOrganizationNotificationsRequestBuilder {

    private String auditId;
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public GetOrganizationNotificationsRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public GetOrganizationNotificationsRequestBuilder auditId(String auditId) {
        Utils.checkNotNull(auditId, "auditId");
        this.auditId = auditId;
        return this;
    }


    private GetOrganizationNotificationsRequest buildRequest() {

        GetOrganizationNotificationsRequest request = new GetOrganizationNotificationsRequest(auditId);

        return request;
    }

    public GetOrganizationNotificationsResponse call() {
        
        RequestOperation<GetOrganizationNotificationsRequest, GetOrganizationNotificationsResponse> operation
              = new GetOrganizationNotifications.Sync(sdkConfiguration, _headers);
        GetOrganizationNotificationsRequest request = buildRequest();

        return operation.handleResponse(operation.doRequest(request));
    }
}
