/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.vanta.vanta_auditor_api.models.operations;

import static com.vanta.vanta_auditor_api.operations.Operations.RequestOperation;

import com.vanta.vanta_auditor_api.SDKConfiguration;
import com.vanta.vanta_auditor_api.operations.ListPeopleInAuditScope;
import com.vanta.vanta_auditor_api.utils.Headers;
import com.vanta.vanta_auditor_api.utils.Utils;

public class ListPeopleInAuditScopeRequestBuilder {

    private ListPeopleInAuditScopeRequest request;
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public ListPeopleInAuditScopeRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public ListPeopleInAuditScopeRequestBuilder request(ListPeopleInAuditScopeRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public ListPeopleInAuditScopeResponse call() {
        
        RequestOperation<ListPeopleInAuditScopeRequest, ListPeopleInAuditScopeResponse> operation
              = new ListPeopleInAuditScope.Sync(sdkConfiguration, _headers);

        return operation.handleResponse(operation.doRequest(request));
    }
}
