/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.vanta.vanta_auditor_api.models.operations;

import static com.vanta.vanta_auditor_api.operations.Operations.RequestOperation;

import com.vanta.vanta_auditor_api.SDKConfiguration;
import com.vanta.vanta_auditor_api.operations.ListAuditIssues;
import com.vanta.vanta_auditor_api.utils.Headers;
import com.vanta.vanta_auditor_api.utils.Utils;

public class ListAuditIssuesRequestBuilder {

    private ListAuditIssuesRequest request;
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public ListAuditIssuesRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public ListAuditIssuesRequestBuilder request(ListAuditIssuesRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public ListAuditIssuesResponse call() {
        
        RequestOperation<ListAuditIssuesRequest, ListAuditIssuesResponse> operation
              = new ListAuditIssues.Sync(sdkConfiguration, _headers);

        return operation.handleResponse(operation.doRequest(request));
    }
}
