/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.vanta.vanta_auditor_api.models.operations;

import static com.vanta.vanta_auditor_api.operations.Operations.RequestOperation;

import com.vanta.vanta_auditor_api.SDKConfiguration;
import com.vanta.vanta_auditor_api.operations.ListInformationRequestEvidence;
import com.vanta.vanta_auditor_api.utils.Headers;
import com.vanta.vanta_auditor_api.utils.Utils;

public class ListInformationRequestEvidenceRequestBuilder {

    private ListInformationRequestEvidenceRequest request;
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public ListInformationRequestEvidenceRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public ListInformationRequestEvidenceRequestBuilder request(ListInformationRequestEvidenceRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public ListInformationRequestEvidenceResponse call() {
        
        RequestOperation<ListInformationRequestEvidenceRequest, ListInformationRequestEvidenceResponse> operation
              = new ListInformationRequestEvidence.Sync(sdkConfiguration, _headers);

        return operation.handleResponse(operation.doRequest(request));
    }
}
