/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.vanta.vanta_auditor_api.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.core.type.TypeReference;
import com.vanta.vanta_auditor_api.utils.LazySingletonValue;
import com.vanta.vanta_auditor_api.utils.SpeakeasyMetadata;
import com.vanta.vanta_auditor_api.utils.Utils;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.List;
import java.util.Optional;


public class ListAuditIssuesRequest {
    /**
     * The audit ID
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=auditId")
    private String auditId;

    /**
     * Maximum number of results per page (1-100, default 10)
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=pageSize")
    private Optional<Integer> pageSize;

    /**
     * Pagination cursor from previous response
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=pageCursor")
    private Optional<String> pageCursor;

    /**
     * Search term for filtering by issue title and description
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=search")
    private Optional<String> search;

    /**
     * Filter issues to specific snapshots by snapshot ID
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=snapshotIdMatchesAny")
    private Optional<? extends List<String>> snapshotIdMatchesAny;

    @JsonCreator
    public ListAuditIssuesRequest(
            String auditId,
            Optional<Integer> pageSize,
            Optional<String> pageCursor,
            Optional<String> search,
            Optional<? extends List<String>> snapshotIdMatchesAny) {
        Utils.checkNotNull(auditId, "auditId");
        Utils.checkNotNull(pageSize, "pageSize");
        Utils.checkNotNull(pageCursor, "pageCursor");
        Utils.checkNotNull(search, "search");
        Utils.checkNotNull(snapshotIdMatchesAny, "snapshotIdMatchesAny");
        this.auditId = auditId;
        this.pageSize = pageSize;
        this.pageCursor = pageCursor;
        this.search = search;
        this.snapshotIdMatchesAny = snapshotIdMatchesAny;
    }
    
    public ListAuditIssuesRequest(
            String auditId) {
        this(auditId, Optional.empty(), Optional.empty(),
            Optional.empty(), Optional.empty());
    }

    /**
     * The audit ID
     */
    @JsonIgnore
    public String auditId() {
        return auditId;
    }

    /**
     * Maximum number of results per page (1-100, default 10)
     */
    @JsonIgnore
    public Optional<Integer> pageSize() {
        return pageSize;
    }

    /**
     * Pagination cursor from previous response
     */
    @JsonIgnore
    public Optional<String> pageCursor() {
        return pageCursor;
    }

    /**
     * Search term for filtering by issue title and description
     */
    @JsonIgnore
    public Optional<String> search() {
        return search;
    }

    /**
     * Filter issues to specific snapshots by snapshot ID
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<List<String>> snapshotIdMatchesAny() {
        return (Optional<List<String>>) snapshotIdMatchesAny;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The audit ID
     */
    public ListAuditIssuesRequest withAuditId(String auditId) {
        Utils.checkNotNull(auditId, "auditId");
        this.auditId = auditId;
        return this;
    }

    /**
     * Maximum number of results per page (1-100, default 10)
     */
    public ListAuditIssuesRequest withPageSize(int pageSize) {
        Utils.checkNotNull(pageSize, "pageSize");
        this.pageSize = Optional.ofNullable(pageSize);
        return this;
    }


    /**
     * Maximum number of results per page (1-100, default 10)
     */
    public ListAuditIssuesRequest withPageSize(Optional<Integer> pageSize) {
        Utils.checkNotNull(pageSize, "pageSize");
        this.pageSize = pageSize;
        return this;
    }

    /**
     * Pagination cursor from previous response
     */
    public ListAuditIssuesRequest withPageCursor(String pageCursor) {
        Utils.checkNotNull(pageCursor, "pageCursor");
        this.pageCursor = Optional.ofNullable(pageCursor);
        return this;
    }


    /**
     * Pagination cursor from previous response
     */
    public ListAuditIssuesRequest withPageCursor(Optional<String> pageCursor) {
        Utils.checkNotNull(pageCursor, "pageCursor");
        this.pageCursor = pageCursor;
        return this;
    }

    /**
     * Search term for filtering by issue title and description
     */
    public ListAuditIssuesRequest withSearch(String search) {
        Utils.checkNotNull(search, "search");
        this.search = Optional.ofNullable(search);
        return this;
    }


    /**
     * Search term for filtering by issue title and description
     */
    public ListAuditIssuesRequest withSearch(Optional<String> search) {
        Utils.checkNotNull(search, "search");
        this.search = search;
        return this;
    }

    /**
     * Filter issues to specific snapshots by snapshot ID
     */
    public ListAuditIssuesRequest withSnapshotIdMatchesAny(List<String> snapshotIdMatchesAny) {
        Utils.checkNotNull(snapshotIdMatchesAny, "snapshotIdMatchesAny");
        this.snapshotIdMatchesAny = Optional.ofNullable(snapshotIdMatchesAny);
        return this;
    }


    /**
     * Filter issues to specific snapshots by snapshot ID
     */
    public ListAuditIssuesRequest withSnapshotIdMatchesAny(Optional<? extends List<String>> snapshotIdMatchesAny) {
        Utils.checkNotNull(snapshotIdMatchesAny, "snapshotIdMatchesAny");
        this.snapshotIdMatchesAny = snapshotIdMatchesAny;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ListAuditIssuesRequest other = (ListAuditIssuesRequest) o;
        return 
            Utils.enhancedDeepEquals(this.auditId, other.auditId) &&
            Utils.enhancedDeepEquals(this.pageSize, other.pageSize) &&
            Utils.enhancedDeepEquals(this.pageCursor, other.pageCursor) &&
            Utils.enhancedDeepEquals(this.search, other.search) &&
            Utils.enhancedDeepEquals(this.snapshotIdMatchesAny, other.snapshotIdMatchesAny);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            auditId, pageSize, pageCursor,
            search, snapshotIdMatchesAny);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ListAuditIssuesRequest.class,
                "auditId", auditId,
                "pageSize", pageSize,
                "pageCursor", pageCursor,
                "search", search,
                "snapshotIdMatchesAny", snapshotIdMatchesAny);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String auditId;

        private Optional<Integer> pageSize;

        private Optional<String> pageCursor = Optional.empty();

        private Optional<String> search = Optional.empty();

        private Optional<? extends List<String>> snapshotIdMatchesAny = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * The audit ID
         */
        public Builder auditId(String auditId) {
            Utils.checkNotNull(auditId, "auditId");
            this.auditId = auditId;
            return this;
        }


        /**
         * Maximum number of results per page (1-100, default 10)
         */
        public Builder pageSize(int pageSize) {
            Utils.checkNotNull(pageSize, "pageSize");
            this.pageSize = Optional.ofNullable(pageSize);
            return this;
        }

        /**
         * Maximum number of results per page (1-100, default 10)
         */
        public Builder pageSize(Optional<Integer> pageSize) {
            Utils.checkNotNull(pageSize, "pageSize");
            this.pageSize = pageSize;
            return this;
        }


        /**
         * Pagination cursor from previous response
         */
        public Builder pageCursor(String pageCursor) {
            Utils.checkNotNull(pageCursor, "pageCursor");
            this.pageCursor = Optional.ofNullable(pageCursor);
            return this;
        }

        /**
         * Pagination cursor from previous response
         */
        public Builder pageCursor(Optional<String> pageCursor) {
            Utils.checkNotNull(pageCursor, "pageCursor");
            this.pageCursor = pageCursor;
            return this;
        }


        /**
         * Search term for filtering by issue title and description
         */
        public Builder search(String search) {
            Utils.checkNotNull(search, "search");
            this.search = Optional.ofNullable(search);
            return this;
        }

        /**
         * Search term for filtering by issue title and description
         */
        public Builder search(Optional<String> search) {
            Utils.checkNotNull(search, "search");
            this.search = search;
            return this;
        }


        /**
         * Filter issues to specific snapshots by snapshot ID
         */
        public Builder snapshotIdMatchesAny(List<String> snapshotIdMatchesAny) {
            Utils.checkNotNull(snapshotIdMatchesAny, "snapshotIdMatchesAny");
            this.snapshotIdMatchesAny = Optional.ofNullable(snapshotIdMatchesAny);
            return this;
        }

        /**
         * Filter issues to specific snapshots by snapshot ID
         */
        public Builder snapshotIdMatchesAny(Optional<? extends List<String>> snapshotIdMatchesAny) {
            Utils.checkNotNull(snapshotIdMatchesAny, "snapshotIdMatchesAny");
            this.snapshotIdMatchesAny = snapshotIdMatchesAny;
            return this;
        }

        public ListAuditIssuesRequest build() {
            if (pageSize == null) {
                pageSize = _SINGLETON_VALUE_PageSize.value();
            }

            return new ListAuditIssuesRequest(
                auditId, pageSize, pageCursor,
                search, snapshotIdMatchesAny);
        }


        private static final LazySingletonValue<Optional<Integer>> _SINGLETON_VALUE_PageSize =
                new LazySingletonValue<>(
                        "pageSize",
                        "10",
                        new TypeReference<Optional<Integer>>() {});
    }
}
