/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.vanta.vanta_auditor_api.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.vanta.vanta_auditor_api.models.components.PaginatedResponseAuditorApiVulnerability;
import com.vanta.vanta_auditor_api.utils.Response;
import com.vanta.vanta_auditor_api.utils.Utils;
import java.io.InputStream;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.net.http.HttpResponse;
import java.util.Optional;


public class ListVulnerabilitiesResponse implements Response {
    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<InputStream> rawResponse;

    /**
     * Ok
     */
    private Optional<? extends PaginatedResponseAuditorApiVulnerability> paginatedResponseAuditorApiVulnerability;

    @JsonCreator
    public ListVulnerabilitiesResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse,
            Optional<? extends PaginatedResponseAuditorApiVulnerability> paginatedResponseAuditorApiVulnerability) {
        Utils.checkNotNull(contentType, "contentType");
        Utils.checkNotNull(statusCode, "statusCode");
        Utils.checkNotNull(rawResponse, "rawResponse");
        Utils.checkNotNull(paginatedResponseAuditorApiVulnerability, "paginatedResponseAuditorApiVulnerability");
        this.contentType = contentType;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
        this.paginatedResponseAuditorApiVulnerability = paginatedResponseAuditorApiVulnerability;
    }
    
    public ListVulnerabilitiesResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse) {
        this(contentType, statusCode, rawResponse,
            Optional.empty());
    }

    /**
     * HTTP response content type for this operation
     */
    @JsonIgnore
    public String contentType() {
        return contentType;
    }

    /**
     * HTTP response status code for this operation
     */
    @JsonIgnore
    public int statusCode() {
        return statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @JsonIgnore
    public HttpResponse<InputStream> rawResponse() {
        return rawResponse;
    }

    /**
     * Ok
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<PaginatedResponseAuditorApiVulnerability> paginatedResponseAuditorApiVulnerability() {
        return (Optional<PaginatedResponseAuditorApiVulnerability>) paginatedResponseAuditorApiVulnerability;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * HTTP response content type for this operation
     */
    public ListVulnerabilitiesResponse withContentType(String contentType) {
        Utils.checkNotNull(contentType, "contentType");
        this.contentType = contentType;
        return this;
    }

    /**
     * HTTP response status code for this operation
     */
    public ListVulnerabilitiesResponse withStatusCode(int statusCode) {
        Utils.checkNotNull(statusCode, "statusCode");
        this.statusCode = statusCode;
        return this;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public ListVulnerabilitiesResponse withRawResponse(HttpResponse<InputStream> rawResponse) {
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.rawResponse = rawResponse;
        return this;
    }

    /**
     * Ok
     */
    public ListVulnerabilitiesResponse withPaginatedResponseAuditorApiVulnerability(PaginatedResponseAuditorApiVulnerability paginatedResponseAuditorApiVulnerability) {
        Utils.checkNotNull(paginatedResponseAuditorApiVulnerability, "paginatedResponseAuditorApiVulnerability");
        this.paginatedResponseAuditorApiVulnerability = Optional.ofNullable(paginatedResponseAuditorApiVulnerability);
        return this;
    }


    /**
     * Ok
     */
    public ListVulnerabilitiesResponse withPaginatedResponseAuditorApiVulnerability(Optional<? extends PaginatedResponseAuditorApiVulnerability> paginatedResponseAuditorApiVulnerability) {
        Utils.checkNotNull(paginatedResponseAuditorApiVulnerability, "paginatedResponseAuditorApiVulnerability");
        this.paginatedResponseAuditorApiVulnerability = paginatedResponseAuditorApiVulnerability;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ListVulnerabilitiesResponse other = (ListVulnerabilitiesResponse) o;
        return 
            Utils.enhancedDeepEquals(this.contentType, other.contentType) &&
            Utils.enhancedDeepEquals(this.statusCode, other.statusCode) &&
            Utils.enhancedDeepEquals(this.rawResponse, other.rawResponse) &&
            Utils.enhancedDeepEquals(this.paginatedResponseAuditorApiVulnerability, other.paginatedResponseAuditorApiVulnerability);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            contentType, statusCode, rawResponse,
            paginatedResponseAuditorApiVulnerability);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ListVulnerabilitiesResponse.class,
                "contentType", contentType,
                "statusCode", statusCode,
                "rawResponse", rawResponse,
                "paginatedResponseAuditorApiVulnerability", paginatedResponseAuditorApiVulnerability);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String contentType;

        private Integer statusCode;

        private HttpResponse<InputStream> rawResponse;

        private Optional<? extends PaginatedResponseAuditorApiVulnerability> paginatedResponseAuditorApiVulnerability = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(String contentType) {
            Utils.checkNotNull(contentType, "contentType");
            this.contentType = contentType;
            return this;
        }


        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            Utils.checkNotNull(statusCode, "statusCode");
            this.statusCode = statusCode;
            return this;
        }


        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(HttpResponse<InputStream> rawResponse) {
            Utils.checkNotNull(rawResponse, "rawResponse");
            this.rawResponse = rawResponse;
            return this;
        }


        /**
         * Ok
         */
        public Builder paginatedResponseAuditorApiVulnerability(PaginatedResponseAuditorApiVulnerability paginatedResponseAuditorApiVulnerability) {
            Utils.checkNotNull(paginatedResponseAuditorApiVulnerability, "paginatedResponseAuditorApiVulnerability");
            this.paginatedResponseAuditorApiVulnerability = Optional.ofNullable(paginatedResponseAuditorApiVulnerability);
            return this;
        }

        /**
         * Ok
         */
        public Builder paginatedResponseAuditorApiVulnerability(Optional<? extends PaginatedResponseAuditorApiVulnerability> paginatedResponseAuditorApiVulnerability) {
            Utils.checkNotNull(paginatedResponseAuditorApiVulnerability, "paginatedResponseAuditorApiVulnerability");
            this.paginatedResponseAuditorApiVulnerability = paginatedResponseAuditorApiVulnerability;
            return this;
        }

        public ListVulnerabilitiesResponse build() {

            return new ListVulnerabilitiesResponse(
                contentType, statusCode, rawResponse,
                paginatedResponseAuditorApiVulnerability);
        }

    }
}
