/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.vanta.vanta_auditor_api.models.operations;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.vanta.vanta_auditor_api.models.components.PaginatedResponseEvidence;
import com.vanta.vanta_auditor_api.utils.Response;
import com.vanta.vanta_auditor_api.utils.Utils;
import java.io.InputStream;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.net.http.HttpResponse;
import java.util.Objects;
import java.util.Optional;


public class ListAuditEvidenceResponse implements Response {

    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<InputStream> rawResponse;

    /**
     * Ok
     */
    private Optional<? extends PaginatedResponseEvidence> paginatedResponseEvidence;

    @JsonCreator
    public ListAuditEvidenceResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse,
            Optional<? extends PaginatedResponseEvidence> paginatedResponseEvidence) {
        Utils.checkNotNull(contentType, "contentType");
        Utils.checkNotNull(statusCode, "statusCode");
        Utils.checkNotNull(rawResponse, "rawResponse");
        Utils.checkNotNull(paginatedResponseEvidence, "paginatedResponseEvidence");
        this.contentType = contentType;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
        this.paginatedResponseEvidence = paginatedResponseEvidence;
    }
    
    public ListAuditEvidenceResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse) {
        this(contentType, statusCode, rawResponse, Optional.empty());
    }

    /**
     * HTTP response content type for this operation
     */
    @JsonIgnore
    public String contentType() {
        return contentType;
    }

    /**
     * HTTP response status code for this operation
     */
    @JsonIgnore
    public int statusCode() {
        return statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @JsonIgnore
    public HttpResponse<InputStream> rawResponse() {
        return rawResponse;
    }

    /**
     * Ok
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<PaginatedResponseEvidence> paginatedResponseEvidence() {
        return (Optional<PaginatedResponseEvidence>) paginatedResponseEvidence;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * HTTP response content type for this operation
     */
    public ListAuditEvidenceResponse withContentType(String contentType) {
        Utils.checkNotNull(contentType, "contentType");
        this.contentType = contentType;
        return this;
    }

    /**
     * HTTP response status code for this operation
     */
    public ListAuditEvidenceResponse withStatusCode(int statusCode) {
        Utils.checkNotNull(statusCode, "statusCode");
        this.statusCode = statusCode;
        return this;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public ListAuditEvidenceResponse withRawResponse(HttpResponse<InputStream> rawResponse) {
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.rawResponse = rawResponse;
        return this;
    }

    /**
     * Ok
     */
    public ListAuditEvidenceResponse withPaginatedResponseEvidence(PaginatedResponseEvidence paginatedResponseEvidence) {
        Utils.checkNotNull(paginatedResponseEvidence, "paginatedResponseEvidence");
        this.paginatedResponseEvidence = Optional.ofNullable(paginatedResponseEvidence);
        return this;
    }

    /**
     * Ok
     */
    public ListAuditEvidenceResponse withPaginatedResponseEvidence(Optional<? extends PaginatedResponseEvidence> paginatedResponseEvidence) {
        Utils.checkNotNull(paginatedResponseEvidence, "paginatedResponseEvidence");
        this.paginatedResponseEvidence = paginatedResponseEvidence;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ListAuditEvidenceResponse other = (ListAuditEvidenceResponse) o;
        return 
            Objects.deepEquals(this.contentType, other.contentType) &&
            Objects.deepEquals(this.statusCode, other.statusCode) &&
            Objects.deepEquals(this.rawResponse, other.rawResponse) &&
            Objects.deepEquals(this.paginatedResponseEvidence, other.paginatedResponseEvidence);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            contentType,
            statusCode,
            rawResponse,
            paginatedResponseEvidence);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ListAuditEvidenceResponse.class,
                "contentType", contentType,
                "statusCode", statusCode,
                "rawResponse", rawResponse,
                "paginatedResponseEvidence", paginatedResponseEvidence);
    }
    
    public final static class Builder {
 
        private String contentType;
 
        private Integer statusCode;
 
        private HttpResponse<InputStream> rawResponse;
 
        private Optional<? extends PaginatedResponseEvidence> paginatedResponseEvidence = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(String contentType) {
            Utils.checkNotNull(contentType, "contentType");
            this.contentType = contentType;
            return this;
        }

        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            Utils.checkNotNull(statusCode, "statusCode");
            this.statusCode = statusCode;
            return this;
        }

        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(HttpResponse<InputStream> rawResponse) {
            Utils.checkNotNull(rawResponse, "rawResponse");
            this.rawResponse = rawResponse;
            return this;
        }

        /**
         * Ok
         */
        public Builder paginatedResponseEvidence(PaginatedResponseEvidence paginatedResponseEvidence) {
            Utils.checkNotNull(paginatedResponseEvidence, "paginatedResponseEvidence");
            this.paginatedResponseEvidence = Optional.ofNullable(paginatedResponseEvidence);
            return this;
        }

        /**
         * Ok
         */
        public Builder paginatedResponseEvidence(Optional<? extends PaginatedResponseEvidence> paginatedResponseEvidence) {
            Utils.checkNotNull(paginatedResponseEvidence, "paginatedResponseEvidence");
            this.paginatedResponseEvidence = paginatedResponseEvidence;
            return this;
        }
        
        public ListAuditEvidenceResponse build() {
            return new ListAuditEvidenceResponse(
                contentType,
                statusCode,
                rawResponse,
                paginatedResponseEvidence);
        }
    }
}

