/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.vanta.vanta_auditor_api.models.operations;

import com.fasterxml.jackson.core.type.TypeReference;
import com.vanta.vanta_auditor_api.utils.LazySingletonValue;
import com.vanta.vanta_auditor_api.utils.Utils;
import java.lang.Exception;
import java.lang.Integer;
import java.lang.String;
import java.util.Optional;

public class ListAuditEvidenceUrlsRequestBuilder {

    private String auditId;
    private String auditEvidenceId;
    private Optional<Integer> pageSize = Utils.readDefaultOrConstValue(
                            "pageSize",
                            "10",
                            new TypeReference<Optional<Integer>>() {});
    private Optional<String> pageCursor = Optional.empty();
    private final SDKMethodInterfaces.MethodCallListAuditEvidenceUrls sdk;

    public ListAuditEvidenceUrlsRequestBuilder(SDKMethodInterfaces.MethodCallListAuditEvidenceUrls sdk) {
        this.sdk = sdk;
    }

    public ListAuditEvidenceUrlsRequestBuilder auditId(String auditId) {
        Utils.checkNotNull(auditId, "auditId");
        this.auditId = auditId;
        return this;
    }

    public ListAuditEvidenceUrlsRequestBuilder auditEvidenceId(String auditEvidenceId) {
        Utils.checkNotNull(auditEvidenceId, "auditEvidenceId");
        this.auditEvidenceId = auditEvidenceId;
        return this;
    }
                
    public ListAuditEvidenceUrlsRequestBuilder pageSize(int pageSize) {
        Utils.checkNotNull(pageSize, "pageSize");
        this.pageSize = Optional.of(pageSize);
        return this;
    }

    public ListAuditEvidenceUrlsRequestBuilder pageSize(Optional<Integer> pageSize) {
        Utils.checkNotNull(pageSize, "pageSize");
        this.pageSize = pageSize;
        return this;
    }
                
    public ListAuditEvidenceUrlsRequestBuilder pageCursor(String pageCursor) {
        Utils.checkNotNull(pageCursor, "pageCursor");
        this.pageCursor = Optional.of(pageCursor);
        return this;
    }

    public ListAuditEvidenceUrlsRequestBuilder pageCursor(Optional<String> pageCursor) {
        Utils.checkNotNull(pageCursor, "pageCursor");
        this.pageCursor = pageCursor;
        return this;
    }

    public ListAuditEvidenceUrlsResponse call() throws Exception {
        if (pageSize == null) {
            pageSize = _SINGLETON_VALUE_PageSize.value();
        }
        return sdk.getEvidenceUrls(
            auditId,
            auditEvidenceId,
            pageSize,
            pageCursor);
    }

    private static final LazySingletonValue<Optional<Integer>> _SINGLETON_VALUE_PageSize =
            new LazySingletonValue<>(
                    "pageSize",
                    "10",
                    new TypeReference<Optional<Integer>>() {});
}
