/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.vanta.vanta_auditor_api.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.core.type.TypeReference;
import com.vanta.vanta_auditor_api.models.components.GroupOrderBy;
import com.vanta.vanta_auditor_api.models.components.OrderDirection;
import com.vanta.vanta_auditor_api.utils.LazySingletonValue;
import com.vanta.vanta_auditor_api.utils.SpeakeasyMetadata;
import com.vanta.vanta_auditor_api.utils.Utils;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.List;
import java.util.Optional;


public class ListPersonnelGroupsRequest {
    /**
     * The audit ID
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=auditId")
    private String auditId;

    /**
     * Maximum number of results per page (1-100, default 10)
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=pageSize")
    private Optional<Integer> pageSize;

    /**
     * Pagination cursor from previous response
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=pageCursor")
    private Optional<String> pageCursor;

    /**
     * Search term for filtering by group name
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=search")
    private Optional<String> search;

    /**
     * Filter groups by IDP source service names
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=sourcesMatchesAny")
    private Optional<? extends List<String>> sourcesMatchesAny;

    /**
     * Field to sort results by. Allowed: "name", "members", "source", "tasksLastUpdated",
     * "pointOfContact". Default: "name"
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=orderBy")
    private Optional<? extends GroupOrderBy> orderBy;

    /**
     * Sort direction: "asc" or "desc". Default: "asc"
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=orderDirection")
    private Optional<? extends OrderDirection> orderDirection;

    @JsonCreator
    public ListPersonnelGroupsRequest(
            String auditId,
            Optional<Integer> pageSize,
            Optional<String> pageCursor,
            Optional<String> search,
            Optional<? extends List<String>> sourcesMatchesAny,
            Optional<? extends GroupOrderBy> orderBy,
            Optional<? extends OrderDirection> orderDirection) {
        Utils.checkNotNull(auditId, "auditId");
        Utils.checkNotNull(pageSize, "pageSize");
        Utils.checkNotNull(pageCursor, "pageCursor");
        Utils.checkNotNull(search, "search");
        Utils.checkNotNull(sourcesMatchesAny, "sourcesMatchesAny");
        Utils.checkNotNull(orderBy, "orderBy");
        Utils.checkNotNull(orderDirection, "orderDirection");
        this.auditId = auditId;
        this.pageSize = pageSize;
        this.pageCursor = pageCursor;
        this.search = search;
        this.sourcesMatchesAny = sourcesMatchesAny;
        this.orderBy = orderBy;
        this.orderDirection = orderDirection;
    }
    
    public ListPersonnelGroupsRequest(
            String auditId) {
        this(auditId, Optional.empty(), Optional.empty(),
            Optional.empty(), Optional.empty(), Optional.empty(),
            Optional.empty());
    }

    /**
     * The audit ID
     */
    @JsonIgnore
    public String auditId() {
        return auditId;
    }

    /**
     * Maximum number of results per page (1-100, default 10)
     */
    @JsonIgnore
    public Optional<Integer> pageSize() {
        return pageSize;
    }

    /**
     * Pagination cursor from previous response
     */
    @JsonIgnore
    public Optional<String> pageCursor() {
        return pageCursor;
    }

    /**
     * Search term for filtering by group name
     */
    @JsonIgnore
    public Optional<String> search() {
        return search;
    }

    /**
     * Filter groups by IDP source service names
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<List<String>> sourcesMatchesAny() {
        return (Optional<List<String>>) sourcesMatchesAny;
    }

    /**
     * Field to sort results by. Allowed: "name", "members", "source", "tasksLastUpdated",
     * "pointOfContact". Default: "name"
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<GroupOrderBy> orderBy() {
        return (Optional<GroupOrderBy>) orderBy;
    }

    /**
     * Sort direction: "asc" or "desc". Default: "asc"
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<OrderDirection> orderDirection() {
        return (Optional<OrderDirection>) orderDirection;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The audit ID
     */
    public ListPersonnelGroupsRequest withAuditId(String auditId) {
        Utils.checkNotNull(auditId, "auditId");
        this.auditId = auditId;
        return this;
    }

    /**
     * Maximum number of results per page (1-100, default 10)
     */
    public ListPersonnelGroupsRequest withPageSize(int pageSize) {
        Utils.checkNotNull(pageSize, "pageSize");
        this.pageSize = Optional.ofNullable(pageSize);
        return this;
    }


    /**
     * Maximum number of results per page (1-100, default 10)
     */
    public ListPersonnelGroupsRequest withPageSize(Optional<Integer> pageSize) {
        Utils.checkNotNull(pageSize, "pageSize");
        this.pageSize = pageSize;
        return this;
    }

    /**
     * Pagination cursor from previous response
     */
    public ListPersonnelGroupsRequest withPageCursor(String pageCursor) {
        Utils.checkNotNull(pageCursor, "pageCursor");
        this.pageCursor = Optional.ofNullable(pageCursor);
        return this;
    }


    /**
     * Pagination cursor from previous response
     */
    public ListPersonnelGroupsRequest withPageCursor(Optional<String> pageCursor) {
        Utils.checkNotNull(pageCursor, "pageCursor");
        this.pageCursor = pageCursor;
        return this;
    }

    /**
     * Search term for filtering by group name
     */
    public ListPersonnelGroupsRequest withSearch(String search) {
        Utils.checkNotNull(search, "search");
        this.search = Optional.ofNullable(search);
        return this;
    }


    /**
     * Search term for filtering by group name
     */
    public ListPersonnelGroupsRequest withSearch(Optional<String> search) {
        Utils.checkNotNull(search, "search");
        this.search = search;
        return this;
    }

    /**
     * Filter groups by IDP source service names
     */
    public ListPersonnelGroupsRequest withSourcesMatchesAny(List<String> sourcesMatchesAny) {
        Utils.checkNotNull(sourcesMatchesAny, "sourcesMatchesAny");
        this.sourcesMatchesAny = Optional.ofNullable(sourcesMatchesAny);
        return this;
    }


    /**
     * Filter groups by IDP source service names
     */
    public ListPersonnelGroupsRequest withSourcesMatchesAny(Optional<? extends List<String>> sourcesMatchesAny) {
        Utils.checkNotNull(sourcesMatchesAny, "sourcesMatchesAny");
        this.sourcesMatchesAny = sourcesMatchesAny;
        return this;
    }

    /**
     * Field to sort results by. Allowed: "name", "members", "source", "tasksLastUpdated",
     * "pointOfContact". Default: "name"
     */
    public ListPersonnelGroupsRequest withOrderBy(GroupOrderBy orderBy) {
        Utils.checkNotNull(orderBy, "orderBy");
        this.orderBy = Optional.ofNullable(orderBy);
        return this;
    }


    /**
     * Field to sort results by. Allowed: "name", "members", "source", "tasksLastUpdated",
     * "pointOfContact". Default: "name"
     */
    public ListPersonnelGroupsRequest withOrderBy(Optional<? extends GroupOrderBy> orderBy) {
        Utils.checkNotNull(orderBy, "orderBy");
        this.orderBy = orderBy;
        return this;
    }

    /**
     * Sort direction: "asc" or "desc". Default: "asc"
     */
    public ListPersonnelGroupsRequest withOrderDirection(OrderDirection orderDirection) {
        Utils.checkNotNull(orderDirection, "orderDirection");
        this.orderDirection = Optional.ofNullable(orderDirection);
        return this;
    }


    /**
     * Sort direction: "asc" or "desc". Default: "asc"
     */
    public ListPersonnelGroupsRequest withOrderDirection(Optional<? extends OrderDirection> orderDirection) {
        Utils.checkNotNull(orderDirection, "orderDirection");
        this.orderDirection = orderDirection;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ListPersonnelGroupsRequest other = (ListPersonnelGroupsRequest) o;
        return 
            Utils.enhancedDeepEquals(this.auditId, other.auditId) &&
            Utils.enhancedDeepEquals(this.pageSize, other.pageSize) &&
            Utils.enhancedDeepEquals(this.pageCursor, other.pageCursor) &&
            Utils.enhancedDeepEquals(this.search, other.search) &&
            Utils.enhancedDeepEquals(this.sourcesMatchesAny, other.sourcesMatchesAny) &&
            Utils.enhancedDeepEquals(this.orderBy, other.orderBy) &&
            Utils.enhancedDeepEquals(this.orderDirection, other.orderDirection);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            auditId, pageSize, pageCursor,
            search, sourcesMatchesAny, orderBy,
            orderDirection);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ListPersonnelGroupsRequest.class,
                "auditId", auditId,
                "pageSize", pageSize,
                "pageCursor", pageCursor,
                "search", search,
                "sourcesMatchesAny", sourcesMatchesAny,
                "orderBy", orderBy,
                "orderDirection", orderDirection);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String auditId;

        private Optional<Integer> pageSize;

        private Optional<String> pageCursor = Optional.empty();

        private Optional<String> search = Optional.empty();

        private Optional<? extends List<String>> sourcesMatchesAny = Optional.empty();

        private Optional<? extends GroupOrderBy> orderBy = Optional.empty();

        private Optional<? extends OrderDirection> orderDirection = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * The audit ID
         */
        public Builder auditId(String auditId) {
            Utils.checkNotNull(auditId, "auditId");
            this.auditId = auditId;
            return this;
        }


        /**
         * Maximum number of results per page (1-100, default 10)
         */
        public Builder pageSize(int pageSize) {
            Utils.checkNotNull(pageSize, "pageSize");
            this.pageSize = Optional.ofNullable(pageSize);
            return this;
        }

        /**
         * Maximum number of results per page (1-100, default 10)
         */
        public Builder pageSize(Optional<Integer> pageSize) {
            Utils.checkNotNull(pageSize, "pageSize");
            this.pageSize = pageSize;
            return this;
        }


        /**
         * Pagination cursor from previous response
         */
        public Builder pageCursor(String pageCursor) {
            Utils.checkNotNull(pageCursor, "pageCursor");
            this.pageCursor = Optional.ofNullable(pageCursor);
            return this;
        }

        /**
         * Pagination cursor from previous response
         */
        public Builder pageCursor(Optional<String> pageCursor) {
            Utils.checkNotNull(pageCursor, "pageCursor");
            this.pageCursor = pageCursor;
            return this;
        }


        /**
         * Search term for filtering by group name
         */
        public Builder search(String search) {
            Utils.checkNotNull(search, "search");
            this.search = Optional.ofNullable(search);
            return this;
        }

        /**
         * Search term for filtering by group name
         */
        public Builder search(Optional<String> search) {
            Utils.checkNotNull(search, "search");
            this.search = search;
            return this;
        }


        /**
         * Filter groups by IDP source service names
         */
        public Builder sourcesMatchesAny(List<String> sourcesMatchesAny) {
            Utils.checkNotNull(sourcesMatchesAny, "sourcesMatchesAny");
            this.sourcesMatchesAny = Optional.ofNullable(sourcesMatchesAny);
            return this;
        }

        /**
         * Filter groups by IDP source service names
         */
        public Builder sourcesMatchesAny(Optional<? extends List<String>> sourcesMatchesAny) {
            Utils.checkNotNull(sourcesMatchesAny, "sourcesMatchesAny");
            this.sourcesMatchesAny = sourcesMatchesAny;
            return this;
        }


        /**
         * Field to sort results by. Allowed: "name", "members", "source", "tasksLastUpdated",
         * "pointOfContact". Default: "name"
         */
        public Builder orderBy(GroupOrderBy orderBy) {
            Utils.checkNotNull(orderBy, "orderBy");
            this.orderBy = Optional.ofNullable(orderBy);
            return this;
        }

        /**
         * Field to sort results by. Allowed: "name", "members", "source", "tasksLastUpdated",
         * "pointOfContact". Default: "name"
         */
        public Builder orderBy(Optional<? extends GroupOrderBy> orderBy) {
            Utils.checkNotNull(orderBy, "orderBy");
            this.orderBy = orderBy;
            return this;
        }


        /**
         * Sort direction: "asc" or "desc". Default: "asc"
         */
        public Builder orderDirection(OrderDirection orderDirection) {
            Utils.checkNotNull(orderDirection, "orderDirection");
            this.orderDirection = Optional.ofNullable(orderDirection);
            return this;
        }

        /**
         * Sort direction: "asc" or "desc". Default: "asc"
         */
        public Builder orderDirection(Optional<? extends OrderDirection> orderDirection) {
            Utils.checkNotNull(orderDirection, "orderDirection");
            this.orderDirection = orderDirection;
            return this;
        }

        public ListPersonnelGroupsRequest build() {
            if (pageSize == null) {
                pageSize = _SINGLETON_VALUE_PageSize.value();
            }

            return new ListPersonnelGroupsRequest(
                auditId, pageSize, pageCursor,
                search, sourcesMatchesAny, orderBy,
                orderDirection);
        }


        private static final LazySingletonValue<Optional<Integer>> _SINGLETON_VALUE_PageSize =
                new LazySingletonValue<>(
                        "pageSize",
                        "10",
                        new TypeReference<Optional<Integer>>() {});
    }
}
