/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.vanta.vanta_auditor_api.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.core.type.TypeReference;
import com.vanta.vanta_auditor_api.models.components.ExternalFindingSeverity;
import com.vanta.vanta_auditor_api.utils.LazySingletonValue;
import com.vanta.vanta_auditor_api.utils.SpeakeasyMetadata;
import com.vanta.vanta_auditor_api.utils.Utils;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.time.OffsetDateTime;
import java.util.Optional;


public class ListVulnerabilitiesRequest {

    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=auditId")
    private String auditId;

    /**
     * Filter vulnerabilities by search query
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=query")
    private Optional<String> query;


    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=pageSize")
    private Optional<Integer> pageSize;


    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=pageCursor")
    private Optional<String> pageCursor;

    /**
     * Filter vulnerabilities by deactivation status.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=isDeactivated")
    private Optional<Boolean> isDeactivated;

    /**
     * Filter vulnerabilities based on a specific external ID.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=externalVulnerabilityId")
    private Optional<String> externalVulnerabilityId;

    /**
     * Filter vulnerabilities that have an available fix.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=isFixAvailable")
    private Optional<Boolean> isFixAvailable;

    /**
     * Filter vulnerabilities that are from a specific package.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=packageIdentifier")
    private Optional<String> packageIdentifier;

    /**
     * Filter vulnerabilities with a fix due after a specific timestamp
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=slaDeadlineAfterDate")
    private Optional<OffsetDateTime> slaDeadlineAfterDate;

    /**
     * Filter vulnerabilities with a fix due before a specific timestamp
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=slaDeadlineBeforeDate")
    private Optional<OffsetDateTime> slaDeadlineBeforeDate;

    /**
     * Filter vulnerabilities by severity.
     * Possible values: CRITICAL, HIGH, MEDIUM, LOW.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=severity")
    private Optional<? extends ExternalFindingSeverity> severity;

    /**
     * Filter vulnerabilities by the vulnerability scanner that detected them.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=integrationId")
    private Optional<String> integrationId;

    /**
     * Filter vulnerabilities without an SLA due date.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=includeVulnerabilitiesWithoutSlas")
    private Optional<Boolean> includeVulnerabilitiesWithoutSlas;

    /**
     * Filter vulnerabilities by a specific asset ID.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=vulnerableAssetId")
    private Optional<String> vulnerableAssetId;

    @JsonCreator
    public ListVulnerabilitiesRequest(
            String auditId,
            Optional<String> query,
            Optional<Integer> pageSize,
            Optional<String> pageCursor,
            Optional<Boolean> isDeactivated,
            Optional<String> externalVulnerabilityId,
            Optional<Boolean> isFixAvailable,
            Optional<String> packageIdentifier,
            Optional<OffsetDateTime> slaDeadlineAfterDate,
            Optional<OffsetDateTime> slaDeadlineBeforeDate,
            Optional<? extends ExternalFindingSeverity> severity,
            Optional<String> integrationId,
            Optional<Boolean> includeVulnerabilitiesWithoutSlas,
            Optional<String> vulnerableAssetId) {
        Utils.checkNotNull(auditId, "auditId");
        Utils.checkNotNull(query, "query");
        Utils.checkNotNull(pageSize, "pageSize");
        Utils.checkNotNull(pageCursor, "pageCursor");
        Utils.checkNotNull(isDeactivated, "isDeactivated");
        Utils.checkNotNull(externalVulnerabilityId, "externalVulnerabilityId");
        Utils.checkNotNull(isFixAvailable, "isFixAvailable");
        Utils.checkNotNull(packageIdentifier, "packageIdentifier");
        Utils.checkNotNull(slaDeadlineAfterDate, "slaDeadlineAfterDate");
        Utils.checkNotNull(slaDeadlineBeforeDate, "slaDeadlineBeforeDate");
        Utils.checkNotNull(severity, "severity");
        Utils.checkNotNull(integrationId, "integrationId");
        Utils.checkNotNull(includeVulnerabilitiesWithoutSlas, "includeVulnerabilitiesWithoutSlas");
        Utils.checkNotNull(vulnerableAssetId, "vulnerableAssetId");
        this.auditId = auditId;
        this.query = query;
        this.pageSize = pageSize;
        this.pageCursor = pageCursor;
        this.isDeactivated = isDeactivated;
        this.externalVulnerabilityId = externalVulnerabilityId;
        this.isFixAvailable = isFixAvailable;
        this.packageIdentifier = packageIdentifier;
        this.slaDeadlineAfterDate = slaDeadlineAfterDate;
        this.slaDeadlineBeforeDate = slaDeadlineBeforeDate;
        this.severity = severity;
        this.integrationId = integrationId;
        this.includeVulnerabilitiesWithoutSlas = includeVulnerabilitiesWithoutSlas;
        this.vulnerableAssetId = vulnerableAssetId;
    }
    
    public ListVulnerabilitiesRequest(
            String auditId) {
        this(auditId, Optional.empty(), Optional.empty(),
            Optional.empty(), Optional.empty(), Optional.empty(),
            Optional.empty(), Optional.empty(), Optional.empty(),
            Optional.empty(), Optional.empty(), Optional.empty(),
            Optional.empty(), Optional.empty());
    }

    @JsonIgnore
    public String auditId() {
        return auditId;
    }

    /**
     * Filter vulnerabilities by search query
     */
    @JsonIgnore
    public Optional<String> query() {
        return query;
    }

    @JsonIgnore
    public Optional<Integer> pageSize() {
        return pageSize;
    }

    @JsonIgnore
    public Optional<String> pageCursor() {
        return pageCursor;
    }

    /**
     * Filter vulnerabilities by deactivation status.
     */
    @JsonIgnore
    public Optional<Boolean> isDeactivated() {
        return isDeactivated;
    }

    /**
     * Filter vulnerabilities based on a specific external ID.
     */
    @JsonIgnore
    public Optional<String> externalVulnerabilityId() {
        return externalVulnerabilityId;
    }

    /**
     * Filter vulnerabilities that have an available fix.
     */
    @JsonIgnore
    public Optional<Boolean> isFixAvailable() {
        return isFixAvailable;
    }

    /**
     * Filter vulnerabilities that are from a specific package.
     */
    @JsonIgnore
    public Optional<String> packageIdentifier() {
        return packageIdentifier;
    }

    /**
     * Filter vulnerabilities with a fix due after a specific timestamp
     */
    @JsonIgnore
    public Optional<OffsetDateTime> slaDeadlineAfterDate() {
        return slaDeadlineAfterDate;
    }

    /**
     * Filter vulnerabilities with a fix due before a specific timestamp
     */
    @JsonIgnore
    public Optional<OffsetDateTime> slaDeadlineBeforeDate() {
        return slaDeadlineBeforeDate;
    }

    /**
     * Filter vulnerabilities by severity.
     * Possible values: CRITICAL, HIGH, MEDIUM, LOW.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<ExternalFindingSeverity> severity() {
        return (Optional<ExternalFindingSeverity>) severity;
    }

    /**
     * Filter vulnerabilities by the vulnerability scanner that detected them.
     */
    @JsonIgnore
    public Optional<String> integrationId() {
        return integrationId;
    }

    /**
     * Filter vulnerabilities without an SLA due date.
     */
    @JsonIgnore
    public Optional<Boolean> includeVulnerabilitiesWithoutSlas() {
        return includeVulnerabilitiesWithoutSlas;
    }

    /**
     * Filter vulnerabilities by a specific asset ID.
     */
    @JsonIgnore
    public Optional<String> vulnerableAssetId() {
        return vulnerableAssetId;
    }

    public static Builder builder() {
        return new Builder();
    }


    public ListVulnerabilitiesRequest withAuditId(String auditId) {
        Utils.checkNotNull(auditId, "auditId");
        this.auditId = auditId;
        return this;
    }

    /**
     * Filter vulnerabilities by search query
     */
    public ListVulnerabilitiesRequest withQuery(String query) {
        Utils.checkNotNull(query, "query");
        this.query = Optional.ofNullable(query);
        return this;
    }


    /**
     * Filter vulnerabilities by search query
     */
    public ListVulnerabilitiesRequest withQuery(Optional<String> query) {
        Utils.checkNotNull(query, "query");
        this.query = query;
        return this;
    }

    public ListVulnerabilitiesRequest withPageSize(int pageSize) {
        Utils.checkNotNull(pageSize, "pageSize");
        this.pageSize = Optional.ofNullable(pageSize);
        return this;
    }


    public ListVulnerabilitiesRequest withPageSize(Optional<Integer> pageSize) {
        Utils.checkNotNull(pageSize, "pageSize");
        this.pageSize = pageSize;
        return this;
    }

    public ListVulnerabilitiesRequest withPageCursor(String pageCursor) {
        Utils.checkNotNull(pageCursor, "pageCursor");
        this.pageCursor = Optional.ofNullable(pageCursor);
        return this;
    }


    public ListVulnerabilitiesRequest withPageCursor(Optional<String> pageCursor) {
        Utils.checkNotNull(pageCursor, "pageCursor");
        this.pageCursor = pageCursor;
        return this;
    }

    /**
     * Filter vulnerabilities by deactivation status.
     */
    public ListVulnerabilitiesRequest withIsDeactivated(boolean isDeactivated) {
        Utils.checkNotNull(isDeactivated, "isDeactivated");
        this.isDeactivated = Optional.ofNullable(isDeactivated);
        return this;
    }


    /**
     * Filter vulnerabilities by deactivation status.
     */
    public ListVulnerabilitiesRequest withIsDeactivated(Optional<Boolean> isDeactivated) {
        Utils.checkNotNull(isDeactivated, "isDeactivated");
        this.isDeactivated = isDeactivated;
        return this;
    }

    /**
     * Filter vulnerabilities based on a specific external ID.
     */
    public ListVulnerabilitiesRequest withExternalVulnerabilityId(String externalVulnerabilityId) {
        Utils.checkNotNull(externalVulnerabilityId, "externalVulnerabilityId");
        this.externalVulnerabilityId = Optional.ofNullable(externalVulnerabilityId);
        return this;
    }


    /**
     * Filter vulnerabilities based on a specific external ID.
     */
    public ListVulnerabilitiesRequest withExternalVulnerabilityId(Optional<String> externalVulnerabilityId) {
        Utils.checkNotNull(externalVulnerabilityId, "externalVulnerabilityId");
        this.externalVulnerabilityId = externalVulnerabilityId;
        return this;
    }

    /**
     * Filter vulnerabilities that have an available fix.
     */
    public ListVulnerabilitiesRequest withIsFixAvailable(boolean isFixAvailable) {
        Utils.checkNotNull(isFixAvailable, "isFixAvailable");
        this.isFixAvailable = Optional.ofNullable(isFixAvailable);
        return this;
    }


    /**
     * Filter vulnerabilities that have an available fix.
     */
    public ListVulnerabilitiesRequest withIsFixAvailable(Optional<Boolean> isFixAvailable) {
        Utils.checkNotNull(isFixAvailable, "isFixAvailable");
        this.isFixAvailable = isFixAvailable;
        return this;
    }

    /**
     * Filter vulnerabilities that are from a specific package.
     */
    public ListVulnerabilitiesRequest withPackageIdentifier(String packageIdentifier) {
        Utils.checkNotNull(packageIdentifier, "packageIdentifier");
        this.packageIdentifier = Optional.ofNullable(packageIdentifier);
        return this;
    }


    /**
     * Filter vulnerabilities that are from a specific package.
     */
    public ListVulnerabilitiesRequest withPackageIdentifier(Optional<String> packageIdentifier) {
        Utils.checkNotNull(packageIdentifier, "packageIdentifier");
        this.packageIdentifier = packageIdentifier;
        return this;
    }

    /**
     * Filter vulnerabilities with a fix due after a specific timestamp
     */
    public ListVulnerabilitiesRequest withSlaDeadlineAfterDate(OffsetDateTime slaDeadlineAfterDate) {
        Utils.checkNotNull(slaDeadlineAfterDate, "slaDeadlineAfterDate");
        this.slaDeadlineAfterDate = Optional.ofNullable(slaDeadlineAfterDate);
        return this;
    }


    /**
     * Filter vulnerabilities with a fix due after a specific timestamp
     */
    public ListVulnerabilitiesRequest withSlaDeadlineAfterDate(Optional<OffsetDateTime> slaDeadlineAfterDate) {
        Utils.checkNotNull(slaDeadlineAfterDate, "slaDeadlineAfterDate");
        this.slaDeadlineAfterDate = slaDeadlineAfterDate;
        return this;
    }

    /**
     * Filter vulnerabilities with a fix due before a specific timestamp
     */
    public ListVulnerabilitiesRequest withSlaDeadlineBeforeDate(OffsetDateTime slaDeadlineBeforeDate) {
        Utils.checkNotNull(slaDeadlineBeforeDate, "slaDeadlineBeforeDate");
        this.slaDeadlineBeforeDate = Optional.ofNullable(slaDeadlineBeforeDate);
        return this;
    }


    /**
     * Filter vulnerabilities with a fix due before a specific timestamp
     */
    public ListVulnerabilitiesRequest withSlaDeadlineBeforeDate(Optional<OffsetDateTime> slaDeadlineBeforeDate) {
        Utils.checkNotNull(slaDeadlineBeforeDate, "slaDeadlineBeforeDate");
        this.slaDeadlineBeforeDate = slaDeadlineBeforeDate;
        return this;
    }

    /**
     * Filter vulnerabilities by severity.
     * Possible values: CRITICAL, HIGH, MEDIUM, LOW.
     */
    public ListVulnerabilitiesRequest withSeverity(ExternalFindingSeverity severity) {
        Utils.checkNotNull(severity, "severity");
        this.severity = Optional.ofNullable(severity);
        return this;
    }


    /**
     * Filter vulnerabilities by severity.
     * Possible values: CRITICAL, HIGH, MEDIUM, LOW.
     */
    public ListVulnerabilitiesRequest withSeverity(Optional<? extends ExternalFindingSeverity> severity) {
        Utils.checkNotNull(severity, "severity");
        this.severity = severity;
        return this;
    }

    /**
     * Filter vulnerabilities by the vulnerability scanner that detected them.
     */
    public ListVulnerabilitiesRequest withIntegrationId(String integrationId) {
        Utils.checkNotNull(integrationId, "integrationId");
        this.integrationId = Optional.ofNullable(integrationId);
        return this;
    }


    /**
     * Filter vulnerabilities by the vulnerability scanner that detected them.
     */
    public ListVulnerabilitiesRequest withIntegrationId(Optional<String> integrationId) {
        Utils.checkNotNull(integrationId, "integrationId");
        this.integrationId = integrationId;
        return this;
    }

    /**
     * Filter vulnerabilities without an SLA due date.
     */
    public ListVulnerabilitiesRequest withIncludeVulnerabilitiesWithoutSlas(boolean includeVulnerabilitiesWithoutSlas) {
        Utils.checkNotNull(includeVulnerabilitiesWithoutSlas, "includeVulnerabilitiesWithoutSlas");
        this.includeVulnerabilitiesWithoutSlas = Optional.ofNullable(includeVulnerabilitiesWithoutSlas);
        return this;
    }


    /**
     * Filter vulnerabilities without an SLA due date.
     */
    public ListVulnerabilitiesRequest withIncludeVulnerabilitiesWithoutSlas(Optional<Boolean> includeVulnerabilitiesWithoutSlas) {
        Utils.checkNotNull(includeVulnerabilitiesWithoutSlas, "includeVulnerabilitiesWithoutSlas");
        this.includeVulnerabilitiesWithoutSlas = includeVulnerabilitiesWithoutSlas;
        return this;
    }

    /**
     * Filter vulnerabilities by a specific asset ID.
     */
    public ListVulnerabilitiesRequest withVulnerableAssetId(String vulnerableAssetId) {
        Utils.checkNotNull(vulnerableAssetId, "vulnerableAssetId");
        this.vulnerableAssetId = Optional.ofNullable(vulnerableAssetId);
        return this;
    }


    /**
     * Filter vulnerabilities by a specific asset ID.
     */
    public ListVulnerabilitiesRequest withVulnerableAssetId(Optional<String> vulnerableAssetId) {
        Utils.checkNotNull(vulnerableAssetId, "vulnerableAssetId");
        this.vulnerableAssetId = vulnerableAssetId;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ListVulnerabilitiesRequest other = (ListVulnerabilitiesRequest) o;
        return 
            Utils.enhancedDeepEquals(this.auditId, other.auditId) &&
            Utils.enhancedDeepEquals(this.query, other.query) &&
            Utils.enhancedDeepEquals(this.pageSize, other.pageSize) &&
            Utils.enhancedDeepEquals(this.pageCursor, other.pageCursor) &&
            Utils.enhancedDeepEquals(this.isDeactivated, other.isDeactivated) &&
            Utils.enhancedDeepEquals(this.externalVulnerabilityId, other.externalVulnerabilityId) &&
            Utils.enhancedDeepEquals(this.isFixAvailable, other.isFixAvailable) &&
            Utils.enhancedDeepEquals(this.packageIdentifier, other.packageIdentifier) &&
            Utils.enhancedDeepEquals(this.slaDeadlineAfterDate, other.slaDeadlineAfterDate) &&
            Utils.enhancedDeepEquals(this.slaDeadlineBeforeDate, other.slaDeadlineBeforeDate) &&
            Utils.enhancedDeepEquals(this.severity, other.severity) &&
            Utils.enhancedDeepEquals(this.integrationId, other.integrationId) &&
            Utils.enhancedDeepEquals(this.includeVulnerabilitiesWithoutSlas, other.includeVulnerabilitiesWithoutSlas) &&
            Utils.enhancedDeepEquals(this.vulnerableAssetId, other.vulnerableAssetId);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            auditId, query, pageSize,
            pageCursor, isDeactivated, externalVulnerabilityId,
            isFixAvailable, packageIdentifier, slaDeadlineAfterDate,
            slaDeadlineBeforeDate, severity, integrationId,
            includeVulnerabilitiesWithoutSlas, vulnerableAssetId);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ListVulnerabilitiesRequest.class,
                "auditId", auditId,
                "query", query,
                "pageSize", pageSize,
                "pageCursor", pageCursor,
                "isDeactivated", isDeactivated,
                "externalVulnerabilityId", externalVulnerabilityId,
                "isFixAvailable", isFixAvailable,
                "packageIdentifier", packageIdentifier,
                "slaDeadlineAfterDate", slaDeadlineAfterDate,
                "slaDeadlineBeforeDate", slaDeadlineBeforeDate,
                "severity", severity,
                "integrationId", integrationId,
                "includeVulnerabilitiesWithoutSlas", includeVulnerabilitiesWithoutSlas,
                "vulnerableAssetId", vulnerableAssetId);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String auditId;

        private Optional<String> query = Optional.empty();

        private Optional<Integer> pageSize;

        private Optional<String> pageCursor = Optional.empty();

        private Optional<Boolean> isDeactivated = Optional.empty();

        private Optional<String> externalVulnerabilityId = Optional.empty();

        private Optional<Boolean> isFixAvailable = Optional.empty();

        private Optional<String> packageIdentifier = Optional.empty();

        private Optional<OffsetDateTime> slaDeadlineAfterDate = Optional.empty();

        private Optional<OffsetDateTime> slaDeadlineBeforeDate = Optional.empty();

        private Optional<? extends ExternalFindingSeverity> severity = Optional.empty();

        private Optional<String> integrationId = Optional.empty();

        private Optional<Boolean> includeVulnerabilitiesWithoutSlas = Optional.empty();

        private Optional<String> vulnerableAssetId = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        public Builder auditId(String auditId) {
            Utils.checkNotNull(auditId, "auditId");
            this.auditId = auditId;
            return this;
        }


        /**
         * Filter vulnerabilities by search query
         */
        public Builder query(String query) {
            Utils.checkNotNull(query, "query");
            this.query = Optional.ofNullable(query);
            return this;
        }

        /**
         * Filter vulnerabilities by search query
         */
        public Builder query(Optional<String> query) {
            Utils.checkNotNull(query, "query");
            this.query = query;
            return this;
        }


        public Builder pageSize(int pageSize) {
            Utils.checkNotNull(pageSize, "pageSize");
            this.pageSize = Optional.ofNullable(pageSize);
            return this;
        }

        public Builder pageSize(Optional<Integer> pageSize) {
            Utils.checkNotNull(pageSize, "pageSize");
            this.pageSize = pageSize;
            return this;
        }


        public Builder pageCursor(String pageCursor) {
            Utils.checkNotNull(pageCursor, "pageCursor");
            this.pageCursor = Optional.ofNullable(pageCursor);
            return this;
        }

        public Builder pageCursor(Optional<String> pageCursor) {
            Utils.checkNotNull(pageCursor, "pageCursor");
            this.pageCursor = pageCursor;
            return this;
        }


        /**
         * Filter vulnerabilities by deactivation status.
         */
        public Builder isDeactivated(boolean isDeactivated) {
            Utils.checkNotNull(isDeactivated, "isDeactivated");
            this.isDeactivated = Optional.ofNullable(isDeactivated);
            return this;
        }

        /**
         * Filter vulnerabilities by deactivation status.
         */
        public Builder isDeactivated(Optional<Boolean> isDeactivated) {
            Utils.checkNotNull(isDeactivated, "isDeactivated");
            this.isDeactivated = isDeactivated;
            return this;
        }


        /**
         * Filter vulnerabilities based on a specific external ID.
         */
        public Builder externalVulnerabilityId(String externalVulnerabilityId) {
            Utils.checkNotNull(externalVulnerabilityId, "externalVulnerabilityId");
            this.externalVulnerabilityId = Optional.ofNullable(externalVulnerabilityId);
            return this;
        }

        /**
         * Filter vulnerabilities based on a specific external ID.
         */
        public Builder externalVulnerabilityId(Optional<String> externalVulnerabilityId) {
            Utils.checkNotNull(externalVulnerabilityId, "externalVulnerabilityId");
            this.externalVulnerabilityId = externalVulnerabilityId;
            return this;
        }


        /**
         * Filter vulnerabilities that have an available fix.
         */
        public Builder isFixAvailable(boolean isFixAvailable) {
            Utils.checkNotNull(isFixAvailable, "isFixAvailable");
            this.isFixAvailable = Optional.ofNullable(isFixAvailable);
            return this;
        }

        /**
         * Filter vulnerabilities that have an available fix.
         */
        public Builder isFixAvailable(Optional<Boolean> isFixAvailable) {
            Utils.checkNotNull(isFixAvailable, "isFixAvailable");
            this.isFixAvailable = isFixAvailable;
            return this;
        }


        /**
         * Filter vulnerabilities that are from a specific package.
         */
        public Builder packageIdentifier(String packageIdentifier) {
            Utils.checkNotNull(packageIdentifier, "packageIdentifier");
            this.packageIdentifier = Optional.ofNullable(packageIdentifier);
            return this;
        }

        /**
         * Filter vulnerabilities that are from a specific package.
         */
        public Builder packageIdentifier(Optional<String> packageIdentifier) {
            Utils.checkNotNull(packageIdentifier, "packageIdentifier");
            this.packageIdentifier = packageIdentifier;
            return this;
        }


        /**
         * Filter vulnerabilities with a fix due after a specific timestamp
         */
        public Builder slaDeadlineAfterDate(OffsetDateTime slaDeadlineAfterDate) {
            Utils.checkNotNull(slaDeadlineAfterDate, "slaDeadlineAfterDate");
            this.slaDeadlineAfterDate = Optional.ofNullable(slaDeadlineAfterDate);
            return this;
        }

        /**
         * Filter vulnerabilities with a fix due after a specific timestamp
         */
        public Builder slaDeadlineAfterDate(Optional<OffsetDateTime> slaDeadlineAfterDate) {
            Utils.checkNotNull(slaDeadlineAfterDate, "slaDeadlineAfterDate");
            this.slaDeadlineAfterDate = slaDeadlineAfterDate;
            return this;
        }


        /**
         * Filter vulnerabilities with a fix due before a specific timestamp
         */
        public Builder slaDeadlineBeforeDate(OffsetDateTime slaDeadlineBeforeDate) {
            Utils.checkNotNull(slaDeadlineBeforeDate, "slaDeadlineBeforeDate");
            this.slaDeadlineBeforeDate = Optional.ofNullable(slaDeadlineBeforeDate);
            return this;
        }

        /**
         * Filter vulnerabilities with a fix due before a specific timestamp
         */
        public Builder slaDeadlineBeforeDate(Optional<OffsetDateTime> slaDeadlineBeforeDate) {
            Utils.checkNotNull(slaDeadlineBeforeDate, "slaDeadlineBeforeDate");
            this.slaDeadlineBeforeDate = slaDeadlineBeforeDate;
            return this;
        }


        /**
         * Filter vulnerabilities by severity.
         * Possible values: CRITICAL, HIGH, MEDIUM, LOW.
         */
        public Builder severity(ExternalFindingSeverity severity) {
            Utils.checkNotNull(severity, "severity");
            this.severity = Optional.ofNullable(severity);
            return this;
        }

        /**
         * Filter vulnerabilities by severity.
         * Possible values: CRITICAL, HIGH, MEDIUM, LOW.
         */
        public Builder severity(Optional<? extends ExternalFindingSeverity> severity) {
            Utils.checkNotNull(severity, "severity");
            this.severity = severity;
            return this;
        }


        /**
         * Filter vulnerabilities by the vulnerability scanner that detected them.
         */
        public Builder integrationId(String integrationId) {
            Utils.checkNotNull(integrationId, "integrationId");
            this.integrationId = Optional.ofNullable(integrationId);
            return this;
        }

        /**
         * Filter vulnerabilities by the vulnerability scanner that detected them.
         */
        public Builder integrationId(Optional<String> integrationId) {
            Utils.checkNotNull(integrationId, "integrationId");
            this.integrationId = integrationId;
            return this;
        }


        /**
         * Filter vulnerabilities without an SLA due date.
         */
        public Builder includeVulnerabilitiesWithoutSlas(boolean includeVulnerabilitiesWithoutSlas) {
            Utils.checkNotNull(includeVulnerabilitiesWithoutSlas, "includeVulnerabilitiesWithoutSlas");
            this.includeVulnerabilitiesWithoutSlas = Optional.ofNullable(includeVulnerabilitiesWithoutSlas);
            return this;
        }

        /**
         * Filter vulnerabilities without an SLA due date.
         */
        public Builder includeVulnerabilitiesWithoutSlas(Optional<Boolean> includeVulnerabilitiesWithoutSlas) {
            Utils.checkNotNull(includeVulnerabilitiesWithoutSlas, "includeVulnerabilitiesWithoutSlas");
            this.includeVulnerabilitiesWithoutSlas = includeVulnerabilitiesWithoutSlas;
            return this;
        }


        /**
         * Filter vulnerabilities by a specific asset ID.
         */
        public Builder vulnerableAssetId(String vulnerableAssetId) {
            Utils.checkNotNull(vulnerableAssetId, "vulnerableAssetId");
            this.vulnerableAssetId = Optional.ofNullable(vulnerableAssetId);
            return this;
        }

        /**
         * Filter vulnerabilities by a specific asset ID.
         */
        public Builder vulnerableAssetId(Optional<String> vulnerableAssetId) {
            Utils.checkNotNull(vulnerableAssetId, "vulnerableAssetId");
            this.vulnerableAssetId = vulnerableAssetId;
            return this;
        }

        public ListVulnerabilitiesRequest build() {
            if (pageSize == null) {
                pageSize = _SINGLETON_VALUE_PageSize.value();
            }

            return new ListVulnerabilitiesRequest(
                auditId, query, pageSize,
                pageCursor, isDeactivated, externalVulnerabilityId,
                isFixAvailable, packageIdentifier, slaDeadlineAfterDate,
                slaDeadlineBeforeDate, severity, integrationId,
                includeVulnerabilitiesWithoutSlas, vulnerableAssetId);
        }


        private static final LazySingletonValue<Optional<Integer>> _SINGLETON_VALUE_PageSize =
                new LazySingletonValue<>(
                        "pageSize",
                        "10",
                        new TypeReference<Optional<Integer>>() {});
    }
}
