/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.vanta.vanta_auditor_api.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.vanta.vanta_auditor_api.models.components.PartialUpdateInformationRequest;
import com.vanta.vanta_auditor_api.utils.SpeakeasyMetadata;
import com.vanta.vanta_auditor_api.utils.Utils;
import java.lang.Override;
import java.lang.String;


public class UpdateInformationRequestRequest {

    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=auditId")
    private String auditId;


    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=requestId")
    private String requestId;


    @SpeakeasyMetadata("request:mediaType=application/json")
    private PartialUpdateInformationRequest partialUpdateInformationRequest;

    @JsonCreator
    public UpdateInformationRequestRequest(
            String auditId,
            String requestId,
            PartialUpdateInformationRequest partialUpdateInformationRequest) {
        Utils.checkNotNull(auditId, "auditId");
        Utils.checkNotNull(requestId, "requestId");
        Utils.checkNotNull(partialUpdateInformationRequest, "partialUpdateInformationRequest");
        this.auditId = auditId;
        this.requestId = requestId;
        this.partialUpdateInformationRequest = partialUpdateInformationRequest;
    }

    @JsonIgnore
    public String auditId() {
        return auditId;
    }

    @JsonIgnore
    public String requestId() {
        return requestId;
    }

    @JsonIgnore
    public PartialUpdateInformationRequest partialUpdateInformationRequest() {
        return partialUpdateInformationRequest;
    }

    public static Builder builder() {
        return new Builder();
    }


    public UpdateInformationRequestRequest withAuditId(String auditId) {
        Utils.checkNotNull(auditId, "auditId");
        this.auditId = auditId;
        return this;
    }

    public UpdateInformationRequestRequest withRequestId(String requestId) {
        Utils.checkNotNull(requestId, "requestId");
        this.requestId = requestId;
        return this;
    }

    public UpdateInformationRequestRequest withPartialUpdateInformationRequest(PartialUpdateInformationRequest partialUpdateInformationRequest) {
        Utils.checkNotNull(partialUpdateInformationRequest, "partialUpdateInformationRequest");
        this.partialUpdateInformationRequest = partialUpdateInformationRequest;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UpdateInformationRequestRequest other = (UpdateInformationRequestRequest) o;
        return 
            Utils.enhancedDeepEquals(this.auditId, other.auditId) &&
            Utils.enhancedDeepEquals(this.requestId, other.requestId) &&
            Utils.enhancedDeepEquals(this.partialUpdateInformationRequest, other.partialUpdateInformationRequest);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            auditId, requestId, partialUpdateInformationRequest);
    }
    
    @Override
    public String toString() {
        return Utils.toString(UpdateInformationRequestRequest.class,
                "auditId", auditId,
                "requestId", requestId,
                "partialUpdateInformationRequest", partialUpdateInformationRequest);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String auditId;

        private String requestId;

        private PartialUpdateInformationRequest partialUpdateInformationRequest;

        private Builder() {
          // force use of static builder() method
        }


        public Builder auditId(String auditId) {
            Utils.checkNotNull(auditId, "auditId");
            this.auditId = auditId;
            return this;
        }


        public Builder requestId(String requestId) {
            Utils.checkNotNull(requestId, "requestId");
            this.requestId = requestId;
            return this;
        }


        public Builder partialUpdateInformationRequest(PartialUpdateInformationRequest partialUpdateInformationRequest) {
            Utils.checkNotNull(partialUpdateInformationRequest, "partialUpdateInformationRequest");
            this.partialUpdateInformationRequest = partialUpdateInformationRequest;
            return this;
        }

        public UpdateInformationRequestRequest build() {

            return new UpdateInformationRequestRequest(
                auditId, requestId, partialUpdateInformationRequest);
        }

    }
}
